# SPDX-License-Identifier: Unlicense
# Trait-object vtable layout dual-pin (fifty-ninth pin: slot 58 fifty-sixth Method).
# Fail-closed if TraitObjectVtable.lean, the named fixture IR, or the
# checkable writer recipe vanish. Does not require rustc/clang/llc.
# Not FullBackend. Not product Rust under src/. Not occupancy 50.
# Greppable: HOST-TRAIT-OBJECT-VTABLE, HOST-TRAIT-OBJECT-FAT,
# SLAKE_TRAIT_OBJECT_VTABLE_V0, TRAIT-OBJECT-VTABLE-IR, TraitVPtr,
# Vacant, VtblEntry::Vacant, TraitObjectFat, llvm-trait-object-vtable.
{
  requiredFiles = [
    "src/systems/SystemsLean/TraitObjectVtable.lean"
    "out/llvm-ir/trait-object-vtable.ll"
    "just/llvm-link-smoke.just"
  ];

  contentSpecs = [
    {
      rel = "src/systems/SystemsLean/TraitObjectVtable.lean";
      all = [
        "HOST-TRAIT-OBJECT-VTABLE"
        "HOST-TRAIT-OBJECT-FAT"
        "SLAKE_TRAIT_OBJECT_VTABLE_V0"
        "TRAIT-OBJECT-VTABLE-IR"
        "TraitObjectFat"
        "TraitObjectVtableValue"
        "TraitObjectRecord"
        "COMMON_VTABLE_ENTRIES"
        "VtblEntry::Method"
        "VtblEntry::Vacant"
        "VtblEntry::TraitVPtr"
        "vtableSecondMethodSlot"
        "vtableSecondMethodOffset"
        "vtableThirdMethodSlot"
        "vtableThirdMethodOffset"
        "vtableFourthMethodSlot"
        "vtableFourthMethodOffset"
        "vtableFifthMethodSlot"
        "vtableFifthMethodOffset"
        "vtableSixthMethodSlot"
        "vtableSixthMethodOffset"
        "vtableSeventhMethodSlot"
        "vtableSeventhMethodOffset"
        "vtableEighthMethodSlot"
        "vtableEighthMethodOffset"
        "vtableNinthMethodSlot"
        "vtableNinthMethodOffset"
        "vtableTenthMethodSlot"
        "vtableTenthMethodOffset"
        "vtableEleventhMethodSlot"
        "vtableEleventhMethodOffset"
        "vtableTwelfthMethodSlot"
        "vtableTwelfthMethodOffset"
        "vtableThirteenthMethodSlot"
        "vtableThirteenthMethodOffset"
        "vtableFourteenthMethodSlot"
        "vtableFourteenthMethodOffset"
        "vtableFifteenthMethodSlot"
        "vtableFifteenthMethodOffset"
        "vtableSixteenthMethodSlot"
        "vtableSixteenthMethodOffset"
        "vtableSeventeenthMethodSlot"
        "vtableSeventeenthMethodOffset"
        "vtableEighteenthMethodSlot"
        "vtableEighteenthMethodOffset"
        "vtableNineteenthMethodSlot"
        "vtableNineteenthMethodOffset"
        "vtableTwentiethMethodSlot"
        "vtableTwentiethMethodOffset"
        "vtableTwentyFirstMethodSlot"
        "vtableTwentyFirstMethodOffset"
        "vtableTwentySecondMethodSlot"
        "vtableTwentySecondMethodOffset"
        "vtableTwentyThirdMethodSlot"
        "vtableTwentyThirdMethodOffset"
        "vtableTwentyFourthMethodSlot"
        "vtableTwentyFourthMethodOffset"
        "vtableTwentyFifthMethodSlot"
        "vtableTwentyFifthMethodOffset"
        "vtableTwentySixthMethodSlot"
        "vtableTwentySixthMethodOffset"
        "vtableTwentySeventhMethodSlot"
        "vtableTwentySeventhMethodOffset"
        "vtableTwentyEighthMethodSlot"
        "vtableTwentyEighthMethodOffset"
        "vtableTwentyNinthMethodSlot"
        "vtableTwentyNinthMethodOffset"
        "vtableThirtiethMethodSlot"
        "vtableThirtiethMethodOffset"
        "vtableThirtyFirstMethodSlot"
        "vtableThirtyFirstMethodOffset"
        "vtableThirtySecondMethodSlot"
        "vtableThirtySecondMethodOffset"
        "vtableThirtyThirdMethodSlot"
        "vtableThirtyThirdMethodOffset"
        "vtableThirtyFourthMethodSlot"
        "vtableThirtyFourthMethodOffset"
        "vtableThirtyFifthMethodSlot"
        "vtableThirtyFifthMethodOffset"
        "vtableThirtySixthMethodSlot"
        "vtableThirtySixthMethodOffset"
        "vtableThirtySeventhMethodSlot"
        "vtableThirtySeventhMethodOffset"
        "vtableThirtyEighthMethodSlot"
        "vtableThirtyEighthMethodOffset"
        "vtableThirtyNinthMethodSlot"
        "vtableThirtyNinthMethodOffset"
        "vtableFortiethMethodSlot"
        "vtableFortiethMethodOffset"
        "vtableFortyFirstMethodSlot"
        "vtableFortyFirstMethodOffset"
        "vtableFortySecondMethodSlot"
        "vtableFortySecondMethodOffset"
        "vtableFortyThirdMethodSlot"
        "vtableFortyThirdMethodOffset"
        "vtableFortyFourthMethodSlot"
        "vtableFortyFourthMethodOffset"
        "vtableFortyFifthMethodSlot"
        "vtableFortyFifthMethodOffset"
        "vtableFortySixthMethodSlot"
        "vtableFortySixthMethodOffset"
        "vtableFortySeventhMethodSlot"
        "vtableFortySeventhMethodOffset"
        "vtableFortyEighthMethodSlot"
        "vtableFortyEighthMethodOffset"
        "vtableFortyNinthMethodSlot"
        "vtableFortyNinthMethodOffset"
        "vtableFiftiethMethodSlot"
        "vtableFiftiethMethodOffset"
        "vtableFiftyFirstMethodSlot"
        "vtableFiftyFirstMethodOffset"
        "vtableFiftySecondMethodSlot"
        "vtableFiftySecondMethodOffset"
        "vtableFiftyThirdMethodSlot"
        "vtableFiftyThirdMethodOffset"
        "vtableFiftyFourthMethodSlot"
        "vtableFiftyFourthMethodOffset"
        "vtableFiftyFifthMethodSlot"
        "vtableFiftyFifthMethodOffset"
        "vtableFiftySixthMethodSlot"
        "vtableFiftySixthMethodOffset"
        "vtableFiftySeventhMethodSlot"
        "vtableFiftySeventhMethodOffset"
        "vtableFiftyEighthMethodSlot"
        "vtableFiftyEighthMethodOffset"
        "vtableFiftyNinthMethodSlot"
        "vtableFiftyNinthMethodOffset"
        "vtableSixtiethMethodSlot"
        "vtableSixtiethMethodOffset"
        "vtableSixtyFirstMethodSlot"
        "vtableSixtyFirstMethodOffset"
        "vtableSixtySecondMethodSlot"
        "vtableSixtySecondMethodOffset"
        "vtableSixtyFifthMethodSlot"
        "vtableSixtyFifthMethodOffset"
        "vtableSixtySixthMethodSlot"
        "vtableSixtySixthMethodOffset"
        "vtableSixtySeventhMethodSlot"
        "vtableSixtySeventhMethodOffset"
        "vtableSixtyEighthMethodSlot"
        "vtableSixtyEighthMethodOffset"
        "vtableSixtyNinthMethodSlot"
        "vtableSixtyNinthMethodOffset"
        "vtableSeventyFirstMethodSlot"
        "vtableSeventyFirstMethodOffset"
        "vtableSeventySecondMethodSlot"
        "vtableSeventySecondMethodOffset"
        "vtableSeventyThirdMethodSlot"
        "vtableSeventyThirdMethodOffset"
        "vtableSeventyFourthMethodSlot"
        "vtableSeventyFourthMethodOffset"
        "vtableSeventyFifthMethodSlot"
        "vtableSeventyFifthMethodOffset"
        "vtableSeventySixthMethodSlot"
        "vtableSeventySixthMethodOffset"
        "vtableSeventySeventhMethodSlot"
        "vtableSeventySeventhMethodOffset"
        "vtableSeventyEighthMethodSlot"
        "vtableSeventyEighthMethodOffset"
        "vtableSeventyNinthMethodSlot"
        "vtableSeventyNinthMethodOffset"
        "vtableEightyFirstMethodSlot"
        "vtableEightyFirstMethodOffset"
        "vtableEightySecondMethodSlot"
        "vtableEightySecondMethodOffset"
        "vtableEightyThirdMethodSlot"
        "vtableEightyThirdMethodOffset"
        "vtableEightyFourthMethodSlot"
        "vtableEightyFourthMethodOffset"
        "vtableEightyFifthMethodSlot"
        "vtableEightyFifthMethodOffset"
        "vtableEightySixthMethodSlot"
        "vtableEightySixthMethodOffset"
        "vtableEightySeventhMethodSlot"
        "vtableEightySeventhMethodOffset"
        "vtableEightyEighthMethodSlot"
        "vtableEightyEighthMethodOffset"
        "vtableEightyNinthMethodSlot"
        "vtableEightyNinthMethodOffset"
        "vtableNinetiethMethodSlot"
        "vtableNinetiethMethodOffset"
        "vtableFirstVacantSlot"
        "vtableVacantOffset"
        "vtableFirstTraitVPtrSlot"
        "vtableTraitVPtrOffset"
        "x86_64-unknown-linux-gnu"
        "llvm-trait-object-vtable"
        "def traitObjectVtableFullBackendClaimed : Bool := false"
        "theorem traitObjectVtableFullBackendClaimed_false"
        "def traitObjectVtableProductionEmitClaimed : Bool := false"
      ];
      forbidden = [
        "def traitObjectVtableFullBackendClaimed : Bool := true"
        "def traitObjectVtableFullHostClaimed : Bool := true"
        "def traitObjectVtableOccupancyMemberClaimed : Bool := true"
        "def traitObjectVtableProductionEmitClaimed : Bool := true"
      ];
    }
    {
      rel = "out/llvm-ir/trait-object-vtable.ll";
      all = [
        "SLAKE_TRAIT_OBJECT_VTABLE_V0"
        "HOST-TRAIT-OBJECT-VTABLE"
        "HOST-TRAIT-OBJECT-FAT"
        "TraitObjectRecord"
        "drop_in_place"
        "slake_trait_object_method0"
        "slake_trait_object_method1"
        "slake_trait_object_method2"
        "slake_trait_object_method3"
        "slake_trait_object_method4"
        "slake_trait_object_method5"
        "slake_trait_object_method6"
        "slake_trait_object_method7"
        "slake_trait_object_method8"
        "slake_trait_object_method9"
        "slake_trait_object_method10"
        "slake_trait_object_method11"
        "slake_trait_object_method12"
        "slake_trait_object_method13"
        "slake_trait_object_method14"
        "slake_trait_object_method15"
        "slake_trait_object_method16"
        "slake_trait_object_method17"
        "slake_trait_object_method18"
        "slake_trait_object_method19"
        "slake_trait_object_method20"
        "slake_trait_object_method21"
        "slake_trait_object_method22"
        "slake_trait_object_method23"
        "slake_trait_object_method24"
        "slake_trait_object_method25"
        "slake_trait_object_method26"
        "slake_trait_object_method27"
        "slake_trait_object_method28"
        "slake_trait_object_method29"
        "slake_trait_object_method30"
        "slake_trait_object_method31"
        "slake_trait_object_method32"
        "slake_trait_object_method33"
        "slake_trait_object_method34"
        "slake_trait_object_method35"
        "slake_trait_object_method36"
        "slake_trait_object_method37"
        "slake_trait_object_method38"
        "slake_trait_object_method39"
        "slake_trait_object_method40"
        "slake_trait_object_method41"
        "slake_trait_object_method42"
        "slake_trait_object_method43"
        "slake_trait_object_method44"
        "slake_trait_object_method45"
        "slake_trait_object_method46"
        "slake_trait_object_method47"
        "slake_trait_object_method48"
        "slake_trait_object_method49"
        "slake_trait_object_method50"
        "slake_trait_object_method51"
        "slake_trait_object_method52"
        "slake_trait_object_method53"
        "slake_trait_object_method54"
        "slake_trait_object_method55"
        "slake_trait_object_method56"
        "slake_trait_object_method57"
        "slake_trait_object_method58"
        "slake_trait_object_method59"
        "slake_trait_object_method60"
        "slake_trait_object_method61"
        "slake_trait_object_method62"
        "slake_trait_object_method63"
        "slake_trait_object_method64"
        "slake_trait_object_method65"
        "slake_trait_object_method66"
        "slake_trait_object_method67"
        "slake_trait_object_method68"
        "slake_trait_object_method69"
        "slake_trait_object_method70"
        "slake_trait_object_method71"
        "slake_trait_object_method72"
        "slake_trait_object_method73"
        "slake_trait_object_method74"
        "slake_trait_object_method75"
        "slake_trait_object_method76"
        "slake_trait_object_method77"
        "slake_trait_object_method78"
        "slake_trait_object_method79"
        "slake_trait_object_method80"
        "slake_trait_object_method81"
        "slake_trait_object_method82"
        "slake_trait_object_method83"
        "slake_trait_object_method84"
        "slake_trait_object_method85"
        "slake_trait_object_method86"
        "slake_trait_object_method87"
        "slake_trait_object_method88"
        "slake_trait_object_method89"
        "slake_trait_object_method90"
        "slake_trait_object_method91"
        "slake_trait_object_method92"
        "slake_trait_object_method93"
        "slake_trait_object_method94"
        "slake_trait_object_method95"
        "slake_trait_object_supertrait_vtable"
        "TraitVPtr"
        "Vacant"
        "VtblEntry::Vacant"
        "slot 4"
        "slot 5"
        "slot 6"
        "slot 7"
        "slot 8"
        "slot 9"
        "slot 10"
        "slot 11"
        "slot 12"
        "slot 13"
        "slot 14"
        "slot 15"
        "slot 16"
        "slot 17"
        "slot 18"
        "slot 19"
        "slot 20"
        "slot 21"
        "slot 22"
        "slot 23"
        "slot 24"
        "slot 25"
        "slot 26"
        "slot 27"
        "slot 28"
        "slot 29"
        "slot 30"
        "slot 31"
        "slot 32"
        "slot 33"
        "slot 34"
        "slot 35"
        "slot 36"
        "slot 37"
        "slot 38"
        "slot 39"
        "slot 40"
        "slot 41"
        "slot 42"
        "slot 43"
        "slot 44"
        "slot 45"
        "slot 46"
        "slot 47"
        "slot 48"
        "slot 49"
        "slot 50"
        "slot 51"
        "slot 52"
        "slot 53"
        "slot 54"
        "slot 55"
        "slot 56"
        "slot 57"
        "slot 58"
        "slot 59"
        "slot 60"
        "slot 61"
        "slot 62"
        "slot 63"
        "slot 64"
        "slot 65"
        "slot 66"
        "slot 67"
        "slot 68"
        "slot 69"
        "slot 70"
        "slot 71"
        "slot 72"
        "slot 73"
        "slot 74"
        "slot 75"
        "slot 76"
        "slot 77"
        "slot 78"
        "slot 79"
        "slot 80"
        "slot 7 method4 offset 56"
        "slot 8 method5 offset 64"
        "slot 9 method6 offset 72"
        "slot 10 method7 offset 80"
        "slot 11 method8 offset 88"
        "slot 12 method9 offset 96"
        "slot 13 method10 offset 104"
        "slot 14 method11 offset 112"
        "slot 15 method12 offset 120"
        "slot 16 method13 offset 128"
        "slot 17 method14 offset 136"
        "slot 18 method15 offset 144"
        "slot 19 method16 offset 152"
        "slot 20 method17 offset 160"
        "slot 21 method18 offset 168"
        "slot 22 method19 offset 176"
        "slot 23 method20 offset 184"
        "slot 24 method21 offset 192"
        "slot 25 method22 offset 200"
        "slot 26 method23 offset 208"
        "slot 27 method24 offset 216"
        "slot 28 method25 offset 224"
        "slot 29 method26 offset 232"
        "slot 30 method27 offset 240"
        "slot 31 method28 offset 248"
        "slot 32 method29 offset 256"
        "slot 33 method30 offset 264"
        "slot 34 method31 offset 272"
        "slot 35 method32 offset 280"
        "slot 36 method33 offset 288"
        "slot 37 method34 offset 296"
        "slot 38 method35 offset 304"
        "slot 39 method36 offset 312"
        "slot 40 method37 offset 320"
        "slot 41 method38 offset 328"
        "slot 42 method39 offset 336"
        "slot 43 method40 offset 344"
        "slot 44 method41 offset 352"
        "slot 45 method42 offset 360"
        "slot 46 method43 offset 368"
        "slot 47 method44 offset 376"
        "slot 48 method45 offset 384"
        "slot 49 method46 offset 392"
        "slot 50 method47 offset 400"
        "slot 51 method48 offset 408"
        "slot 52 method49 offset 416"
        "slot 53 method50 offset 424"
        "slot 54 method51 offset 432"
        "slot 55 method52 offset 440"
        "slot 56 method53 offset 448"
        "slot 57 method54 offset 456"
        "slot 58 method55 offset 464"
        "slot 59 method56 offset 472"
        "slot 60 method57 offset 480"
        "slot 61 method58 offset 488"
        "slot 62 method59 offset 496"
        "slot 63 method60 offset 504"
        "slot 64 method61 offset 512"
        "slot 65 method62 offset 520"
        "slot 66 method63 offset 528"
        "slot 67 method64 offset 536"
        "slot 68 method65 offset 544"
        "slot 69 method66 offset 552"
        "slot 70 method67 offset 560"
        "slot 71 method68 offset 568"
        "slot 72 method69 offset 576"
        "slot 73 method70 offset 584"
        "slot 74 method71 offset 592"
        "slot 75 method72 offset 600"
        "slot 76 method73 offset 608"
        "slot 77 method74 offset 616"
        "slot 78 method75 offset 624"
        "slot 79 method76 offset 632"
        "slot 80 method77 offset 640"
        "slot 81 method78 offset 648"
        "slot 82 method79 offset 656"
        "slot 83 method80 offset 664"
        "slot 84 method81 offset 672"
        "slot 85 method82 offset 680"
        "slot 86 method83 offset 688"
        "slot 87 method84 offset 696"
        "slot 88 method85 offset 704"
        "slot 89 method86 offset 712"
        "slot 90 method87 offset 720"
        "slot 91 method88 offset 728"
        "slot 92 method89 offset 736"
        "slot 93 method90 offset 744"
        "slot 94 method91 offset 752"
        "slot 95 method92 offset 760"
        "slot 96 method93 offset 768"
        "slot 97 method94 offset 776"
        "slot 98 method95 offset 784"
        "slot 99 method96 offset 792"
        "slot 100 method97 offset 800"
        "slot 131 Vacant offset 1048"
        "slot 132 TraitVPtr offset 1056"
        "133 slots, 1064 bytes"
        "rustc_abi pointer"
        "not FullBackend"
      ];
    }
    {
      rel = "just/llvm-link-smoke.just";
      all = [
        "llvm-trait-object-vtable:"
        "llvm-trait-object-vtable-check:"
        "HOST-TRAIT-OBJECT-VTABLE"
        "HOST-TRAIT-OBJECT-FAT"
        "SLAKE_TRAIT_OBJECT_VTABLE_V0"
        "TRAIT-OBJECT-VTABLE-IR"
        "TraitVPtr"
        "Vacant"
        "method1"
        "method2"
        "method3"
        "method4"
        "method5"
        "method6"
        "method7"
        "method8"
        "method9"
        "method10"
        "method11"
        "method12"
        "method13"
        "method14"
        "method15"
        "method16"
        "method17"
        "method18"
        "method19"
        "method20"
        "method21"
        "method22"
        "method23"
        "method24"
        "method25"
        "method26"
        "method27"
        "method28"
        "method29"
        "method30"
        "method31"
        "method32"
        "method33"
        "method34"
        "method35"
        "method36"
        "method37"
        "method38"
        "method39"
        "method40"
        "method41"
        "method42"
        "method43"
        "method44"
        "method45"
        "method46"
        "method47"
        "method48"
        "method49"
        "method50"
        "method51"
        "method52"
        "method53"
        "method54"
        "method55"
        "method56"
        "method57"
        "method58"
        "method59"
        "method60"
        "method61"
        "method62"
        "method63"
        "method64"
        "method65"
        "method66"
        "method67"
        "method68"
        "method69"
        "method70"
        "method71"
        "method72"
        "method73"
        "method74"
        "method75"
        "method76"
        "method77"
        "method78"
        "method79"
        "method80"
        "method81"
        "method82"
        "method83"
        "method84"
        "method85"
        "method86"
        "method87"
        "method88"
        "method89"
        "method90"
        "method91"
        "method92"
        "method93"
        "method94"
        "method95"
        "not FullBackend"
      ];
    }
  ];
}
