# SPDX-License-Identifier: Unlicense
# Pure Nix systems emit-wire presence: compile/emit drivers, freestanding emit
# product tokens (UNIT_TRANSLATION_V0 through EMIT_BODY_V0), UNIT_DEEPEN_V1
# units + companions, optional release surface, dynamic unit-surface walk, and
# required hosted behavioral probe path (smoke debt under src/systems/smoke/;
# not product emit residual). Fail-closed on missing required paths or honesty
# tokens. No bash, no ripgrep, no Python.
#
#   import ./systems-emit-wire { inherit lib; root = novelSourceOrRepo; }
#   -> { ok, violations, summary }
#
# Specs data: ./specs.nix. Flake: checks.systems-emit-wire.
# Live gate (does not require git-tracked flake store): just systems-emit-wire
# Workspace check.sh deleted; link/run smoke is just systems-cc-probe process glue.
{ lib, root }:
let
  specs = import ./specs.nix;
  inherit (specs)
    requiredFiles
    optionalFiles
    contentSpecs
    optionalContentSpecs
    unitWalkRoot
    unitWalkSkipDirs
    unitWalkExtensions
    unitSurfaceRequiredAny
    unitSurfaceRequiredAll
    unitSurfaceModuleAny
    emitH
    emitC
    releaseH
    releaseC
    residualFreeMeasureStageId
    residualFreeMeasureHostId
    residualFreeMeasureSelfHostId
    forbiddenManagedResidual
    requiredFreestandingHonesty
    productOutBbarOwnership
    productOutBbarApis
    productKernelSelfApplyStageId
    productKernelSelfApplyHostId
    productKernelSelfApplySelfHostId
    productKernelSelfApplyModulePath
    productKernelSelfApplyModuleTokens
    productKernelSelfApplyModuleForbiddenTokens
    productOutKernelStageId
    productOutKernelHostId
    productOutKernelSelfHostId
    productOutKernelModulePath
    productOutKernelModuleTokens
    productOutKernelModuleForbiddenTokens
    productPathBootstrapStageId
    productPathBootstrapHostId
    productPathBootstrapSelfHostId
    productPathBootstrapWriterPath
    freestandingEmitLoadPath
    freestandingEmitLoadScaffoldPath
    productPathBootstrapWriterTokens
    productPathBootstrapWriterLoadTokens
    productPathBootstrapAcceptanceTokens
    productPathBootstrapModulePath
    productPathBootstrapModuleTokens
    productPathBootstrapModuleForbiddenTokens
    productWriterSurfaceStageId
    productWriterSurfaceHostId
    productWriterSurfaceSelfHostId
    productWriterSurfaceOwnership
    productWriterSurfaceApis
    productWriterSurfaceAcceptanceTokens
    productWriterSurfaceModulePath
    productWriterSurfaceModuleTokens
    productWriterSurfaceModuleForbiddenTokens
    productWriterPathPlanStageId
    productWriterPathPlanHostId
    productWriterPathPlanSelfHostId
    productWriterPathPlanStepTokens
    productWriterPathPlanAcceptanceTokens
    productWriterPathPlanModulePath
    productWriterPathPlanModuleTokens
    productWriterPathPlanModuleForbiddenTokens
    productWriterPathExecutionStageId
    productWriterPathExecutionHostId
    productWriterPathExecutionSelfHostId
    productWriterPathExecutionWriterTokens
    productWriterPathExecutionLoadTokens
    productWriterPathExecutionLoadScaffoldTokens
    productWriterPathExecutionInstallPath
    productWriterPathExecutionInstallTokens
    productWriterPathExecutionAcceptanceTokens
    productWriterPathExecModulePath
    productWriterPathExecModuleTokens
    productWriterPathExecModuleForbiddenTokens
    productPathOwnershipStageId
    productPathOwnershipHostId
    productPathOwnershipSelfHostId
    productPathOwnershipSsotPaths
    productPathOwnershipEmitPaths
    productPathOwnershipAcceptanceTokens
    productPathOwnershipInputsModulePath
    productPathOwnershipInputsModuleTokens
    productPathOwnershipInputsModuleForbiddenTokens
    productPathPerformStageId
    productPathPerformHostId
    productPathPerformSelfHostId
    productPathPerformLakeWriterPath
    productPathPerformLakeWriterTokens
    productPathPerformLakeLoadTokens
    productPathPerformLakeLoadPath
    productPathPerformInstallPath
    productPathPerformInstallTokens
    productPathPerformAcceptanceTokens
    productPathPerformModulePath
    productPathPerformModuleTokens
    productPathPerformModuleForbiddenTokens
    productPathPerformStepStageId
    productPathPerformStepHostId
    productPathPerformStepSelfHostId
    productPathPerformStepInstallPath
    productPathPerformStepInstallTokens
    productPathPerformStepInstallForbiddenCmdPrefixes
    productPathPerformStepAcceptanceTokens
    productPathPerformStepModulePath
    productPathPerformStepModuleTokens
    productPathPerformStepModuleForbiddenTokens
    productPathPerformReadStageId
    productPathPerformReadHostId
    productPathPerformReadSelfHostId
    productPathPerformReadModulePath
    productPathPerformReadModuleTokens
    productPathPerformReadModuleForbiddenTokens
    productPathPerformReadLakefilePath
    productPathPerformReadLakefileTokens
    productPathPerformReadJustPath
    productPathPerformReadJustTokens
    productPathPerformReadAcceptanceTokens
    productPathPerformComposeStageId
    productPathPerformComposeHostId
    productPathPerformComposeSelfHostId
    productPathPerformComposeModulePath
    productPathPerformComposeModuleTokens
    productPathPerformComposeModuleForbiddenTokens
    productPathPerformComposeLakefilePath
    productPathPerformComposeLakefileTokens
    productPathPerformComposeJustPath
    productPathPerformComposeJustTokens
    productPathPerformComposeAcceptanceTokens
    productPathPerformWriteHcStageId
    productPathPerformWriteHcHostId
    productPathPerformWriteHcSelfHostId
    productPathPerformWriteHcModulePath
    productPathPerformWriteHcModuleTokens
    productPathPerformWriteHcModuleForbiddenTokens
    productPathPerformWriteHcLakefilePath
    productPathPerformWriteHcLakefileTokens
    productPathPerformWriteHcJustPath
    productPathPerformWriteHcJustTokens
    productPathPerformWriteHcAcceptanceTokens
    productPathFreestandingCapableStageId
    productPathFreestandingCapableHostId
    productPathFreestandingCapableSelfHostId
    productPathFreestandingCapableModulePath
    productPathFreestandingCapableModuleTokens
    productPathFreestandingCapableModuleForbiddenTokens
    productPathFreestandingCapableLakefilePath
    productPathFreestandingCapableLakefileTokens
    productPathFreestandingCapableJustPath
    productPathFreestandingCapableJustTokens
    productPathFreestandingCapableAcceptanceTokens
    productPathFreestandingCapableStepContractStageId
    productPathFreestandingCapableStepContractHostId
    productPathFreestandingCapableStepContractSelfHostId
    productPathFreestandingCapableStepContractModulePath
    productPathFreestandingCapableStepContractModuleTokens
    productPathFreestandingCapableStepContractModuleForbiddenTokens
    productPathFreestandingCapableStepContractLakefilePath
    productPathFreestandingCapableStepContractLakefileTokens
    productPathFreestandingCapableStepContractJustPath
    productPathFreestandingCapableStepContractJustTokens
    productPathFreestandingCapableStepContractAcceptanceTokens
    productPathFreestandingCapableReadStageId
    productPathFreestandingCapableReadHostId
    productPathFreestandingCapableReadSelfHostId
    productPathFreestandingCapableReadModulePath
    productPathFreestandingCapableReadModuleTokens
    productPathFreestandingCapableReadModuleForbiddenTokens
    productPathFreestandingCapableReadLakefilePath
    productPathFreestandingCapableReadLakefileTokens
    productPathFreestandingCapableReadJustPath
    productPathFreestandingCapableReadJustTokens
    productPathFreestandingCapableReadAcceptanceTokens
    productPathFreestandingCapableComposeStageId
    productPathFreestandingCapableComposeHostId
    productPathFreestandingCapableComposeSelfHostId
    productPathFreestandingCapableComposeModulePath
    productPathFreestandingCapableComposeModuleTokens
    productPathFreestandingCapableComposeModuleForbiddenTokens
    productPathFreestandingCapableComposeLakefilePath
    productPathFreestandingCapableComposeLakefileTokens
    productPathFreestandingCapableComposeJustPath
    productPathFreestandingCapableComposeJustTokens
    productPathFreestandingCapableComposeAcceptanceTokens
    productPathFreestandingCapableWriteHcStageId
    productPathFreestandingCapableWriteHcHostId
    productPathFreestandingCapableWriteHcSelfHostId
    productPathFreestandingCapableWriteHcModulePath
    productPathFreestandingCapableWriteHcLoadPath
    productPathFreestandingCapableWriteHcModuleTokens
    productPathFreestandingCapableWriteHcLoadTokens
    productPathFreestandingCapableWriteHcModuleForbiddenTokens
    productPathFreestandingCapableWriteHcLakefilePath
    productPathFreestandingCapableWriteHcLakefileTokens
    productPathFreestandingCapableWriteHcJustPath
    productPathFreestandingCapableWriteHcJustTokens
    productPathFreestandingCapableWriteHcAcceptanceTokens
    productPathFreestandingCapableRegenerateStageId
    productPathFreestandingCapableRegenerateHostId
    productPathFreestandingCapableRegenerateSelfHostId
    productPathFreestandingCapableRegenerateModulePath
    productPathFreestandingCapableRegenerateModuleTokens
    productPathFreestandingCapableRegenerateModuleForbiddenTokens
    productPathFreestandingCapableRegenerateLakefilePath
    productPathFreestandingCapableRegenerateLakefileTokens
    productPathFreestandingCapableRegenerateJustPath
    productPathFreestandingCapableRegenerateJustTokens
    productPathFreestandingCapableRegenerateAcceptanceTokens
    productPathFreestandingCapableInstallOutStageId
    productPathFreestandingCapableInstallOutHostId
    productPathFreestandingCapableInstallOutSelfHostId
    productPathFreestandingCapableInstallOutModulePath
    productPathFreestandingCapableInstallOutModuleTokens
    productPathFreestandingCapableInstallOutModuleForbiddenTokens
    productPathFreestandingCapableInstallOutLakefilePath
    productPathFreestandingCapableInstallOutLakefileTokens
    productPathFreestandingCapableInstallOutJustPath
    productPathFreestandingCapableInstallOutJustTokens
    productPathFreestandingCapableInstallOutAcceptanceTokens
    productPathFreestandingCapableFullBarStageId
    productPathFreestandingCapableFullBarHostId
    productPathFreestandingCapableFullBarSelfHostId
    productPathFreestandingCapableFullBarModulePath
    productPathFreestandingCapableFullBarModuleTokens
    productPathFreestandingCapableFullBarModuleForbiddenTokens
    productPathFreestandingCapableFullBarLakefilePath
    productPathFreestandingCapableFullBarLakefileTokens
    productPathFreestandingCapableFullBarJustPath
    productPathFreestandingCapableFullBarJustTokens
    productPathFreestandingCapableFullBarAcceptanceTokens
    productPathOwnershipRegenerateStageId
    productPathOwnershipRegenerateHostId
    productPathOwnershipRegenerateSelfHostId
    productPathOwnershipRegenerateModulePath
    productPathOwnershipRegenerateModuleTokens
    productPathOwnershipRegenerateModuleForbiddenTokens
    productPathOwnershipRegenerateLakefilePath
    productPathOwnershipRegenerateLakefileTokens
    productPathOwnershipRegenerateJustPath
    productPathOwnershipRegenerateJustTokens
    productPathOwnershipRegenerateAcceptanceTokens
    productPathFreestandingPerformEvidenceStageId
    productPathFreestandingPerformEvidenceHostId
    productPathFreestandingPerformEvidenceSelfHostId
    productPathFreestandingPerformEvidenceModulePath
    productPathFreestandingPerformEvidenceModuleTokens
    productPathFreestandingPerformEvidenceModuleForbiddenTokens
    productPathFreestandingPerformEvidenceLakefilePath
    productPathFreestandingPerformEvidenceLakefileTokens
    productPathFreestandingPerformEvidenceJustPath
    productPathFreestandingPerformEvidenceJustTokens
    productPathFreestandingPerformEvidenceAcceptanceTokens
    productPathFreestandingPerformOfficialPathStageId
    productPathFreestandingPerformOfficialPathHostId
    productPathFreestandingPerformOfficialPathSelfHostId
    productPathFreestandingPerformOfficialPathModulePath
    productPathFreestandingPerformOfficialPathModuleTokens
    productPathFreestandingPerformOfficialPathModuleForbiddenTokens
    productPathFreestandingPerformOfficialPathLakefilePath
    productPathFreestandingPerformOfficialPathLakefileTokens
    productPathFreestandingPerformOfficialPathJustPath
    productPathFreestandingPerformOfficialPathJustTokens
    productPathFreestandingPerformOfficialPathAcceptanceTokens
    productPathFreestandingPerformOfficialPathAlternateStageId
    productPathFreestandingPerformOfficialPathAlternateHostId
    productPathFreestandingPerformOfficialPathAlternateSelfHostId
    productPathFreestandingPerformOfficialPathAlternateModulePath
    productPathFreestandingPerformOfficialPathAlternateModuleTokens
    productPathFreestandingPerformOfficialPathAlternateModuleForbiddenTokens
    productPathFreestandingPerformOfficialPathAlternateLakefilePath
    productPathFreestandingPerformOfficialPathAlternateLakefileTokens
    productPathFreestandingPerformOfficialPathAlternateJustPath
    productPathFreestandingPerformOfficialPathAlternateJustTokens
    productPathFreestandingPerformOfficialPathAlternateAcceptanceTokens
    productPathFreestandingPerformDualEqualityWriteParityStageId
    productPathFreestandingPerformDualEqualityWriteParityHostId
    productPathFreestandingPerformDualEqualityWriteParitySelfHostId
    productPathFreestandingPerformDualEqualityWriteParityModulePath
    productPathFreestandingPerformDualEqualityWriteParityModuleTokens
    productPathFreestandingPerformDualEqualityWriteParityModuleForbiddenTokens
    productPathFreestandingPerformDualEqualityWriteParityLakefilePath
    productPathFreestandingPerformDualEqualityWriteParityLakefileTokens
    productPathFreestandingPerformDualEqualityWriteParityJustPath
    productPathFreestandingPerformDualEqualityWriteParityJustTokens
    productPathFreestandingPerformDualEqualityWriteParityAcceptanceTokens
    productPathFreestandingPerformDualEqualityWriteClosePathStageId
    productPathFreestandingPerformDualEqualityWriteClosePathHostId
    productPathFreestandingPerformDualEqualityWriteClosePathSelfHostId
    productPathFreestandingPerformDualEqualityWriteClosePathModulePath
    productPathFreestandingPerformDualEqualityWriteClosePathModuleTokens
    productPathFreestandingPerformDualEqualityWriteClosePathModuleForbiddenTokens
    productPathFreestandingPerformDualEqualityWriteClosePathLakefilePath
    productPathFreestandingPerformDualEqualityWriteClosePathLakefileTokens
    productPathFreestandingPerformDualEqualityWriteClosePathJustPath
    productPathFreestandingPerformDualEqualityWriteClosePathJustTokens
    productPathFreestandingPerformDualEqualityWriteClosePathAcceptanceTokens
    productPathFreestandingPerformDualEqualityWriteApiStageId
    productPathFreestandingPerformDualEqualityWriteApiHostId
    productPathFreestandingPerformDualEqualityWriteApiSelfHostId
    productPathFreestandingPerformDualEqualityWriteApiModulePath
    productPathFreestandingPerformDualEqualityWriteApiLoadPath
    productPathFreestandingPerformDualEqualityWriteApiModuleTokens
    productPathFreestandingPerformDualEqualityWriteApiLoadTokens
    productPathFreestandingPerformDualEqualityWriteApiModuleForbiddenTokens
    productPathFreestandingPerformDualEqualityWriteApiLakefilePath
    productPathFreestandingPerformDualEqualityWriteApiLakefileTokens
    productPathFreestandingPerformDualEqualityWriteApiJustPath
    productPathFreestandingPerformDualEqualityWriteApiJustTokens
    productPathFreestandingPerformDualEqualityWriteApiAcceptanceTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapStageId
    productPathFreestandingPerformDualEqualityWriteCapableGapHostId
    productPathFreestandingPerformDualEqualityWriteCapableGapSelfHostId
    productPathFreestandingPerformDualEqualityWriteCapableGapModulePath
    productPathFreestandingPerformDualEqualityWriteCapableGapModuleTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapModuleForbiddenTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapLakefilePath
    productPathFreestandingPerformDualEqualityWriteCapableGapLakefileTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapJustPath
    productPathFreestandingPerformDualEqualityWriteCapableGapJustTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapAcceptanceTokens
    productPathOfficialPathRetireOfficialStageId
    productPathOfficialPathRetireOfficialHostId
    productPathOfficialPathRetireOfficialSelfHostId
    productPathOfficialPathRetireOfficialModulePath
    productPathOfficialPathRetireOfficialModuleTokens
    productPathOfficialPathRetireOfficialModuleForbiddenTokens
    productPathOfficialPathRetireOfficialLakefilePath
    productPathOfficialPathRetireOfficialLakefileTokens
    productPathOfficialPathRetireOfficialJustPath
    productPathOfficialPathRetireOfficialJustTokens
    productPathOfficialPathRetireOfficialAcceptanceTokens
    productPathFreestandingPerformClaimedStageId
    productPathFreestandingPerformClaimedHostId
    productPathFreestandingPerformClaimedSelfHostId
    productPathFreestandingPerformClaimedModulePath
    productPathFreestandingPerformClaimedModuleTokens
    productPathFreestandingPerformClaimedModuleForbiddenTokens
    productPathFreestandingPerformClaimedLakefilePath
    productPathFreestandingPerformClaimedLakefileTokens
    productPathFreestandingPerformClaimedJustPath
    productPathFreestandingPerformClaimedJustTokens
    productPathFreestandingPerformClaimedAcceptanceTokens
    productPathFreestandingOwnershipClaimedStageId
    productPathFreestandingOwnershipClaimedHostId
    productPathFreestandingOwnershipClaimedSelfHostId
    productPathFreestandingOwnershipClaimedModulePath
    productPathFreestandingOwnershipClaimedModuleTokens
    productPathFreestandingOwnershipClaimedModuleForbiddenTokens
    productPathFreestandingOwnershipClaimedLakefilePath
    productPathFreestandingOwnershipClaimedLakefileTokens
    productPathFreestandingOwnershipClaimedJustPath
    productPathFreestandingOwnershipClaimedJustTokens
    productPathFreestandingOwnershipClaimedAcceptanceTokens
    stepContractFullStageId
    stepContractFullHostId
    stepContractFullSelfHostId
    stepContractFullModulePath
    stepContractFullModuleTokens
    stepContractFullModuleForbiddenTokens
    stepContractFullLakefilePath
    stepContractFullLakefileTokens
    stepContractFullJustPath
    stepContractFullJustTokens
    stepContractFullAcceptanceTokens
    selfHostCompleteStageId
    selfHostCompleteHostId
    selfHostCompleteSelfHostId
    selfHostCompleteModulePath
    selfHostCompleteModuleTokens
    selfHostCompleteModuleForbiddenTokens
    selfHostCompleteLakefilePath
    selfHostCompleteLakefileTokens
    selfHostCompleteJustPath
    selfHostCompleteJustTokens
    selfHostCompleteAcceptanceTokens
    ;

  # Cold eval peels (helpers, file/content, unit walk, emit/out match).
  # HostPin family scanners stay inline below (dual-pin batch race surface).
  evalHelpers = import ./eval-helpers.nix { inherit lib root; };
  inherit (evalHelpers) exists readRel has hasI checkContent;

  evalFileContent = import ./eval-file-content.nix {
    inherit
      lib
      exists
      readRel
      checkContent
      requiredFiles
      contentSpecs
      optionalContentSpecs
      ;
  };
  inherit (evalFileContent) fileViolations contentViolations optionalContentViolations;

  evalUnitWalk = import ./eval-unit-walk.nix {
    inherit
      lib
      root
      readRel
      has
      unitWalkRoot
      unitWalkSkipDirs
      unitWalkExtensions
      unitSurfaceRequiredAny
      unitSurfaceRequiredAll
      unitSurfaceModuleAny
      ;
  };
  inherit (evalUnitWalk)
    hasExt
    walkUnits
    unitPaths
    unitFileViolations
    unitSurfaceCount
    unitCountViolations
    ;

  evalEmitReleaseMatch = import ./eval-emit-release-match.nix {
    inherit
      readRel
      emitH
      emitC
      releaseH
      releaseC
      ;
  };
  inherit (evalEmitReleaseMatch) emitReleaseMatchViolations;


  # HostPin / claim-path scanners (Sub-1-KLOC slices).
  # residualFreeReleasePresent / residualFreeMeasureGreen come from hostpin-1 via fold.
  envBase = {
    inherit lib has hasI exists readRel checkContent;
  } // specs;

  hostpin = lib.foldl' (acc: path: acc // import path (envBase // acc)) {} [
    ./eval-hostpin-1.nix
    ./eval-hostpin-2.nix
    ./eval-hostpin-3.nix
    ./eval-hostpin-4.nix
  ];

  inherit (hostpin)
    productKernelSelfApplyModuleViolations
    productKernelSelfApplyModuleGreen
    productOutKernelEvidenceViolations
    residualFreeMeasureViolations
    residualFreeReleasePresent
    residualFreeMeasureGreen
    productOutKernelEvidenceGreen
    productPathBootstrapViolations
    productPathHostLakeBootstrapGreen
    productWriterSurfaceViolations
    productWriterSurfaceGreen
    productWriterPathPlanViolations
    productWriterPathPlanGreen
    productWriterPathExecutionViolations
    productWriterPathExecutionGreen
    productPathOwnershipInputsViolations
    productPathOwnershipInputsGreen
    productPathPerformViolations
    productPathPerformGreen
    productPathPerformStepViolations
    productPathPerformStepGreen
    productPathPerformReadViolations
    productPathPerformReadGreen
    productPathPerformComposeViolations
    productPathPerformComposeGreen
    productPathPerformWriteHcViolations
    productPathPerformWriteHcGreen
    productPathFreestandingCapableViolations
    productPathFreestandingCapableGreen
    productPathFreestandingCapableStepContractViolations
    productPathFreestandingCapableStepContractGreen
    productPathFreestandingCapableReadViolations
    productPathFreestandingCapableReadGreen
    productPathFreestandingCapableComposeViolations
    productPathFreestandingCapableComposeGreen
    productPathFreestandingCapableWriteHcViolations
    productPathFreestandingCapableWriteHcGreen
    productPathFreestandingCapableRegenerateViolations
    productPathFreestandingCapableRegenerateGreen
    productPathFreestandingCapableInstallOutViolations
    productPathFreestandingCapableInstallOutGreen
    productPathFreestandingCapableFullBarViolations
    productPathFreestandingCapableFullBarGreen
    productPathOwnershipRegenerateViolations
    productPathOwnershipRegenerateGreen
    productPathFreestandingPerformEvidenceViolations
    productPathFreestandingPerformEvidenceGreen
    productPathFreestandingPerformOfficialPathViolations
    productPathFreestandingPerformOfficialPathGreen
    productPathFreestandingPerformOfficialPathAlternateViolations
    productPathFreestandingPerformOfficialPathAlternateGreen
    productPathFreestandingPerformDualEqualityWriteParityViolations
    productPathFreestandingPerformDualEqualityWriteParityGreen
    productPathFreestandingPerformDualEqualityWriteClosePathViolations
    productPathFreestandingPerformDualEqualityWriteClosePathGreen
    productPathFreestandingPerformDualEqualityWriteApiViolations
    productPathFreestandingPerformDualEqualityWriteApiGreen
    productPathFreestandingPerformDualEqualityWriteCapableGapViolations
    productPathFreestandingPerformDualEqualityWriteCapableGapGreen
    productPathOfficialPathRetireOfficialViolations
    productPathOfficialPathRetireOfficialGreen
    productPathFreestandingPerformClaimedViolations
    productPathFreestandingPerformClaimedGreen
    productPathFreestandingOwnershipClaimedViolations
    productPathFreestandingOwnershipClaimedGreen
    stepContractFullViolations
    stepContractFullGreen
    selfHostCompleteViolations
    selfHostCompleteGreen
    ;


  join = import ./eval-join.nix (
    {
      inherit
        lib
        has
        readRel
        residualFreeReleasePresent
        residualFreeMeasureGreen
        residualFreeMeasureStageId
        residualFreeMeasureHostId
        residualFreeMeasureSelfHostId
        fileViolations
        contentViolations
        optionalContentViolations
        unitFileViolations
        unitCountViolations
        emitReleaseMatchViolations
        unitPaths
        unitSurfaceCount
        requiredFiles
        optionalFiles
        ;
    }
    // hostpin
    // specs
  );

in import ./eval-result.nix (
  {
    inherit
      residualFreeMeasureGreen
      residualFreeReleasePresent
      unitPaths
      unitSurfaceCount
      requiredFiles
      optionalFiles
      ;
  }
  // hostpin
  // specs
  // join
)
