# SPDX-License-Identifier: Unlicense
# Data slice for systems-emit-wire emit product. Joined by emit-product.nix.
# No bash, no Python in eval.
rec {
  unitTranslationApis = [
    "slake_mult_is_valid"
    "slake_linear_consume"
    "slake_erasure_is_runtime_absent"
    "slake_check_fail_closed"
    "slake_extract_with_checks"
    "slake_typed_ir_id"
    "slake_ir_node_init"
    "slake_ir_node_is_well_typed"
    "slake_ir_node_check_fail_closed"
    "slake_ir_program_id"
    "slake_ir_program_init"
    "slake_ir_program_push"
    "slake_ir_program_is_well_typed"
    "slake_ir_program_check_fail_closed"
    "slake_ir_graph_id"
    "slake_ir_graph_init"
    "slake_ir_graph_push_node"
    "slake_ir_graph_add_edge"
    "slake_ir_graph_is_well_typed"
    "slake_ir_graph_check_fail_closed"
    "slake_host_compose_id"
    "slake_host_compose_init"
    "slake_host_compose_reset"
    "slake_host_compose_push_node"
    "slake_host_compose_add_edge"
    "slake_host_compose_mint"
    "slake_host_compose_consume"
    "slake_host_compose_mark_erased"
    "slake_host_compose_is_well_typed"
    "slake_host_compose_check_fail_closed"
    "slake_host_compose_extract"
    "slake_emit_plan_id"
    "slake_emit_plan_from_compose"
    "slake_emit_plan_is_ready"
    "slake_emit_apply_id"
    "slake_emit_apply_from_compose"
    "slake_emit_apply_is_valid"
    "slake_emit_body_id"
    "slake_emit_body_from_compose"
    "slake_emit_body_is_valid"
  ];

  emitProductAll = [
    "SLAKE_EMIT_FREESTANDING_C_V0"
    "UNIT_DEEPEN_V1"
    "UNIT_TRANSLATION_V0"
    "MULT-0"
    "MULT-1"
    "MULT-OMEGA"
    "RUNTIME-FS"
    "product residual free"
    "FAIL_CLOSED_CHECKER_V1"
    "CONSUME_TOKEN_HOST_V0"
    "JOIN-ALG"
    "ConsumeToken"
    "LINEAR-EXACT-ONCE"
    "TYPED_IR_V0"
    "IR_PROGRAM_V0"
    "IR_GRAPH_EDGES_V0"
    "HOST_COMPOSE_V0"
    "EMIT_PLAN_V0"
    "EMIT_APPLY_V0"
    "EMIT_BODY_V0"
    "HOST-EMIT-SSOT"
    "HOST-EMIT-BODY"
    "HOST-EMIT-BANNER"
    "HOST-EMIT-MULT"
    "HOST-EMIT-LINEAR"
    "HOST-EMIT-ERASURE"
    "HOST-EMIT-EXTRACT"
    "HOST-EMIT-TYPES"
    "HOST-EMIT-PROGRAM"
    "HOST-EMIT-GRAPH"
    "HOST-EMIT-COMPOSE"
    "HOST-EMIT-PLAN"
    "HOST-EMIT-APPLY"
    "SLAKE_IR_KIND_VALUE"
    "SLAKE_IR_KIND_LINEAR"
    "SLAKE_IR_KIND_ERASED"
    "slake_ir_node"
    "SLAKE_IR_PROGRAM_CAP"
    "slake_ir_program"
    "SLAKE_IR_EDGE_MAX"
    "slake_ir_graph"
    "slake_ir_edge"
    "slake_host_compose"
    "EMIT-BOUNDARY"
    "slake_emit_plan"
    "slake_emit_apply"
    "SLAKE_EMIT_APPLY_CAP"
    "slake_emit_body"
    "SLAKE_EMIT_BODY_CAP"
    "slake_check_bundle"
    "slake_consume_token_mint"
    "slake_consume_token_consume"
    "slake_consume_token_check_fail_closed"
    "slake_consume_token_host_id"
    "slake_consume_token_init"
    "slake_consume_token_is_live"
    "slake_emit_version"
    "slake_type_tag_init"
    "slake_mult_is_known"
    "slake_mult_name"
    "slake_linear_token_consume"
    "slake_erased_mark"
    "slake_extract_product_runtime"
    "slake_type_tag_get"
    "slake_unit_translation_id"
  ]
  ++ unitTranslationApis;

  emitProductNone = [
    "SLAKE_IR_PROGRAM_MAX"
    "SLAKE_IR_EDGE_CAP"
  ];

  releaseAll = emitProductAll;
  releaseNone = emitProductNone;
}
