# SPDX-License-Identifier: Unlicense
# Join only: import data slices for systems-emit-wire (one flake check / just recipe).
# Edit job-specific files when honesty tokens change:
#   emit-product.nix         -- drivers, emit product APIs/stages, optional release
#   unit-deepen.nix          -- UNIT_DEEPEN_V1 units + companions
#   unit-walk.nix            -- dynamic SKELETON|UNIT_SURFACE walk
#   residual-free-measure.nix -- claim A product residual free measure (release)
# Imported by ./default.nix. No bash, no competing gate module names.
let
  emit = import ./emit-product.nix;
  deepen = import ./unit-deepen.nix;
  walk = import ./unit-walk.nix;
  residualFree = import ./residual-free-measure.nix;
in
{
  inherit (emit)
    emitH
    emitC
    releaseH
    releaseC
    behavioralProbe
    unitTranslationApis
    optionalFiles
    optionalContentSpecs
    productOutBbarOwnership
    productOutBbarApis
    productKernelSelfApplyStageId
    productKernelSelfApplyHostId
    productKernelSelfApplySelfHostId
    productKernelSelfApplyModulePath
    productKernelSelfApplyModuleTokens
    productKernelSelfApplyModuleForbiddenTokens
    productOutKernelStageId
    productOutKernelHostId
    productOutKernelSelfHostId
    productOutKernelModulePath
    productOutKernelModuleTokens
    productOutKernelModuleForbiddenTokens
    productPathBootstrapStageId
    productPathBootstrapHostId
    productPathBootstrapSelfHostId
    productPathBootstrapWriterPath
    freestandingEmitLoadPath
    freestandingEmitLoadScaffoldPath
    productPathBootstrapWriterTokens
    productPathBootstrapWriterLoadTokens
    productPathBootstrapAcceptanceTokens
    productPathBootstrapModulePath
    productPathBootstrapModuleTokens
    productPathBootstrapModuleForbiddenTokens
    productWriterSurfaceStageId
    productWriterSurfaceHostId
    productWriterSurfaceSelfHostId
    productWriterSurfaceOwnership
    productWriterSurfaceApis
    productWriterSurfaceAcceptanceTokens
    productWriterSurfaceModulePath
    productWriterSurfaceModuleTokens
    productWriterSurfaceModuleForbiddenTokens
    productWriterPathPlanStageId
    productWriterPathPlanHostId
    productWriterPathPlanSelfHostId
    productWriterPathPlanStepTokens
    productWriterPathPlanAcceptanceTokens
    productWriterPathPlanModulePath
    productWriterPathPlanModuleTokens
    productWriterPathPlanModuleForbiddenTokens
    productWriterPathExecutionStageId
    productWriterPathExecutionHostId
    productWriterPathExecutionSelfHostId
    productWriterPathExecutionWriterTokens
    productWriterPathExecutionLoadTokens
    productWriterPathExecutionLoadScaffoldTokens
    productWriterPathExecutionInstallPath
    productWriterPathExecutionInstallTokens
    productWriterPathExecutionAcceptanceTokens
    productWriterPathExecModulePath
    productWriterPathExecModuleTokens
    productWriterPathExecModuleForbiddenTokens
    productPathOwnershipStageId
    productPathOwnershipHostId
    productPathOwnershipSelfHostId
    productPathOwnershipSsotPaths
    productPathOwnershipEmitPaths
    productPathOwnershipAcceptanceTokens
    productPathOwnershipInputsModulePath
    productPathOwnershipInputsModuleTokens
    productPathOwnershipInputsModuleForbiddenTokens
    productPathPerformStageId
    productPathPerformHostId
    productPathPerformSelfHostId
    productPathPerformLakeWriterPath
    productPathPerformLakeWriterTokens
    productPathPerformLakeLoadTokens
    productPathPerformLakeLoadPath
    productPathPerformInstallPath
    productPathPerformInstallTokens
    productPathPerformAcceptanceTokens
    productPathPerformModulePath
    productPathPerformModuleTokens
    productPathPerformModuleForbiddenTokens
    productPathPerformStepStageId
    productPathPerformStepHostId
    productPathPerformStepSelfHostId
    productPathPerformStepInstallPath
    productPathPerformStepInstallTokens
    productPathPerformStepInstallForbiddenCmdPrefixes
    productPathPerformStepAcceptanceTokens
    productPathPerformStepModulePath
    productPathPerformStepModuleTokens
    productPathPerformStepModuleForbiddenTokens
    productPathPerformReadStageId
    productPathPerformReadHostId
    productPathPerformReadSelfHostId
    productPathPerformReadModulePath
    productPathPerformReadModuleTokens
    productPathPerformReadModuleForbiddenTokens
    productPathPerformReadLakefilePath
    productPathPerformReadLakefileTokens
    productPathPerformReadJustPath
    productPathPerformReadJustTokens
    productPathPerformReadAcceptanceTokens
    productPathPerformComposeStageId
    productPathPerformComposeHostId
    productPathPerformComposeSelfHostId
    productPathPerformComposeModulePath
    productPathPerformComposeModuleTokens
    productPathPerformComposeModuleForbiddenTokens
    productPathPerformComposeLakefilePath
    productPathPerformComposeLakefileTokens
    productPathPerformComposeJustPath
    productPathPerformComposeJustTokens
    productPathPerformComposeAcceptanceTokens
    productPathPerformWriteHcStageId
    productPathPerformWriteHcHostId
    productPathPerformWriteHcSelfHostId
    productPathPerformWriteHcModulePath
    productPathPerformWriteHcModuleTokens
    productPathPerformWriteHcModuleForbiddenTokens
    productPathPerformWriteHcLakefilePath
    productPathPerformWriteHcLakefileTokens
    productPathPerformWriteHcJustPath
    productPathPerformWriteHcJustTokens
    productPathPerformWriteHcAcceptanceTokens
    productPathFreestandingCapableStageId
    productPathFreestandingCapableHostId
    productPathFreestandingCapableSelfHostId
    productPathFreestandingCapableModulePath
    productPathFreestandingCapableModuleTokens
    productPathFreestandingCapableModuleForbiddenTokens
    productPathFreestandingCapableLakefilePath
    productPathFreestandingCapableLakefileTokens
    productPathFreestandingCapableJustPath
    productPathFreestandingCapableJustTokens
    productPathFreestandingCapableAcceptanceTokens
    productPathFreestandingCapableStepContractStageId
    productPathFreestandingCapableStepContractHostId
    productPathFreestandingCapableStepContractSelfHostId
    productPathFreestandingCapableStepContractModulePath
    productPathFreestandingCapableStepContractModuleTokens
    productPathFreestandingCapableStepContractModuleForbiddenTokens
    productPathFreestandingCapableStepContractLakefilePath
    productPathFreestandingCapableStepContractLakefileTokens
    productPathFreestandingCapableStepContractJustPath
    productPathFreestandingCapableStepContractJustTokens
    productPathFreestandingCapableStepContractAcceptanceTokens
    productPathFreestandingCapableReadStageId
    productPathFreestandingCapableReadHostId
    productPathFreestandingCapableReadSelfHostId
    productPathFreestandingCapableReadModulePath
    productPathFreestandingCapableReadModuleTokens
    productPathFreestandingCapableReadModuleForbiddenTokens
    productPathFreestandingCapableReadLakefilePath
    productPathFreestandingCapableReadLakefileTokens
    productPathFreestandingCapableReadJustPath
    productPathFreestandingCapableReadJustTokens
    productPathFreestandingCapableReadAcceptanceTokens
    productPathFreestandingCapableComposeStageId
    productPathFreestandingCapableComposeHostId
    productPathFreestandingCapableComposeSelfHostId
    productPathFreestandingCapableComposeModulePath
    productPathFreestandingCapableComposeModuleTokens
    productPathFreestandingCapableComposeModuleForbiddenTokens
    productPathFreestandingCapableComposeLakefilePath
    productPathFreestandingCapableComposeLakefileTokens
    productPathFreestandingCapableComposeJustPath
    productPathFreestandingCapableComposeJustTokens
    productPathFreestandingCapableComposeAcceptanceTokens
    productPathFreestandingCapableWriteHcStageId
    productPathFreestandingCapableWriteHcHostId
    productPathFreestandingCapableWriteHcSelfHostId
    productPathFreestandingCapableWriteHcModulePath
    productPathFreestandingCapableWriteHcLoadPath
    productPathFreestandingCapableWriteHcModuleTokens
    productPathFreestandingCapableWriteHcLoadTokens
    productPathFreestandingCapableWriteHcModuleForbiddenTokens
    productPathFreestandingCapableWriteHcLakefilePath
    productPathFreestandingCapableWriteHcLakefileTokens
    productPathFreestandingCapableWriteHcJustPath
    productPathFreestandingCapableWriteHcJustTokens
    productPathFreestandingCapableWriteHcAcceptanceTokens
    productPathFreestandingCapableRegenerateStageId
    productPathFreestandingCapableRegenerateHostId
    productPathFreestandingCapableRegenerateSelfHostId
    productPathFreestandingCapableRegenerateModulePath
    productPathFreestandingCapableRegenerateModuleTokens
    productPathFreestandingCapableRegenerateModuleForbiddenTokens
    productPathFreestandingCapableRegenerateLakefilePath
    productPathFreestandingCapableRegenerateLakefileTokens
    productPathFreestandingCapableRegenerateJustPath
    productPathFreestandingCapableRegenerateJustTokens
    productPathFreestandingCapableRegenerateAcceptanceTokens
    productPathFreestandingCapableInstallOutStageId
    productPathFreestandingCapableInstallOutHostId
    productPathFreestandingCapableInstallOutSelfHostId
    productPathFreestandingCapableInstallOutModulePath
    productPathFreestandingCapableInstallOutModuleTokens
    productPathFreestandingCapableInstallOutModuleForbiddenTokens
    productPathFreestandingCapableInstallOutLakefilePath
    productPathFreestandingCapableInstallOutLakefileTokens
    productPathFreestandingCapableInstallOutJustPath
    productPathFreestandingCapableInstallOutJustTokens
    productPathFreestandingCapableInstallOutAcceptanceTokens
    productPathFreestandingCapableFullBarStageId
    productPathFreestandingCapableFullBarHostId
    productPathFreestandingCapableFullBarSelfHostId
    productPathFreestandingCapableFullBarModulePath
    productPathFreestandingCapableFullBarModuleTokens
    productPathFreestandingCapableFullBarModuleForbiddenTokens
    productPathFreestandingCapableFullBarLakefilePath
    productPathFreestandingCapableFullBarLakefileTokens
    productPathFreestandingCapableFullBarJustPath
    productPathFreestandingCapableFullBarJustTokens
    productPathFreestandingCapableFullBarAcceptanceTokens
    productPathOwnershipRegenerateStageId
    productPathOwnershipRegenerateHostId
    productPathOwnershipRegenerateSelfHostId
    productPathOwnershipRegenerateModulePath
    productPathOwnershipRegenerateModuleTokens
    productPathOwnershipRegenerateModuleForbiddenTokens
    productPathOwnershipRegenerateLakefilePath
    productPathOwnershipRegenerateLakefileTokens
    productPathOwnershipRegenerateJustPath
    productPathOwnershipRegenerateJustTokens
    productPathOwnershipRegenerateAcceptanceTokens
    productPathFreestandingPerformEvidenceStageId
    productPathFreestandingPerformEvidenceHostId
    productPathFreestandingPerformEvidenceSelfHostId
    productPathFreestandingPerformEvidenceModulePath
    productPathFreestandingPerformEvidenceModuleTokens
    productPathFreestandingPerformEvidenceModuleForbiddenTokens
    productPathFreestandingPerformEvidenceLakefilePath
    productPathFreestandingPerformEvidenceLakefileTokens
    productPathFreestandingPerformEvidenceJustPath
    productPathFreestandingPerformEvidenceJustTokens
    productPathFreestandingPerformEvidenceAcceptanceTokens
    productPathFreestandingPerformOfficialPathStageId
    productPathFreestandingPerformOfficialPathHostId
    productPathFreestandingPerformOfficialPathSelfHostId
    productPathFreestandingPerformOfficialPathModulePath
    productPathFreestandingPerformOfficialPathModuleTokens
    productPathFreestandingPerformOfficialPathModuleForbiddenTokens
    productPathFreestandingPerformOfficialPathLakefilePath
    productPathFreestandingPerformOfficialPathLakefileTokens
    productPathFreestandingPerformOfficialPathJustPath
    productPathFreestandingPerformOfficialPathJustTokens
    productPathFreestandingPerformOfficialPathAcceptanceTokens
    productPathFreestandingPerformOfficialPathAlternateStageId
    productPathFreestandingPerformOfficialPathAlternateHostId
    productPathFreestandingPerformOfficialPathAlternateSelfHostId
    productPathFreestandingPerformOfficialPathAlternateModulePath
    productPathFreestandingPerformOfficialPathAlternateModuleTokens
    productPathFreestandingPerformOfficialPathAlternateModuleForbiddenTokens
    productPathFreestandingPerformOfficialPathAlternateLakefilePath
    productPathFreestandingPerformOfficialPathAlternateLakefileTokens
    productPathFreestandingPerformOfficialPathAlternateJustPath
    productPathFreestandingPerformOfficialPathAlternateJustTokens
    productPathFreestandingPerformOfficialPathAlternateAcceptanceTokens
    productPathFreestandingPerformDualEqualityWriteParityStageId
    productPathFreestandingPerformDualEqualityWriteParityHostId
    productPathFreestandingPerformDualEqualityWriteParitySelfHostId
    productPathFreestandingPerformDualEqualityWriteParityModulePath
    productPathFreestandingPerformDualEqualityWriteParityModuleTokens
    productPathFreestandingPerformDualEqualityWriteParityModuleForbiddenTokens
    productPathFreestandingPerformDualEqualityWriteParityLakefilePath
    productPathFreestandingPerformDualEqualityWriteParityLakefileTokens
    productPathFreestandingPerformDualEqualityWriteParityJustPath
    productPathFreestandingPerformDualEqualityWriteParityJustTokens
    productPathFreestandingPerformDualEqualityWriteParityAcceptanceTokens
    productPathFreestandingPerformDualEqualityWriteClosePathStageId
    productPathFreestandingPerformDualEqualityWriteClosePathHostId
    productPathFreestandingPerformDualEqualityWriteClosePathSelfHostId
    productPathFreestandingPerformDualEqualityWriteClosePathModulePath
    productPathFreestandingPerformDualEqualityWriteClosePathModuleTokens
    productPathFreestandingPerformDualEqualityWriteClosePathModuleForbiddenTokens
    productPathFreestandingPerformDualEqualityWriteClosePathLakefilePath
    productPathFreestandingPerformDualEqualityWriteClosePathLakefileTokens
    productPathFreestandingPerformDualEqualityWriteClosePathJustPath
    productPathFreestandingPerformDualEqualityWriteClosePathJustTokens
    productPathFreestandingPerformDualEqualityWriteClosePathAcceptanceTokens
    productPathFreestandingPerformDualEqualityWriteApiStageId
    productPathFreestandingPerformDualEqualityWriteApiHostId
    productPathFreestandingPerformDualEqualityWriteApiSelfHostId
    productPathFreestandingPerformDualEqualityWriteApiModulePath
    productPathFreestandingPerformDualEqualityWriteApiLoadPath
    productPathFreestandingPerformDualEqualityWriteApiModuleTokens
    productPathFreestandingPerformDualEqualityWriteApiLoadTokens
    productPathFreestandingPerformDualEqualityWriteApiModuleForbiddenTokens
    productPathFreestandingPerformDualEqualityWriteApiLakefilePath
    productPathFreestandingPerformDualEqualityWriteApiLakefileTokens
    productPathFreestandingPerformDualEqualityWriteApiJustPath
    productPathFreestandingPerformDualEqualityWriteApiJustTokens
    productPathFreestandingPerformDualEqualityWriteApiAcceptanceTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapStageId
    productPathFreestandingPerformDualEqualityWriteCapableGapHostId
    productPathFreestandingPerformDualEqualityWriteCapableGapSelfHostId
    productPathFreestandingPerformDualEqualityWriteCapableGapModulePath
    productPathFreestandingPerformDualEqualityWriteCapableGapModuleTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapModuleForbiddenTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapLakefilePath
    productPathFreestandingPerformDualEqualityWriteCapableGapLakefileTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapJustPath
    productPathFreestandingPerformDualEqualityWriteCapableGapJustTokens
    productPathFreestandingPerformDualEqualityWriteCapableGapAcceptanceTokens
    productPathOfficialPathRetireOfficialStageId
    productPathOfficialPathRetireOfficialHostId
    productPathOfficialPathRetireOfficialSelfHostId
    productPathOfficialPathRetireOfficialModulePath
    productPathOfficialPathRetireOfficialModuleTokens
    productPathOfficialPathRetireOfficialModuleForbiddenTokens
    productPathOfficialPathRetireOfficialLakefilePath
    productPathOfficialPathRetireOfficialLakefileTokens
    productPathOfficialPathRetireOfficialJustPath
    productPathOfficialPathRetireOfficialJustTokens
    productPathOfficialPathRetireOfficialAcceptanceTokens
    productPathFreestandingPerformClaimedStageId
    productPathFreestandingPerformClaimedHostId
    productPathFreestandingPerformClaimedSelfHostId
    productPathFreestandingPerformClaimedModulePath
    productPathFreestandingPerformClaimedModuleTokens
    productPathFreestandingPerformClaimedModuleForbiddenTokens
    productPathFreestandingPerformClaimedLakefilePath
    productPathFreestandingPerformClaimedLakefileTokens
    productPathFreestandingPerformClaimedJustPath
    productPathFreestandingPerformClaimedJustTokens
    productPathFreestandingPerformClaimedAcceptanceTokens
    productPathFreestandingOwnershipClaimedStageId
    productPathFreestandingOwnershipClaimedHostId
    productPathFreestandingOwnershipClaimedSelfHostId
    productPathFreestandingOwnershipClaimedModulePath
    productPathFreestandingOwnershipClaimedModuleTokens
    productPathFreestandingOwnershipClaimedModuleForbiddenTokens
    productPathFreestandingOwnershipClaimedLakefilePath
    productPathFreestandingOwnershipClaimedLakefileTokens
    productPathFreestandingOwnershipClaimedJustPath
    productPathFreestandingOwnershipClaimedJustTokens
    productPathFreestandingOwnershipClaimedAcceptanceTokens
    stepContractFullStageId
    stepContractFullHostId
    stepContractFullSelfHostId
    stepContractFullModulePath
    stepContractFullModuleTokens
    stepContractFullModuleForbiddenTokens
    stepContractFullLakefilePath
    stepContractFullLakefileTokens
    stepContractFullJustPath
    stepContractFullJustTokens
    stepContractFullAcceptanceTokens
    selfHostCompleteStageId
    selfHostCompleteHostId
    selfHostCompleteSelfHostId
    selfHostCompleteModulePath
    selfHostCompleteModuleTokens
    selfHostCompleteModuleForbiddenTokens
    selfHostCompleteLakefilePath
    selfHostCompleteLakefileTokens
    selfHostCompleteJustPath
    selfHostCompleteJustTokens
    selfHostCompleteAcceptanceTokens
    ;

  inherit (walk)
    unitWalkRoot
    unitWalkSkipDirs
    unitWalkExtensions
    unitSurfaceRequiredAny
    unitSurfaceNotEmitAny
    unitSurfaceModuleAny
    ;

  inherit (residualFree)
    residualFreeMeasureStageId
    residualFreeMeasureHostId
    residualFreeMeasureSelfHostId
    forbiddenManagedResidual
    requiredFreestandingHonesty
    ;

  requiredFiles = emit.requiredDriverAndEmit ++ deepen.requiredDeepenFiles;

  contentSpecs = emit.contentSpecs ++ deepen.contentSpecs;
}
