/-
  SYSTEMS_LEAN_HOST partial -- dual-pin live OccupancyWalk.lean bytes.
  liveOccupancyWalkSourcePart02. Not a compile of OccupancyProbe.
  Greppable: liveOccupancyWalkSourcePart02, PARSE-LIVE-OCCUPANCY-WALK.
  Module: SystemsLean.HostFrontLiveOccupancyWalkPart02
  Not FullHost. Occupancy stays 49. Mill stays 69 of 69.
  Module must stay ASCII.
-/

namespace SystemsLean.HostFrontLiveOccupancyWalk

/-- Dual-pinned live OccupancyWalk.lean bytes, liveOccupancyWalkSourcePart02. -/
def liveOccupancyWalkSourcePart02 : String := r#"    List String :=
  ["SystemsLean.Mult",
   "SystemsLean.MultTheorems",
   "SystemsLean.Types",
   "SystemsLean.TypesTheorems",
   "SystemsLean.Erasure",
   "SystemsLean.ErasureTheorems",
   "SystemsLean.Extract",
   "SystemsLean.ExtractTheorems",
   "SystemsLean.IrProgram",
   "SystemsLean.IrProgramTheorems",
   "SystemsLean.HostTerm",
   "SystemsLean.HostFrontGoldens",
   "SystemsLean.HostFront",
   "SystemsLean.HostFrontTheorems",
   "SystemsLean.HostCheck",
   "SystemsLean.HostGraph",
   "SystemsLean.HostGraphTheorems",
   "SystemsLean.IrGraph",
   "SystemsLean.HostCompose",
   "SystemsLean.CompilePath",
   "SystemsLean.EmitMultScaffold",
   "SystemsLean.EmitLinearScaffold",
   "SystemsLean.EmitTypesScaffold",
   "SystemsLean.EmitProgramScaffold",
   "SystemsLean.EmitGraphScaffold",
   "SystemsLean.EmitComposeScaffold",
   "SystemsLean.EmitMult",
   "SystemsLean.EmitLinear",
   "SystemsLean.EmitTypes",
   "SystemsLean.EmitProgram",
   "SystemsLean.EmitGraph",
   "SystemsLean.EmitCompose",
   "SystemsLean.CompilePathMult",
   "SystemsLean.CompilePathLinear",
   "SystemsLean.CompilePathTypes",
   "SystemsLean.CompilePathProgram",
   "SystemsLean.CompilePathGraph",
   "SystemsLean.CompilePathCompose",
   "SystemsLean.FirstSurface",
   "SystemsLean.MultSubsetEmit",
   "SystemsLean.LinearSubsetEmit",
   "SystemsLean.TypesSubsetEmit",
   "SystemsLean.ProgramSubsetEmit",
   "SystemsLean.GraphSubsetEmit",
   "SystemsLean.ComposeSubsetEmit",
   "SystemsLean.HostPackageWrite",
   "SystemsLean.HostPackageWriteTheorems",
   "SystemsLean.HostPackageRoots",
   "SystemsLean.HostImportGraphSeeds",
   "SystemsLean.HostImportGraphModel",
   "SystemsLean.HostImportGraphMods",
   "SystemsLean.HostImportGraphModsLater",
   "SystemsLean.HostImportGraphLoadOkLater",
   "SystemsLean.HostImportGraphWalkLater",
   "SystemsLean.HostImportGraphWalk",
   "SystemsLean.HostModuleCheckRequiredDecls",
   "SystemsLean.HostModuleCheckRequiredDeclsProduct",
   "SystemsLean.HostModuleCheckRequiredDeclsLater",
   "SystemsLean.HostModuleCheckFixtureTexts",
   "SystemsLean.HostModuleCheckFixtureTextsProduct",
   "SystemsLean.HostModuleCheckFixtureTextsLater",
   "SystemsLean.HostModuleCheckFixtureTextsSelfHost",
   "SystemsLean.HostModuleCheckFixtureTextsEmit",
   "SystemsLean.HostModuleCheckFixtures",
   "SystemsLean.HostModuleCheckSurface",
   "SystemsLean.HostModuleCheckMultTerm",
   "SystemsLean.HostModuleCheckMultProof",
   "SystemsLean.HostModuleCheckLinearProof",
   "SystemsLean.HostModuleCheckTypesProof",
   "SystemsLean.HostModuleCheckKernelMultProof",
   "SystemsLean.HostModuleCheckKernelLinearProof",
   "SystemsLean.HostModuleCheckKernelTypesProof",
   "SystemsLean.HostModuleCheckKernelProgramProof",
   "SystemsLean.HostModuleCheckKernelEmitProof",
   "SystemsLean.HostModuleCheckLinearTerm",
   "SystemsLean.HostModuleCheckTypesTerm",
   "SystemsLean.HostModuleCheckIrProgramTerm",
   "SystemsLean.HostModuleCheckIrGraphTerm",
   "SystemsLean.HostModuleCheckHostComposeTerm",
   "SystemsLean.HostModuleCheckErasureTerm",
   "SystemsLean.HostModuleCheckExtractTerm",
   "SystemsLean.HostModuleCheckEmitPlanTerm",
   "SystemsLean.HostModuleCheckEmitMultScaffoldTerm",
   "SystemsLean.HostModuleCheckEmitLinearScaffoldTerm",
   "SystemsLean.HostModuleCheckEmitTypesScaffoldTerm",
   "SystemsLean.HostModuleCheckEmitProgramScaffoldTerm",
   "SystemsLean.HostModuleCheckEmitGraphScaffoldTerm",
   "SystemsLean.HostModuleCheckEmitComposeScaffoldTerm",
   "SystemsLean.HostModuleCheckEmitErasureScaffoldTerm",
   "SystemsLean.HostModuleCheckEmitExtractScaffoldTerm",
   "SystemsLean.HostModuleCheckEmitApplyTerm",
   "SystemsLean.HostModuleCheckParityEmitTerm",
   "SystemsLean.HostModuleCheckEmitBannerScaffoldTerm",
   "SystemsLean.HostModuleCheckKernelSelfApplyTerm",
   "SystemsLean.HostModuleCheckProductOutKernelTerm",
   "SystemsLean.HostModuleCheckCompilePathTerm",
   "SystemsLean.HostModuleCheckJoinMapTerm",
   "SystemsLean.HostModuleCheckSelfHostTerm",
   "SystemsLean.HostModuleCheckSurfaceMatrixTerm",
   "SystemsLean.HostModuleCheckSpecProofTerm",
   "SystemsLean.HostModuleCheckDualResidualTerm",
   "SystemsLean.HostModuleCheckCompilePathMultTerm",
   "SystemsLean.HostModuleCheckCompilePathLinearTerm",
   "SystemsLean.HostModuleCheckCompilePathTypesTerm",
   "SystemsLean.HostModuleCheckCompilePathProgramTerm",
   "SystemsLean.HostModuleCheckCompilePathGraphTerm",
   "SystemsLean.HostModuleCheckCompilePathComposeTerm",
   "SystemsLean.HostModuleCheckCompilePathErasureTerm",
   "SystemsLean.HostModuleCheckCompilePathExtractTerm",
   "SystemsLean.HostModuleCheckCompilePathPlanTerm",
   "SystemsLean.HostModuleCheckCompilePathApplyTerm",
   "SystemsLean.HostModuleCheckCompilePathBodyTerm",
   "SystemsLean.HostModuleCheckFirstSurfaceTerm",
   "SystemsLean.HostModuleCheckLinearSubsetEmitTerm",
   "SystemsLean.HostModuleCheckTypesSubsetEmitTerm",
   "SystemsLean.HostModuleCheckProgramSubsetEmitTerm",
   "SystemsLean.HostModuleCheckGraphSubsetEmitTerm",
   "SystemsLean.HostModuleCheckComposeSubsetEmitTerm",
   "SystemsLean.HostModuleCheckErasureSubsetEmitTerm",
   "SystemsLean.HostModuleCheckExtractSubsetEmitTerm",
   "SystemsLean.HostModuleCheckMultSubsetEmitTerm",
   "SystemsLean.HostModuleCheckMultSubsetRebuildTerm",
   "SystemsLean.HostModuleCheckLinearSubsetRebuildTerm",
   "SystemsLean.HostModuleCheckTypesSubsetRebuildTerm",
   "SystemsLean.HostModuleCheckProgramSubsetRebuildTerm",
   "SystemsLean.HostModuleCheckGraphSubsetRebuildTerm",
   "SystemsLean.HostModuleCheckComposeSubsetRebuildTerm",
   "SystemsLean.HostModuleCheckErasureSubsetRebuildTerm",
   "SystemsLean.HostModuleCheckExtractSubsetRebuildTerm",
   "SystemsLean.HostModuleCheckHostFrontTerm",
   "SystemsLean.HostModuleCheckLlvmMultTextTerm",
   "SystemsLean.HostModuleCheckHostCheckTerm",
   "SystemsLean.HostModuleCheckHostGraphTerm",
   "SystemsLean.HostModuleCheckLlvmLinearTextTerm",
   "SystemsLean.HostModuleCheckMultFsWriteToolTerm",
   "SystemsLean.HostModuleCheckFrontMultPackageTerm",
   "SystemsLean.HostModuleCheckSubsetPackageJoinTerm",
   "SystemsLean.HostModuleCheckLlvmTypesTextTerm",
   "SystemsLean.HostModuleCheckMultFsDeepenTerm",
   "SystemsLean.HostModuleCheckHostPackageWriteTerm",
   "SystemsLean.HostModuleCheckLlvmProgramTextTerm",
   "SystemsLean.HostModuleCheckLlvmGraphTextTerm",
   "SystemsLean.HostModuleCheckLlvmComposeTextTerm",
   "SystemsLean.HostModuleCheckSelfApplyFsTerm",
   "SystemsLean.HostModuleCheckInventoryCloseTerm",
   "SystemsLean.HostModuleCheckProductPathBarsTerm",
   "SystemsLean.HostModuleCheckProductPathTerm",
   "SystemsLean.HostModuleCheckProbeWireTerm",
   "SystemsLean.HostModuleCheckSelfHostBodyTerm",
   "SystemsLean.HostModuleCheckLoadOkCompilePathUnits",
   "SystemsLean.HostModuleCheckCheckers",
   "SystemsLean.HostModuleCheckCheckersLater",
   "SystemsLean.HostModuleCheckEmitBodyTerm",
   "SystemsLean.HostModuleCheckKernelMultTerm",
   "SystemsLean.HostModuleCheckKernelLinearTerm",
   "SystemsLean.HostModuleCheckKernelTypesTerm",
   "SystemsLean.HostModuleCheckKernelProgramTerm",
   "SystemsLean.HostModuleCheckKernelEmitTerm",
   "SystemsLean.HostModuleCheckParityMultTerm",
   "SystemsLean.HostModuleCheckParityLinearTerm",
   "SystemsLean.HostModuleCheckParityTypesTerm",
   "SystemsLean.HostModuleCheckParityProgramTerm",
   "SystemsLean.HostModuleCheckLoadOkLaterTerm",
   "SystemsLean.HostModuleCheckAcceptsGoodsTerm"]

/-- True when the barrel lists each smaller Program isolation member.
    Wrapper over barrelListsNamedMembers.
    Greppable: barrelListsNamedHostModuleCheckParityProgramTermSmallSubset. -/
def barrelListsNamedHostModuleCheckParityProgramTermSmallSubset
    (text : String) : Bool :=
  barrelListsNamedMembers text
    namedClosedHostModuleCheckParityProgramTermSmallSubsetNames

/-- Compile the smaller Program isolation after reading the live
    lakefile. Wrapper over tryCompileNamedMemberListIO.
    Greppable: tryCompileNamedHostModuleCheckParityProgramTermSmallSubset.
    tryCompileOnDiskModule. SystemsLean.HostModuleCheckParityProgramTerm. -/
unsafe def tryCompileNamedHostModuleCheckParityProgramTermSmallSubsetIO
    (srcPath oleanDir : System.FilePath) : IO Bool := do
  tryCompileNamedMemberListIO srcPath oleanDir
    namedClosedHostModuleCheckParityProgramTermSmallSubsetNames
    namedClosedHostModuleCheckParityProgramTermSmallCompileOrder

@[implemented_by tryCompileNamedHostModuleCheckParityProgramTermSmallSubsetIO]
opaque tryCompileNamedHostModuleCheckParityProgramTermSmallSubsetIOSafe
    (srcPath oleanDir : System.FilePath) : IO Bool

/-- CommandElab wrapper: compile the smaller Program isolation.
    Greppable: tryCompileNamedHostModuleCheckParityProgramTermSmallSubset. -/
def tryCompileNamedHostModuleCheckParityProgramTermSmallSubset
    (srcPath oleanDir : System.FilePath) : CommandElabM Bool := do
  try
    liftIO
      (tryCompileNamedHostModuleCheckParityProgramTermSmallSubsetIOSafe
        srcPath oleanDir)
  catch _ =>
    pure false

/-- Compile the smaller Program import closure, then compile srcPath as
    thmMod. Do not plant on the live tree. Wrapper over
    tryCompileAfterNamedDepsIO.
    Greppable: tryCompileAfterHostModuleCheckParityProgramTermSmallDeps.
    tryCompileOnDiskModule. -/
unsafe def tryCompileAfterHostModuleCheckParityProgramTermSmallDepsIO
    (srcPath oleanDir : System.FilePath) (thmMod : Name) : IO Bool :=
  tryCompileAfterNamedDepsIO srcPath oleanDir thmMod
    ["SystemsLean.Mult",
     "SystemsLean.MultTheorems",
     "SystemsLean.Types",
     "SystemsLean.TypesTheorems",
     "SystemsLean.Erasure",
     "SystemsLean.ErasureTheorems",
     "SystemsLean.Extract",
     "SystemsLean.ExtractTheorems",
     "SystemsLean.IrProgram",
     "SystemsLean.IrProgramTheorems",
     "SystemsLean.HostTerm",
     "SystemsLean.HostFrontGoldens",
     "SystemsLean.HostFront",
     "SystemsLean.HostFrontTheorems",
     "SystemsLean.HostCheck",
     "SystemsLean.HostGraph",
     "SystemsLean.HostGraphTheorems",
     "SystemsLean.IrGraph",
     "SystemsLean.HostCompose",
     "SystemsLean.CompilePath",
     "SystemsLean.EmitMultScaffold",
     "SystemsLean.EmitLinearScaffold",
     "SystemsLean.EmitTypesScaffold",
     "SystemsLean.EmitProgramScaffold",
     "SystemsLean.EmitGraphScaffold",
     "SystemsLean.EmitComposeScaffold",
     "SystemsLean.EmitMult",
     "SystemsLean.EmitLinear",
     "SystemsLean.EmitTypes",
     "SystemsLean.EmitProgram",
     "SystemsLean.EmitGraph",
     "SystemsLean.EmitCompose",
     "SystemsLean.CompilePathMult",
     "SystemsLean.CompilePathLinear",
     "SystemsLean.CompilePathTypes",
     "SystemsLean.CompilePathProgram",
     "SystemsLean.CompilePathGraph",
     "SystemsLean.CompilePathCompose",
     "SystemsLean.FirstSurface",
     "SystemsLean.MultSubsetEmit",
     "SystemsLean.LinearSubsetEmit",
     "SystemsLean.TypesSubsetEmit",
     "SystemsLean.ProgramSubsetEmit",
     "SystemsLean.GraphSubsetEmit",
     "SystemsLean.ComposeSubsetEmit",
     "SystemsLean.HostPackageWrite",
     "SystemsLean.HostPackageWriteTheorems",
     "SystemsLean.HostPackageRoots",
     "SystemsLean.HostImportGraphSeeds",
     "SystemsLean.HostImportGraphModel",
     "SystemsLean.HostImportGraphMods",
     "SystemsLean.HostImportGraphModsLater",
     "SystemsLean.HostImportGraphLoadOkLater",
     "SystemsLean.HostImportGraphWalkLater",
     "SystemsLean.HostImportGraphWalk",
     "SystemsLean.HostModuleCheckRequiredDecls",
     "SystemsLean.HostModuleCheckRequiredDeclsProduct",
     "SystemsLean.HostModuleCheckRequiredDeclsLater",
     "SystemsLean.HostModuleCheckFixtureTexts",
     "SystemsLean.HostModuleCheckFixtureTextsProduct",
     "SystemsLean.HostModuleCheckFixtureTextsLater",
     "SystemsLean.HostModuleCheckFixtureTextsSelfHost",
     "SystemsLean.HostModuleCheckFixtureTextsEmit",
     "SystemsLean.HostModuleCheckFixtures",
     "SystemsLean.HostModuleCheckSurface",
     "SystemsLean.HostModuleCheckMultTerm",
     "SystemsLean.HostModuleCheckMultProof",
     "SystemsLean.HostModuleCheckLinearProof",
     "SystemsLean.HostModuleCheckTypesProof",
     "SystemsLean.HostModuleCheckKernelMultProof",
     "SystemsLean.HostModuleCheckKernelLinearProof",
     "SystemsLean.HostModuleCheckKernelTypesProof",
     "SystemsLean.HostModuleCheckKernelProgramProof",
     "SystemsLean.HostModuleCheckKernelEmitProof",
     "SystemsLean.HostModuleCheckLinearTerm",
     "SystemsLean.HostModuleCheckTypesTerm",
     "SystemsLean.HostModuleCheckIrProgramTerm",
     "SystemsLean.HostModuleCheckIrGraphTerm",
     "SystemsLean.HostModuleCheckHostComposeTerm",
     "SystemsLean.HostModuleCheckErasureTerm",
     "SystemsLean.HostModuleCheckExtractTerm",
     "SystemsLean.HostModuleCheckEmitPlanTerm",
     "SystemsLean.HostModuleCheckEmitMultScaffoldTerm",
     "SystemsLean.HostModuleCheckEmitLinearScaffoldTerm",
     "SystemsLean.HostModuleCheckEmitTypesScaffoldTerm",
     "SystemsLean.HostModuleCheckEmitProgramScaffoldTerm",
     "SystemsLean.HostModuleCheckEmitGraphScaffoldTerm",
     "SystemsLean.HostModuleCheckEmitComposeScaffoldTerm",
     "SystemsLean.HostModuleCheckEmitErasureScaffoldTerm",
     "SystemsLean.HostModuleCheckEmitExtractScaffoldTerm",
     "SystemsLean.HostModuleCheckEmitApplyTerm",
     "SystemsLean.HostModuleCheckParityEmitTerm",
     "SystemsLean.HostModuleCheckEmitBannerScaffoldTerm",
     "SystemsLean.HostModuleCheckKernelSelfApplyTerm",
     "SystemsLean.HostModuleCheckProductOutKernelTerm",
     "SystemsLean.HostModuleCheckCompilePathTerm",
     "SystemsLean.HostModuleCheckJoinMapTerm",
     "SystemsLean.HostModuleCheckSelfHostTerm",
     "SystemsLean.HostModuleCheckSurfaceMatrixTerm",
     "SystemsLean.HostModuleCheckSpecProofTerm",
     "SystemsLean.HostModuleCheckDualResidualTerm",
     "SystemsLean.HostModuleCheckCompilePathMultTerm",
     "SystemsLean.HostModuleCheckCompilePathLinearTerm",
     "SystemsLean.HostModuleCheckCompilePathTypesTerm",
     "SystemsLean.HostModuleCheckCompilePathProgramTerm",
     "SystemsLean.HostModuleCheckCompilePathGraphTerm",
     "SystemsLean.HostModuleCheckCompilePathComposeTerm",
     "SystemsLean.HostModuleCheckCompilePathErasureTerm",
     "SystemsLean.HostModuleCheckCompilePathExtractTerm",
     "SystemsLean.HostModuleCheckCompilePathPlanTerm",
     "SystemsLean.HostModuleCheckCompilePathApplyTerm",
     "SystemsLean.HostModuleCheckCompilePathBodyTerm",
     "SystemsLean.HostModuleCheckFirstSurfaceTerm",
     "SystemsLean.HostModuleCheckLinearSubsetEmitTerm",
     "SystemsLean.HostModuleCheckTypesSubsetEmitTerm",
     "SystemsLean.HostModuleCheckProgramSubsetEmitTerm",
     "SystemsLean.HostModuleCheckGraphSubsetEmitTerm",
     "SystemsLean.HostModuleCheckComposeSubsetEmitTerm",
     "SystemsLean.HostModuleCheckErasureSubsetEmitTerm",
     "SystemsLean.HostModuleCheckExtractSubsetEmitTerm",
     "SystemsLean.HostModuleCheckMultSubsetEmitTerm",
     "SystemsLean.HostModuleCheckMultSubsetRebuildTerm",
     "SystemsLean.HostModuleCheckLinearSubsetRebuildTerm",
     "SystemsLean.HostModuleCheckTypesSubsetRebuildTerm",
     "SystemsLean.HostModuleCheckProgramSubsetRebuildTerm",
     "SystemsLean.HostModuleCheckGraphSubsetRebuildTerm",
     "SystemsLean.HostModuleCheckComposeSubsetRebuildTerm",
     "SystemsLean.HostModuleCheckErasureSubsetRebuildTerm",
     "SystemsLean.HostModuleCheckExtractSubsetRebuildTerm",
     "SystemsLean.HostModuleCheckHostFrontTerm",
     "SystemsLean.HostModuleCheckLlvmMultTextTerm",
     "SystemsLean.HostModuleCheckHostCheckTerm",
     "SystemsLean.HostModuleCheckHostGraphTerm",
     "SystemsLean.HostModuleCheckLlvmLinearTextTerm",
     "SystemsLean.HostModuleCheckMultFsWriteToolTerm",
     "SystemsLean.HostModuleCheckFrontMultPackageTerm",
     "SystemsLean.HostModuleCheckSubsetPackageJoinTerm",
     "SystemsLean.HostModuleCheckLlvmTypesTextTerm",
     "SystemsLean.HostModuleCheckMultFsDeepenTerm",
     "SystemsLean.HostModuleCheckHostPackageWriteTerm",
     "SystemsLean.HostModuleCheckLlvmProgramTextTerm",
     "SystemsLean.HostModuleCheckLlvmGraphTextTerm",
     "SystemsLean.HostModuleCheckLlvmComposeTextTerm",
     "SystemsLean.HostModuleCheckSelfApplyFsTerm",
     "SystemsLean.HostModuleCheckInventoryCloseTerm",
     "SystemsLean.HostModuleCheckProductPathBarsTerm",
     "SystemsLean.HostModuleCheckProductPathTerm",
     "SystemsLean.HostModuleCheckProbeWireTerm",
     "SystemsLean.HostModuleCheckSelfHostBodyTerm",
     "SystemsLean.HostModuleCheckLoadOkCompilePathUnits",
     "SystemsLean.HostModuleCheckCheckers",
     "SystemsLean.HostModuleCheckCheckersLater",
     "SystemsLean.HostModuleCheckEmitBodyTerm",
     "SystemsLean.HostModuleCheckKernelMultTerm",
     "SystemsLean.HostModuleCheckKernelLinearTerm",
     "SystemsLean.HostModuleCheckKernelTypesTerm",
     "SystemsLean.HostModuleCheckKernelProgramTerm",
     "SystemsLean.HostModuleCheckKernelEmitTerm",
     "SystemsLean.HostModuleCheckParityMultTerm",
     "SystemsLean.HostModuleCheckParityLinearTerm",
     "SystemsLean.HostModuleCheckParityTypesTerm"]

@[implemented_by tryCompileAfterHostModuleCheckParityProgramTermSmallDepsIO]
opaque tryCompileAfterHostModuleCheckParityProgramTermSmallDepsIOSafe
    (srcPath oleanDir : System.FilePath) (thmMod : Name) : IO Bool

/-- CommandElab wrapper: compile after smaller Program isolation deps.
    Greppable: tryCompileAfterHostModuleCheckParityProgramTermSmallDeps. -/
def tryCompileAfterHostModuleCheckParityProgramTermSmallDeps
    (srcPath oleanDir : System.FilePath) (thmMod : Name) :
    CommandElabM Bool := do
  try
    liftIO
      (tryCompileAfterHostModuleCheckParityProgramTermSmallDepsIOSafe
        srcPath oleanDir thmMod)
  catch _ =>
    pure false

end SystemsLean.ElabMeet
"#

end SystemsLean.HostFrontLiveOccupancyWalk
