/-
  SYSTEMS_LEAN_HOST partial -- HostImportGraph LoadOk fold + readiness pins.
  Side: classic Lean elaborator under src/systems/ (not freestanding C).
  Long-file peel companion. Namespace SystemsLean.HostImportGraph.
  Import-edge dual-pins live in HostImportGraphLoadOkLater (hostImportGraphLoadOkImportEdges).
  Non-claims: PARTIAL-STRUCTURAL; Not freestanding residual free; Not PROVABLY;
  Host elaborator residual remains.
  Greppable: SYSTEMS_LEAN_HOST, HOST-IMPORT-GRAPH, HostImportGraphLoadOk,
  HostImportGraphLoadOkLater, hostImportGraphLoadOk, hostImportGraphReady,
  hostImportGraphWithoutLakeReady, hostImportGraphWithoutLakeKeepsHostLake,
  HOST-IMPORT-GRAPH-WITHOUT-LAKE.
  Module: SystemsLean.HostImportGraphLoadOk
  UNIT_SURFACE host surface, MULT-0, MULT-1, MULT-OMEGA (peer Mult-first cite).
  Red/green: lake build SystemsLean.HostImportGraphLoadOk; just systems-host.
  Not freestanding residual free. Not freestanding emit. Not PROVABLY. Host elaborator residual remains.
-/
import SystemsLean.HostImportGraphModsLater
import SystemsLean.HostImportGraphLoadOkLater
namespace SystemsLean.HostImportGraph
/-- Structural expand seed dual-pin holds (good accept + fail-closed missing/cycle).
    Greppable: hostImportGraphLoadOk. -/
def hostImportGraphLoadOk : Bool :=
  hostImportGraphGoodMultSeed.isAccept
    && (hostImportGraphGoodMultSeed.acceptCount == 2)
    && hostImportGraphGoodExpandSeed.isAccept
    && (hostImportGraphGoodExpandSeed.acceptCount == 206)
    && hostImportGraphBadMissing.isRejectWith reasonMissingImport
    && hostImportGraphBadCycle.isRejectWith reasonImportCycle
    && (hostImportGraphSeedModules
      == ["SystemsLean.Mult",
          "SystemsLean.MultTheorems",
          "SystemsLean.Linear",
          "SystemsLean.LinearTheorems",
          "SystemsLean.Types",
          "SystemsLean.TypesTheorems",
          "SystemsLean.IrProgram",
          "SystemsLean.IrProgramTheorems",
          "SystemsLean.IrGraph",
          "SystemsLean.IrGraphTheorems",
          "SystemsLean.HostCompose",
          "SystemsLean.HostComposeTheorems",
          "SystemsLean.Erasure",
          "SystemsLean.ErasureTheorems",
          "SystemsLean.Extract",
          "SystemsLean.ExtractTheorems",
          "SystemsLean.CompilePath",
          "SystemsLean.KernelMult",
          "SystemsLean.KernelLinear",
          "SystemsLean.KernelTypes",
          "SystemsLean.KernelProgram",
          "SystemsLean.KernelMultTheorems",
          "SystemsLean.KernelLinearTheorems",
          "SystemsLean.KernelTypesTheorems",
          "SystemsLean.KernelProgramTheorems",
          "SystemsLean.JoinMap",
          "SystemsLean.JoinMapTheorems",
          "SystemsLean.SelfHost",
          "SystemsLean.SelfHostTheorems",
          "SystemsLean.SurfaceMatrix",
          "SystemsLean.SurfaceMatrixTheorems",
          "SystemsLean.EmitMultScaffold",
          "SystemsLean.EmitLinearScaffold",
          "SystemsLean.EmitTypesScaffold",
          "SystemsLean.EmitProgramScaffold",
          "SystemsLean.EmitGraphScaffold",
          "SystemsLean.EmitComposeScaffold",
          "SystemsLean.EmitPlanScaffold",
          "SystemsLean.EmitApplyScaffold",
          "SystemsLean.EmitBodyScaffold",
          "SystemsLean.EmitErasureScaffold",
          "SystemsLean.EmitExtractScaffold",
          "SystemsLean.EmitBannerScaffold",
          "SystemsLean.KernelSelfApply",
          "SystemsLean.KernelSelfApplyTheorems",
          "SystemsLean.EmitMult",
          "SystemsLean.EmitPlan",
          "SystemsLean.EmitApply",
          "SystemsLean.EmitBody",
          "SystemsLean.KernelEmit",
          "SystemsLean.KernelEmitTheorems",
          "SystemsLean.ParityMult",
          "SystemsLean.ParityMultTheorems",
          "SystemsLean.ParityLinear",
          "SystemsLean.ParityLinearTheorems",
          "SystemsLean.ParityTypes",
          "SystemsLean.ParityTypesTheorems",
          "SystemsLean.ParityProgram",
          "SystemsLean.ParityProgramTheorems",
          "SystemsLean.ParityEmit",
          "SystemsLean.ParityEmitTheorems",
          "SystemsLean.SelfApply",
          "SystemsLean.SelfApplyTheorems",
          "SystemsLean.EmitLinear",
          "SystemsLean.EmitTypes",
          "SystemsLean.EmitProgram",
          "SystemsLean.EmitGraph",
          "SystemsLean.EmitCompose",
          "SystemsLean.EmitErasure",
          "SystemsLean.EmitExtract",
          "SystemsLean.EmitBanner",
          "SystemsLean.ProductOutKernel",
          "SystemsLean.ProductOutKernelTheorems",
          "SystemsLean.BootstrapHonesty",
          "SystemsLean.BootstrapHonestyTheorems",
          "SystemsLean.ProductPathWriterSurface",
          "SystemsLean.ProductPathWriterSurfaceTheorems",
          "SystemsLean.ProductPathWriterPathPlan",
          "SystemsLean.ProductPathWriterPathPlanTheorems",
          "SystemsLean.ProductPathWriterPathExec",
          "SystemsLean.ProductPathWriterPathExecTheorems",
   "SystemsLean.ProductPathOwnershipInputs",
   "SystemsLean.ProductPathOwnershipInputsTheorems",
   "SystemsLean.ProductPathPerform",
   "SystemsLean.ProductPathPerformTheorems",
   "SystemsLean.ProductPathPerformStep",
   "SystemsLean.ProductPathPerformStepTheorems",
   "SystemsLean.ProductPathReadSsot",
   "SystemsLean.ProductPathReadSsotTheorems",
   "SystemsLean.ProductPathComposePlan",
   "SystemsLean.ProductPathComposePlanTheorems",
   "SystemsLean.Capable",
   "SystemsLean.CapableTheorems",
   "SystemsLean.CapableStepContract",
   "SystemsLean.CapableStepContractTheorems",
   "SystemsLean.InstallOut",
   "SystemsLean.InstallOutTheorems",
   "SystemsLean.OfficialPath",
   "SystemsLean.OfficialPathTheorems",
   "SystemsLean.PerformEvidence",
   "SystemsLean.PerformEvidenceTheorems",
   "SystemsLean.CapableRead",
   "SystemsLean.CapableReadTheorems",
   "SystemsLean.CapableCompose",
   "SystemsLean.CapableComposeTheorems",
   "SystemsLean.CapableFullBar",
   "SystemsLean.CapableFullBarTheorems",
   "SystemsLean.DualEqWriteCapableGap",
   "SystemsLean.DualEqWriteCapableGapTheorems",
   "SystemsLean.DualEqWriteClosePath",
   "SystemsLean.DualEqWriteClosePathTheorems",
   "SystemsLean.DualEqWriteParity",
   "SystemsLean.DualEqWriteParityTheorems",
   "SystemsLean.OfficialRetire",
   "SystemsLean.OfficialRetireTheorems",
   "SystemsLean.OwnershipClaimed",
   "SystemsLean.OwnershipClaimedTheorems",
   "SystemsLean.PerformClaimed",
   "SystemsLean.PerformClaimedTheorems",
   "SystemsLean.StepContractFull",
   "SystemsLean.StepContractFullTheorems",
   "SystemsLean.SelfHostComplete",
   "SystemsLean.SelfHostCompleteTheorems",
   "SystemsLean.OfficialPathAlternate",
   "SystemsLean.OfficialPathAlternateTheorems",
   "SystemsLean.ProductPathOwnershipRegenerate",
   "SystemsLean.ProductPathOwnershipRegenerateTheorems",
   "SystemsLean.CapableWriteHcLoad",
   "SystemsLean.DualEqWriteLoad",
   "SystemsLean.CapableWriteHc",
   "SystemsLean.DualEqWriteApi",
   "SystemsLean.LlvmHold",
   "SystemsLean.LlvmHoldTheorems",
   "SystemsLean.CapableRegenerate",
   "SystemsLean.CapableRegenerateTheorems",
   "SystemsLean.FreestandingEmitLoad",
   "SystemsLean.FreestandingEmitLoadScaffold",
   "SystemsLean.LakeRetireInventory",
   "SystemsLean.HostPackageRoots",
   "SystemsLean.FreestandingEmit",
   "SystemsLean.ProductPathWriteHc",
   "SystemsLean.ProductPathWriteHcTheorems",
   "SystemsLean.CompilePathMult",
   "SystemsLean.CompilePathLinear",
   "SystemsLean.CompilePathTypes",
   "SystemsLean.CompilePathProgram",
   "SystemsLean.CompilePathGraph",
   "SystemsLean.CompilePathCompose",
   "SystemsLean.CompilePathPlan",
   "SystemsLean.CompilePathApply",
   "SystemsLean.CompilePathBody",
   "SystemsLean.CompilePathErasure",
   "SystemsLean.CompilePathExtract",
   "SystemsLean.ProductWireWriteTool",
   "SystemsLean.HostTerm",
   "SystemsLean.LlvmEmitPath",
   "SystemsLean.SubsetFront",
   "SystemsLean.FirstSurface",
   "SystemsLean.LinearSubsetEmit",
   "SystemsLean.TypesSubsetEmit",
   "SystemsLean.ProgramSubsetEmit",
   "SystemsLean.GraphSubsetEmit",
   "SystemsLean.ComposeSubsetEmit",
   "SystemsLean.ErasureSubsetEmit",
   "SystemsLean.ExtractSubsetEmit",
   "SystemsLean.MultSubsetEmit",
   "SystemsLean.MultSubsetRebuild",
   "SystemsLean.LinearSubsetRebuild",
   "SystemsLean.TypesSubsetRebuild",
   "SystemsLean.ProgramSubsetRebuild",
   "SystemsLean.GraphSubsetRebuild",
   "SystemsLean.ComposeSubsetRebuild",
   "SystemsLean.ErasureSubsetRebuild",
   "SystemsLean.ExtractSubsetRebuild",
   "SystemsLean.HostFront",
   "SystemsLean.LlvmMultText",
   "SystemsLean.HostFrontTheorems",
   "SystemsLean.HostCheck",
   "SystemsLean.HostGraph",
   "SystemsLean.LlvmLinearText",
   "SystemsLean.MultFsWriteTool",
   "SystemsLean.FrontMultPackage",
   "SystemsLean.SubsetPackageJoin",
   "SystemsLean.HostGraphTheorems",
   "SystemsLean.LlvmTypesText",
   "SystemsLean.MultFsDeepen",
   "SystemsLean.HostPackageWrite",
   "SystemsLean.HostPackageWriteTheorems",
   "SystemsLean.LlvmProgramText",
   "SystemsLean.LlvmGraphText",
   "SystemsLean.LlvmComposeText",
   "SystemsLean.SelfApplyFs",
   "SystemsLean.SelfApplyFsTheorems",
   "SystemsLean.InventoryClose",
   "SystemsLean.ProductPathBars",
   "SystemsLean.InventoryCloseTheorems",
   "SystemsLean.ProductPath",
   "SystemsLean.ProductPathTheorems",
   "SystemsLean.DualResidual",
   "SystemsLean.DualResidualTheorems",
   "SystemsLean.ProbeWire",
   "SystemsLean.SelfHostBody",
   "SystemsLean.ProbeWireTheorems",
   "SystemsLean.SelfHostBodyTheorems",
   "SystemsLean.SpecProof",
   "SystemsLean.SpecProofTheorems"])
    && (hostImportGraphSeedRelPaths
      == ["src/systems/SystemsLean/Mult.lean",
          "src/systems/SystemsLean/MultTheorems.lean",
          "src/systems/SystemsLean/Linear.lean",
          "src/systems/SystemsLean/LinearTheorems.lean",
          "src/systems/SystemsLean/Types.lean",
          "src/systems/SystemsLean/TypesTheorems.lean",
          "src/systems/SystemsLean/IrProgram.lean",
          "src/systems/SystemsLean/IrProgramTheorems.lean",
          "src/systems/SystemsLean/IrGraph.lean",
          "src/systems/SystemsLean/IrGraphTheorems.lean",
          "src/systems/SystemsLean/HostCompose.lean",
          "src/systems/SystemsLean/HostComposeTheorems.lean",
          "src/systems/SystemsLean/Erasure.lean",
          "src/systems/SystemsLean/ErasureTheorems.lean",
          "src/systems/SystemsLean/Extract.lean",
          "src/systems/SystemsLean/ExtractTheorems.lean",
          "src/systems/SystemsLean/CompilePath.lean",
          "src/systems/SystemsLean/KernelMult.lean",
          "src/systems/SystemsLean/KernelLinear.lean",
          "src/systems/SystemsLean/KernelTypes.lean",
          "src/systems/SystemsLean/KernelProgram.lean",
          "src/systems/SystemsLean/KernelMultTheorems.lean",
          "src/systems/SystemsLean/KernelLinearTheorems.lean",
          "src/systems/SystemsLean/KernelTypesTheorems.lean",
          "src/systems/SystemsLean/KernelProgramTheorems.lean",
          "src/systems/SystemsLean/JoinMap.lean",
          "src/systems/SystemsLean/JoinMapTheorems.lean",
          "src/systems/SystemsLean/SelfHost.lean",
          "src/systems/SystemsLean/SelfHostTheorems.lean",
          "src/systems/SystemsLean/SurfaceMatrix.lean",
          "src/systems/SystemsLean/SurfaceMatrixTheorems.lean",
          "src/systems/SystemsLean/EmitMultScaffold.lean",
          "src/systems/SystemsLean/EmitLinearScaffold.lean",
          "src/systems/SystemsLean/EmitTypesScaffold.lean",
          "src/systems/SystemsLean/EmitProgramScaffold.lean",
          "src/systems/SystemsLean/EmitGraphScaffold.lean",
          "src/systems/SystemsLean/EmitComposeScaffold.lean",
          "src/systems/SystemsLean/EmitPlanScaffold.lean",
          "src/systems/SystemsLean/EmitApplyScaffold.lean",
          "src/systems/SystemsLean/EmitBodyScaffold.lean",
          "src/systems/SystemsLean/EmitErasureScaffold.lean",
          "src/systems/SystemsLean/EmitExtractScaffold.lean",
          "src/systems/SystemsLean/EmitBannerScaffold.lean",
          "src/systems/SystemsLean/KernelSelfApply.lean",
          "src/systems/SystemsLean/KernelSelfApplyTheorems.lean",
          "src/systems/SystemsLean/EmitMult.lean",
          "src/systems/SystemsLean/EmitPlan.lean",
          "src/systems/SystemsLean/EmitApply.lean",
          "src/systems/SystemsLean/EmitBody.lean",
          "src/systems/SystemsLean/KernelEmit.lean",
          "src/systems/SystemsLean/KernelEmitTheorems.lean",
          "src/systems/SystemsLean/ParityMult.lean",
          "src/systems/SystemsLean/ParityMultTheorems.lean",
          "src/systems/SystemsLean/ParityLinear.lean",
          "src/systems/SystemsLean/ParityLinearTheorems.lean",
          "src/systems/SystemsLean/ParityTypes.lean",
          "src/systems/SystemsLean/ParityTypesTheorems.lean",
          "src/systems/SystemsLean/ParityProgram.lean",
          "src/systems/SystemsLean/ParityProgramTheorems.lean",
          "src/systems/SystemsLean/ParityEmit.lean",
          "src/systems/SystemsLean/ParityEmitTheorems.lean",
          "src/systems/SystemsLean/SelfApply.lean",
          "src/systems/SystemsLean/SelfApplyTheorems.lean",
          "src/systems/SystemsLean/EmitLinear.lean",
          "src/systems/SystemsLean/EmitTypes.lean",
          "src/systems/SystemsLean/EmitProgram.lean",
          "src/systems/SystemsLean/EmitGraph.lean",
          "src/systems/SystemsLean/EmitCompose.lean",
          "src/systems/SystemsLean/EmitErasure.lean",
          "src/systems/SystemsLean/EmitExtract.lean",
          "src/systems/SystemsLean/EmitBanner.lean",
          "src/systems/SystemsLean/ProductOutKernel.lean",
          "src/systems/SystemsLean/ProductOutKernelTheorems.lean",
          "src/systems/SystemsLean/BootstrapHonesty.lean",
          "src/systems/SystemsLean/BootstrapHonestyTheorems.lean",
          "src/systems/SystemsLean/ProductPathWriterSurface.lean",
          "src/systems/SystemsLean/ProductPathWriterSurfaceTheorems.lean",
          "src/systems/SystemsLean/ProductPathWriterPathPlan.lean",
          "src/systems/SystemsLean/ProductPathWriterPathPlanTheorems.lean",
          "src/systems/SystemsLean/ProductPathWriterPathExec.lean",
          "src/systems/SystemsLean/ProductPathWriterPathExecTheorems.lean",
   "src/systems/SystemsLean/ProductPathOwnershipInputs.lean",
   "src/systems/SystemsLean/ProductPathOwnershipInputsTheorems.lean",
   "src/systems/SystemsLean/ProductPathPerform.lean",
   "src/systems/SystemsLean/ProductPathPerformTheorems.lean",
   "src/systems/SystemsLean/ProductPathPerformStep.lean",
   "src/systems/SystemsLean/ProductPathPerformStepTheorems.lean",
   "src/systems/SystemsLean/ProductPathReadSsot.lean",
   "src/systems/SystemsLean/ProductPathReadSsotTheorems.lean",
   "src/systems/SystemsLean/ProductPathComposePlan.lean",
   "src/systems/SystemsLean/ProductPathComposePlanTheorems.lean",
   "src/systems/SystemsLean/Capable.lean",
   "src/systems/SystemsLean/CapableTheorems.lean",
   "src/systems/SystemsLean/CapableStepContract.lean",
   "src/systems/SystemsLean/CapableStepContractTheorems.lean",
   "src/systems/SystemsLean/InstallOut.lean",
   "src/systems/SystemsLean/InstallOutTheorems.lean",
   "src/systems/SystemsLean/OfficialPath.lean",
   "src/systems/SystemsLean/OfficialPathTheorems.lean",
   "src/systems/SystemsLean/PerformEvidence.lean",
   "src/systems/SystemsLean/PerformEvidenceTheorems.lean",
   "src/systems/SystemsLean/CapableRead.lean",
   "src/systems/SystemsLean/CapableReadTheorems.lean",
   "src/systems/SystemsLean/CapableCompose.lean",
   "src/systems/SystemsLean/CapableComposeTheorems.lean",
   "src/systems/SystemsLean/CapableFullBar.lean",
   "src/systems/SystemsLean/CapableFullBarTheorems.lean",
   "src/systems/SystemsLean/DualEqWriteCapableGap.lean",
   "src/systems/SystemsLean/DualEqWriteCapableGapTheorems.lean",
   "src/systems/SystemsLean/DualEqWriteClosePath.lean",
   "src/systems/SystemsLean/DualEqWriteClosePathTheorems.lean",
   "src/systems/SystemsLean/DualEqWriteParity.lean",
   "src/systems/SystemsLean/DualEqWriteParityTheorems.lean",
   "src/systems/SystemsLean/OfficialRetire.lean",
   "src/systems/SystemsLean/OfficialRetireTheorems.lean",
   "src/systems/SystemsLean/OwnershipClaimed.lean",
   "src/systems/SystemsLean/OwnershipClaimedTheorems.lean",
   "src/systems/SystemsLean/PerformClaimed.lean",
   "src/systems/SystemsLean/PerformClaimedTheorems.lean",
   "src/systems/SystemsLean/StepContractFull.lean",
   "src/systems/SystemsLean/StepContractFullTheorems.lean",
   "src/systems/SystemsLean/SelfHostComplete.lean",
   "src/systems/SystemsLean/SelfHostCompleteTheorems.lean",
   "src/systems/SystemsLean/OfficialPathAlternate.lean",
   "src/systems/SystemsLean/OfficialPathAlternateTheorems.lean",
   "src/systems/SystemsLean/ProductPathOwnershipRegenerate.lean",
   "src/systems/SystemsLean/ProductPathOwnershipRegenerateTheorems.lean",
   "src/systems/SystemsLean/CapableWriteHcLoad.lean",
   "src/systems/SystemsLean/DualEqWriteLoad.lean",
   "src/systems/SystemsLean/CapableWriteHc.lean",
   "src/systems/SystemsLean/DualEqWriteApi.lean",
   "src/systems/SystemsLean/LlvmHold.lean",
   "src/systems/SystemsLean/LlvmHoldTheorems.lean",
   "src/systems/SystemsLean/CapableRegenerate.lean",
   "src/systems/SystemsLean/CapableRegenerateTheorems.lean",
   "src/systems/SystemsLean/FreestandingEmitLoad.lean",
   "src/systems/SystemsLean/FreestandingEmitLoadScaffold.lean",
   "src/systems/SystemsLean/LakeRetireInventory.lean",
   "src/systems/SystemsLean/HostPackageRoots.lean",
   "src/systems/SystemsLean/FreestandingEmit.lean",
   "src/systems/SystemsLean/ProductPathWriteHc.lean",
   "src/systems/SystemsLean/ProductPathWriteHcTheorems.lean",
   "src/systems/SystemsLean/CompilePathMult.lean",
   "src/systems/SystemsLean/CompilePathLinear.lean",
   "src/systems/SystemsLean/CompilePathTypes.lean",
   "src/systems/SystemsLean/CompilePathProgram.lean",
   "src/systems/SystemsLean/CompilePathGraph.lean",
   "src/systems/SystemsLean/CompilePathCompose.lean",
   "src/systems/SystemsLean/CompilePathPlan.lean",
   "src/systems/SystemsLean/CompilePathApply.lean",
   "src/systems/SystemsLean/CompilePathBody.lean",
   "src/systems/SystemsLean/CompilePathErasure.lean",
   "src/systems/SystemsLean/CompilePathExtract.lean",
   "src/systems/SystemsLean/ProductWireWriteTool.lean",
   "src/systems/SystemsLean/HostTerm.lean",
   "src/systems/SystemsLean/LlvmEmitPath.lean",
   "src/systems/SystemsLean/SubsetFront.lean",
   "src/systems/SystemsLean/FirstSurface.lean",
   "src/systems/SystemsLean/LinearSubsetEmit.lean",
   "src/systems/SystemsLean/TypesSubsetEmit.lean",
   "src/systems/SystemsLean/ProgramSubsetEmit.lean",
   "src/systems/SystemsLean/GraphSubsetEmit.lean",
   "src/systems/SystemsLean/ComposeSubsetEmit.lean",
   "src/systems/SystemsLean/ErasureSubsetEmit.lean",
   "src/systems/SystemsLean/ExtractSubsetEmit.lean",
   "src/systems/SystemsLean/MultSubsetEmit.lean",
   "src/systems/SystemsLean/MultSubsetRebuild.lean",
   "src/systems/SystemsLean/LinearSubsetRebuild.lean",
   "src/systems/SystemsLean/TypesSubsetRebuild.lean",
   "src/systems/SystemsLean/ProgramSubsetRebuild.lean",
   "src/systems/SystemsLean/GraphSubsetRebuild.lean",
   "src/systems/SystemsLean/ComposeSubsetRebuild.lean",
   "src/systems/SystemsLean/ErasureSubsetRebuild.lean",
   "src/systems/SystemsLean/ExtractSubsetRebuild.lean",
   "src/systems/SystemsLean/HostFront.lean",
   "src/systems/SystemsLean/LlvmMultText.lean",
   "src/systems/SystemsLean/HostFrontTheorems.lean",
   "src/systems/SystemsLean/HostCheck.lean",
   "src/systems/SystemsLean/HostGraph.lean",
   "src/systems/SystemsLean/LlvmLinearText.lean",
   "src/systems/SystemsLean/MultFsWriteTool.lean",
   "src/systems/SystemsLean/FrontMultPackage.lean",
   "src/systems/SystemsLean/SubsetPackageJoin.lean",
   "src/systems/SystemsLean/HostGraphTheorems.lean",
   "src/systems/SystemsLean/LlvmTypesText.lean",
   "src/systems/SystemsLean/MultFsDeepen.lean",
   "src/systems/SystemsLean/HostPackageWrite.lean",
   "src/systems/SystemsLean/HostPackageWriteTheorems.lean",
   "src/systems/SystemsLean/LlvmProgramText.lean",
   "src/systems/SystemsLean/LlvmGraphText.lean",
   "src/systems/SystemsLean/LlvmComposeText.lean",
   "src/systems/SystemsLean/SelfApplyFs.lean",
   "src/systems/SystemsLean/SelfApplyFsTheorems.lean",
   "src/systems/SystemsLean/InventoryClose.lean",
   "src/systems/SystemsLean/ProductPathBars.lean",
   "src/systems/SystemsLean/InventoryCloseTheorems.lean",
   "src/systems/SystemsLean/ProductPath.lean",
   "src/systems/SystemsLean/ProductPathTheorems.lean",
   "src/systems/SystemsLean/DualResidual.lean",
   "src/systems/SystemsLean/DualResidualTheorems.lean",
   "src/systems/SystemsLean/ProbeWire.lean",
   "src/systems/SystemsLean/SelfHostBody.lean",
   "src/systems/SystemsLean/ProbeWireTheorems.lean",
   "src/systems/SystemsLean/SelfHostBodyTheorems.lean",
   "src/systems/SystemsLean/SpecProof.lean",
   "src/systems/SystemsLean/SpecProofTheorems.lean"])
    && (designNotePath
      == "doc/dev/research/full-host-elaborator-design-2026-08-03.md")
    && (residualName == "Real Mult import graph")
    && (hostImportGraphExpandSliceName == "Host library seed expand continue")
    && (hostImportGraphSeedUnitsLabel
      == "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems+IrGraph+IrGraphTheorems+HostCompose+HostComposeTheorems+Erasure+ErasureTheorems+Extract+ExtractTheorems+CompilePath+KernelMult+KernelLinear+KernelTypes+KernelProgram+KernelMultTheorems+KernelLinearTheorems+KernelTypesTheorems+KernelProgramTheorems+JoinMap+JoinMapTheorems+SelfHost+SelfHostTheorems+SurfaceMatrix+SurfaceMatrixTheorems+EmitMultScaffold+EmitLinearScaffold+EmitTypesScaffold+EmitProgramScaffold+EmitGraphScaffold+EmitComposeScaffold+EmitPlanScaffold+EmitApplyScaffold+EmitBodyScaffold+EmitErasureScaffold+EmitExtractScaffold+EmitBannerScaffold+KernelSelfApply+KernelSelfApplyTheorems+EmitMult+EmitPlan+EmitApply+EmitBody+KernelEmit+KernelEmitTheorems+ParityMult+ParityMultTheorems+ParityLinear+ParityLinearTheorems+ParityTypes+ParityTypesTheorems+ParityProgram+ParityProgramTheorems+ParityEmit+ParityEmitTheorems+SelfApply+SelfApplyTheorems+EmitLinear+EmitTypes+EmitProgram+EmitGraph+EmitCompose+EmitErasure+EmitExtract+EmitBanner+ProductOutKernel+ProductOutKernelTheorems+BootstrapHonesty+BootstrapHonestyTheorems+ProductPathWriterSurface+ProductPathWriterSurfaceTheorems+ProductPathWriterPathPlan+ProductPathWriterPathPlanTheorems+ProductPathWriterPathExec+ProductPathWriterPathExecTheorems+ProductPathOwnershipInputs+ProductPathOwnershipInputsTheorems+ProductPathPerform+ProductPathPerformTheorems+ProductPathPerformStep+ProductPathPerformStepTheorems+ProductPathReadSsot+ProductPathReadSsotTheorems+ProductPathComposePlan+ProductPathComposePlanTheorems+Capable+CapableTheorems+CapableStepContract+CapableStepContractTheorems+InstallOut+InstallOutTheorems+OfficialPath+OfficialPathTheorems+PerformEvidence+PerformEvidenceTheorems+CapableRead+CapableReadTheorems+CapableCompose+CapableComposeTheorems+CapableFullBar+CapableFullBarTheorems+DualEqWriteCapableGap+DualEqWriteCapableGapTheorems+DualEqWriteClosePath+DualEqWriteClosePathTheorems+DualEqWriteParity+DualEqWriteParityTheorems+OfficialRetire+OfficialRetireTheorems+OwnershipClaimed+OwnershipClaimedTheorems+PerformClaimed+PerformClaimedTheorems+StepContractFull+StepContractFullTheorems+SelfHostComplete+SelfHostCompleteTheorems+OfficialPathAlternate+OfficialPathAlternateTheorems+ProductPathOwnershipRegenerate+ProductPathOwnershipRegenerateTheorems+CapableWriteHcLoad+DualEqWriteLoad+CapableWriteHc+DualEqWriteApi+LlvmHold+LlvmHoldTheorems+CapableRegenerate+CapableRegenerateTheorems+FreestandingEmitLoad+FreestandingEmitLoadScaffold+LakeRetireInventory+HostPackageRoots+FreestandingEmit+ProductPathWriteHc+ProductPathWriteHcTheorems+CompilePathMult+CompilePathLinear+CompilePathTypes+CompilePathProgram+CompilePathGraph+CompilePathCompose+CompilePathPlan+CompilePathApply+CompilePathBody+CompilePathErasure+CompilePathExtract+ProductWireWriteTool+HostTerm+LlvmEmitPath+SubsetFront+FirstSurface+LinearSubsetEmit+TypesSubsetEmit+ProgramSubsetEmit+GraphSubsetEmit+ComposeSubsetEmit+ErasureSubsetEmit+ExtractSubsetEmit+MultSubsetEmit+MultSubsetRebuild+LinearSubsetRebuild+TypesSubsetRebuild+ProgramSubsetRebuild+GraphSubsetRebuild+ComposeSubsetRebuild+ErasureSubsetRebuild+ExtractSubsetRebuild+HostFront+LlvmMultText+HostFrontTheorems+HostCheck+HostGraph+LlvmLinearText+MultFsWriteTool+FrontMultPackage+SubsetPackageJoin+HostGraphTheorems+LlvmTypesText+MultFsDeepen+HostPackageWrite+HostPackageWriteTheorems+LlvmProgramText+LlvmGraphText+LlvmComposeText+SelfApplyFs+SelfApplyFsTheorems+InventoryClose+ProductPathBars+InventoryCloseTheorems+ProductPath+ProductPathTheorems+DualResidual+DualResidualTheorems+ProbeWire+SelfHostBody+ProbeWireTheorems+SelfHostBodyTheorems+SpecProof+SpecProofTheorems")
    && hostImportGraphLoadOkImportEdges

/-- Without-Lake keeps host Lake bootstrap honesty.
    Greppable: hostImportGraphWithoutLakeKeepsHostLake,
    HOST-IMPORT-GRAPH-WITHOUT-LAKE. -/
def hostImportGraphWithoutLakeKeepsHostLake : Bool :=
  hostImportGraphWithoutLakeFinished
    && stillUsesLake
    && dependsOnLake
    && hostImportGraphHostElaboratorResidualRemains
    && !hostImportGraphHostFreeClaimed

/-- Structural ready for real Mult import graph surface.
    Greppable: hostImportGraphReady, HOST-IMPORT-GRAPH,
    SLAKE_HOST_IMPORT_GRAPH. -/
def hostImportGraphReady : Bool :=
  hostImportGraphFinishedClaimed
    && hostImportGraphLoadOk
    && hostImportGraphHostElaboratorResidualRemains
    && !hostImportGraphHostFreeClaimed
    && stillUsesLake
    && dependsOnLake
    && hostImportGraphStillUsesLake
    && hostImportGraphDependsOnLake
    && !hostImportGraphResidualFreeClaimed
    && !hostImportGraphProductSelfHostCompleteClaimed
    && !hostImportGraphProofCompleteClaimed
    && !hostImportGraphLlvmUnlocked
    && !hostImportGraphProvablyUnlocked
    && (stageId == "SLAKE_HOST_IMPORT_GRAPH_V0")
    && (hostId == "HOST-IMPORT-GRAPH")
    && (surfaceId == "HOST-IMPORT-GRAPH")
    && (surfaceAlias == "HOST-HOST-IMPORT-GRAPH")
    && (lakeExeName == "slake-host-import-graph")
    && (justRecipe == "host-import-graph")
    && (justRecipeWithoutLake == "host-import-graph-without-lake")
    && (prebuiltHostImportGraphRel
      == ".lake/build/bin/slake-host-import-graph")

/-- Without-Lake ready (structural + finished + keeps host Lake).
    Greppable: hostImportGraphWithoutLakeReady,
    HOST-IMPORT-GRAPH-WITHOUT-LAKE. -/
def hostImportGraphWithoutLakeReady : Bool :=
  hostImportGraphReady
    && hostImportGraphWithoutLakeFinished
    && hostImportGraphWithoutLakeKeepsHostLake
    && (justRecipeWithoutLake == "host-import-graph-without-lake")
    && (prebuiltHostImportGraphRel
      == ".lake/build/bin/slake-host-import-graph")
end SystemsLean.HostImportGraph
