# SPDX-License-Identifier: Unlicense
# Host presence token specs slice. Joined via specs.nix. Sub-1-KLOC.
# No bash, no Python.
{
  hostSpecsTipPath1 = [
    {
      # Freestanding product path readiness (after HOST-INVENTORY-CLOSE).
      # Fail-closed pins: residual free / complete / unlock claims stay false.
      # Structural compose pins: readiness must fold inventoryCloseReady + unit
      # path + program path + emit path + join unit + join program + self-host
      # unit + self-host program + matrix unit + matrix program + surface
      # (name tokens alone can survive if dropped).
      # Long-file peel: path bar defs live in ProductPathBars; theorems + smoke
      # live in ProductPathTheorems (same namespace).
      rel = "src/systems/SystemsLean/ProductPath.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_PRODUCT_PATH_V0"
        "HOST-PRODUCT-PATH"
        "SELF-HOST-PRODUCT-PATH"
        "SLAKE_SELF_HOST_PRODUCT_PATH_CLOSE_V0"
        "HOST-PRODUCT-PATH-CLOSE"
        "SELF-HOST-PRODUCT-PATH-CLOSE"
        "SELF-HOST"
        "productPathReady"
        "productPathSurfaceOk"
        "freestandingUnitProductPathReady"
        "freestandingProgramProductPathReady"
        "freestandingEmitProductPathReady"
        "freestandingJoinProductPathReady"
        "freestandingJoinUnitProductPathReady"
        "freestandingJoinProgramProductPathReady"
        "freestandingSelfHostProductPathReady"
        "freestandingSelfHostUnitProductPathReady"
        "freestandingSelfHostProgramProductPathReady"
        "freestandingMatrixUnitProductPathReady"
        "freestandingMatrixProgramProductPathReady"
        "freestandingProductPathReady"
        "productPathDoesNotComplete"
        "productPathDoesNotMeanResidualFree"
        "productPathCloseReady"
        "productPathLadderClosedOk"
        "productPathCloseSurfaceOk"
        "productPathCloseDoesNotMeanResidualFree"
        "productPathFurtherAliasTheaterHeld"
        "productPathCloseOk"
        "structural product path ladder closed"
        "residualFreeClaimed"
        "productSelfHostCompleteClaimed"
        "productPathOk"
        "SystemsLean.ProductPath"
        "ProductPathBars"
        "ProductPathTheorems"
        "import SystemsLean.ProductPathBars"
        "PRODUCT-PATH-SMOKE"
        "HOST-PRODUCT-PATH-SMOKE"
        "PRODUCT-PATH-CLOSE-SMOKE"
        "HOST-PRODUCT-PATH-CLOSE-SMOKE"
        "HOST-INVENTORY-CLOSE"
        "HOST-SELF-APPLY-FS"
        "HOST-COMPILE-PATH"
        "HOST-KERNEL-EMIT"
        "HOST-JOIN-MAP"
        "HOST-SELF-HOST"
        "HOST-SURFACE-MATRIX"
        "SLAKE_SELF_HOST_V0"
        "SLAKE_SURFACE_MATRIX_V0"
        "SURFACE-MATRIX"
        "inventoryCloseReady"
        "unitCompileReady"
        "programCompileReady"
        "extractOkFs"
        "lowerEmitCompose"
        "lowerProgramKernel"
        "emitPlanPathReady"
        "emitApplyPathReady"
        "emitBodyPathReady"
        "emitKernelReady"
        "freestandingBodyPathReady"
        "joinUnitCompileReady"
        "joinProgramCompileReady"
        "selfHostUnitReady"
        "selfHostProgramReady"
        "matrixUnitReady"
        "matrixProgramReady"
        "RUNTIME-FS"
        "EMIT-BOUNDARY"
        "EMIT_BODY_V0"
        "HOST-EMIT-SSOT"
        "HOST-EMIT-MULT"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "freestandingProductSelfHostComplete"
        "llvmUnlocked"
        "provablyUnlocked"
        "import SystemsLean.InventoryClose"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.LlvmHold"
        "src/systems/self-host.md"
        "src/systems/host-partial-inventory.md"
        "src/systems/SystemsLean/ProductPath.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not full LLVM backend"
        # Claim pins (presence fail-closed without Lake): defs on parent.
        "def residualFreeClaimed : Bool := false"
        "def productSelfHostCompleteClaimed : Bool := true"
        # Structural compose pins: readiness must fold inventory close + paths.
        "InventoryClose.inventoryCloseReady"
        "freestandingUnitProductPathReady"
        "freestandingProgramProductPathReady"
        "freestandingEmitProductPathReady"
        "freestandingJoinProductPathReady"
        "freestandingJoinProgramProductPathReady"
        "freestandingSelfHostProductPathReady"
        "freestandingSelfHostProgramProductPathReady"
        "freestandingMatrixUnitProductPathReady"
        "freestandingMatrixProgramProductPathReady"
        "&& productPathSurfaceOk"
        "&& !residualFreeClaimed"
        "&& productSelfHostCompleteClaimed"
        "&& SelfApplyFs.freestandingProductSelfHostComplete"
                # Close compose pins: ladder close folds productPathReady + surface
        # (&& -prefixed so presence fails if conjuncts drop from def body while
        # bare def names remain).
        "productPathReady"
        "&& productPathCloseSurfaceOk"
        "&& productPathFurtherAliasTheaterHeld"
        "KernelEmit.lowerEmitCompose"
        "KernelProgram.lowerProgramKernel"
        "KernelEmit.emitPlanPathReady"
        "PRODUCT-PATH-THEOREM"
        "HOST-PRODUCT-PATH-THEOREM"
        "productPathReady_true"
        "productPathCloseReady_true"
        "residualFreeClaimed_false"
        "productPathFurtherAliasTheaterHeld_true"
        "KernelEmit.emitApplyPathReady"
        "KernelEmit.emitBodyPathReady"
        "KernelEmit.emitKernelReady"
        "SelfApplyFs.freestandingBodyPathReady"
      ];
      anyGroups = [
        [
          "productPathSurfaceOk"
          "freestandingUnitProductPathReady"
          "freestandingProgramProductPathReady"
          "freestandingEmitProductPathReady"
          "freestandingJoinProductPathReady"
          "freestandingJoinProgramProductPathReady"
          "freestandingSelfHostProductPathReady"
          "freestandingSelfHostProgramProductPathReady"
          "freestandingMatrixUnitProductPathReady"
          "freestandingMatrixProgramProductPathReady"
          "productPathReady"
          "productPathCloseReady"
          "productPathLadderClosedOk"
        ]
      ];
    }
    {
      # ProductPathBars: freestanding path bar assembly peel (same namespace).
      rel = "src/systems/SystemsLean/ProductPathBars.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "ProductPathBars"
        "SystemsLean.ProductPathBars"
        "def freestandingUnitProductPathReady : Bool :="
        "def freestandingProgramProductPathReady : Bool :="
        "def freestandingEmitProductPathReady : Bool :="
        "def freestandingJoinProductPathReady : Bool :="
        "def freestandingJoinUnitProductPathReady : Bool :="
        "def freestandingJoinProgramProductPathReady : Bool :="
        "def freestandingSelfHostProductPathReady : Bool :="
        "def freestandingSelfHostUnitProductPathReady : Bool :="
        "def freestandingSelfHostProgramProductPathReady : Bool :="
        "def freestandingMatrixUnitProductPathReady : Bool :="
        "def freestandingMatrixProgramProductPathReady : Bool :="
        "def freestandingProductPathReady : Bool :="
        "CompilePath.unitCompileReady HostCompose.empty"
        "KernelEmit.unmintedEmitCompose"
        "KernelEmit.lowerEmitCompose"
        "KernelProgram.lowerProgramKernel"
        "JoinMap.joinUnitCompileReady HostCompose.empty"
        "SelfHost.selfHostUnitReady HostCompose.empty"
        "SurfaceMatrix.matrixUnitReady HostCompose.empty"
        "SelfApplyFs.freestandingBodyPathReady"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # ProductPathTheorems: PRODUCT-PATH-THEOREM + smoke peel (same namespace).
      rel = "src/systems/SystemsLean/ProductPathTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "ProductPathTheorems"
        "SystemsLean.ProductPathTheorems"
        "import SystemsLean.ProductPath"
        "PRODUCT-PATH-THEOREM"
        "HOST-PRODUCT-PATH-THEOREM"
        "PRODUCT-PATH-SMOKE"
        "HOST-PRODUCT-PATH-SMOKE"
        "PRODUCT-PATH-CLOSE-SMOKE"
        "HOST-PRODUCT-PATH-CLOSE-SMOKE"
        "example"
        "productPathReady_true"
        "productPathCloseReady_true"
        "residualFreeClaimed_false"
        "productPathFurtherAliasTheaterHeld_true"
        "productPathDoesNotMeanResidualFree_true"
        "theorem productPathReady_true"
        "theorem productPathCloseReady_true"
        "theorem residualFreeClaimed_false"
        "theorem productPathFurtherAliasTheaterHeld_true"
        "example : residualFreeClaimed = false"
        "example : productSelfHostCompleteClaimed = true"
        "example : productPathReady = true"
        "example : productPathDoesNotComplete = true"
        "example : productPathDoesNotMeanResidualFree = true"
        "example : freestandingUnitProductPathReady = true"
        "example : freestandingProgramProductPathReady = true"
        "example : freestandingEmitProductPathReady = true"
        "example : freestandingJoinProductPathReady = true"
        "example : freestandingJoinProgramProductPathReady = true"
        "example : freestandingSelfHostProductPathReady = true"
        "example : freestandingSelfHostProgramProductPathReady = true"
        "example : freestandingMatrixUnitProductPathReady = true"
        "example : freestandingMatrixProgramProductPathReady = true"
        "example : productPathLadderClosedOk = true"
        "example : productPathCloseReady = true"
        "example : productPathCloseDoesNotMeanResidualFree = true"
        "example : productPathFurtherAliasTheaterHeld = true"
        "CompilePath.unitCompileReady HostCompose.empty"
        "KernelEmit.unmintedEmitCompose"
        "KernelEmit.lowerEmitCompose"
        "KernelProgram.lowerProgramKernel"
        "CompilePath.programCompileReady IrProgram.empty"
        "KernelEmit.emitPlanPathReady"
        "KernelEmit.emitApplyPathReady"
        "KernelEmit.emitBodyPathReady"
        "KernelEmit.emitKernelReady"
        "SelfApplyFs.freestandingBodyPathReady"
        "JoinMap.joinUnitCompileReady HostCompose.empty"
        "JoinMap.joinProgramCompileReady IrProgram.empty"
        "SelfHost.selfHostUnitReady HostCompose.empty"
        "SelfHost.selfHostProgramReady IrProgram.empty"
        "SurfaceMatrix.matrixUnitReady HostCompose.empty"
        "SurfaceMatrix.matrixProgramReady IrProgram.empty"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
  ];
}
