# SPDX-License-Identifier: Unlicense
# JoinMap + SelfHost + SurfaceMatrix + self-host.md cold acceptance cluster.
# HOST-JOIN-MAP / HOST-SELF-HOST / HOST-SURFACE-MATRIX + SELF-HOST acceptance prose.
# Cold slice (not dual-pin tip, not SelfApplyFs). Imported by ./specs.nix thin join. No bash.
{
hostSpecsJoinSurface = [
    {
      # HOST-JOIN-MAP (P4): dual / JOIN honesty into compile-path readiness.
      # JOIN-ALG-USE: host use pins (not dual-path cite alone) for six duals.
      # Theorems + smoke peeled to JoinMapTheorems (same namespace).
      rel = "src/systems/SystemsLean/JoinMap.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_JOIN_MAP_V0"
        "HOST-JOIN-MAP"
        "JOIN-MAP"
        "JOIN-ALG"
        "JOIN-ALG-USE"
        "ConsumeToken"
        "ErasedIndex"
        "UnrestrictedShare"
        "FailClosedGrade"
        "FAIL-CLOSED-UNKNOWN-GRADE"
        "LinearPairSwap"
        "RuntimeExtract"
        "RUNTIME-FS"
        "joinAlgContractOk"
        "joinAlgUseOk"
        "joinDualCiteOk"
        "consumeTokenHostUseOk"
        "erasedIndexHostUseOk"
        "unrestrictedShareHostUseOk"
        "failClosedGradeHostUseOk"
        "linearPairSwapHostUseOk"
        "runtimeExtractHostUseOk"
        "joinUnitCompileReady"
        "joinProgramCompileReady"
        "joinCompileReady"
        "SystemsLean.JoinMap"
        "JoinMapTheorems"
        "JOIN-MAP-SMOKE"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED"
        "HOST-COMPILE-PATH"
        "LINEAR-EXACT-ONCE"
        "MULT-OMEGA"
        "src/idris2/examples/ConsumeToken.idr"
        "src/lean4/examples/ConsumeToken.lean"
        "src/idris2/examples/ErasedIndex.idr"
        "src/lean4/examples/ErasedIndex.lean"
        "src/idris2/examples/UnrestrictedShare.idr"
        "src/lean4/examples/UnrestrictedShare.lean"
        "src/idris2/examples/FailClosedGrade.idr"
        "src/lean4/examples/FailClosedGrade.lean"
        "src/idris2/examples/LinearPairSwap.idr"
        "src/lean4/examples/LinearPairSwap.lean"
        "src/idris2/examples/RuntimeExtract.idr"
        "src/lean4/examples/RuntimeExtract.lean"
        "JOIN-MAP-THEOREM"
        "HOST-JOIN-MAP-THEOREM"
      ];
      anyGroups = [
        [
          "verdictOf"
          "joinLinearCiteOk"
        ]
      ];
    }
    {
      # JoinMapTheorems: JOIN-MAP-THEOREM + JOIN-MAP-SMOKE peel (same namespace).
      rel = "src/systems/SystemsLean/JoinMapTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "JoinMapTheorems"
        "SystemsLean.JoinMapTheorems"
        "import SystemsLean.JoinMap"
        "JOIN-MAP-THEOREM"
        "HOST-JOIN-MAP-THEOREM"
        "JOIN-MAP-SMOKE"
        "example"
        "joinUnitCompileReady_empty_true"
        "joinProgramCompileReady_empty_false"
        "joinAlgContractOk_true"
        "joinAlgUseOk_true"
        "joinUnitCompileReady_eq"
        "joinProgramCompileReady_eq"
        "joinUnitCompileReady_mult1_unminted_false"
        "joinUnitCompileReady_mult1_minted_true"
        "joinProgramCompileReady_single_value"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem joinUnitCompileReady_empty_true"
        "theorem joinProgramCompileReady_empty_false"
        "theorem joinAlgContractOk_true"
        "theorem joinAlgUseOk_true"
        "theorem joinUnitCompileReady_eq"
        "theorem joinProgramCompileReady_eq"
        "theorem joinUnitCompileReady_mult1_unminted_false"
        "theorem joinUnitCompileReady_mult1_minted_true"
        "theorem joinProgramCompileReady_single_value"
        "failClosedGradeHostUseOk_true"
        "failClosedGrade_host_use_implies_mult_unknown_reject"
        "dualFormalMapFailClosedEdge"
        "theorem failClosedGradeHostUseOk_true"
        "theorem failClosedGrade_host_use_implies_mult_unknown_reject"
        "runtimeExtractHostUseOk_true"
        "runtimeExtract_host_use_implies_unknown_runtime_reject"
        "dualFormalMapRuntimeExtractEdge"
        "theorem runtimeExtractHostUseOk_true"
        "theorem runtimeExtract_host_use_implies_unknown_runtime_reject"
      ];
      anyGroups = [];
    }
    {
      # HOST-SELF-HOST (P5): self-host direction readiness from join map + surface.
      # Theorems + smoke live in SelfHostTheorems (same namespace; long-file split).
      rel = "src/systems/SystemsLean/SelfHost.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_V0"
        "HOST-SELF-HOST"
        "SELF-HOST"
        "hostSurfaceOk"
        "selfHostUnitReady"
        "selfHostProgramReady"
        "selfHostReady"
        "SystemsLean.SelfHost"
        "SelfHostTheorems"
        "SELF-HOST-SMOKE"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED"
        "HOST-JOIN-MAP"
        "SLAKE_JOIN_MAP_V0"
        "HOST-COMPILE-PATH"
        "SLAKE_COMPILE_PATH_V1"
        "src/systems/SystemsLean.lean"
        "src/systems/SystemsLean/SelfHost.lean"
        "SELF-HOST-THEOREM"
        "HOST-SELF-HOST-THEOREM"
        "selfHostUnitReady_empty_true"
        "selfHostProgramReady_empty_false"
        "hostSurfaceOk_true"
      ];
      anyGroups = [
        [
          "verdictOf"
          "packageRootPath"
        ]
      ];
    }
    {
      # SelfHostTheorems: SELF-HOST-THEOREM + SELF-HOST-SMOKE long-file split
      # (same namespace).
      rel = "src/systems/SystemsLean/SelfHostTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SelfHostTheorems"
        "SystemsLean.SelfHostTheorems"
        "import SystemsLean.SelfHost"
        "SELF-HOST-THEOREM"
        "HOST-SELF-HOST-THEOREM"
        "SELF-HOST-SMOKE"
        "example"
        "selfHostUnitReady_empty_true"
        "selfHostProgramReady_empty_false"
        "hostSurfaceOk_true"
        "selfHostUnitReady_mult1_unminted_false"
        "selfHostUnitReady_mult1_minted_true"
        "selfHostProgramReady_single_value"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem selfHostUnitReady_empty_true"
        "theorem selfHostProgramReady_empty_false"
        "theorem hostSurfaceOk_true"
      ];
      anyGroups = [];
    }
    {
      # HOST-SURFACE-MATRIX (P7): progressive superset surface inventory + gate.
      # Theorems + smoke peeled to SurfaceMatrixTheorems (same namespace).
      rel = "src/systems/SystemsLean/SurfaceMatrix.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SURFACE_MATRIX_V0"
        "HOST-SURFACE-MATRIX"
        "SURFACE-MATRIX"
        "matrixSurfaceOk"
        "matrixUnitReady"
        "matrixProgramReady"
        "matrixReady"
        "SystemsLean.SurfaceMatrix"
        "SurfaceMatrixTheorems"
        "SURFACE-MATRIX-SMOKE"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED"
        "HOST-SELF-HOST"
        "SLAKE_SELF_HOST_V0"
        "HOST-JOIN-MAP"
        "HOST-COMPILE-PATH"
        "present-partial"
        "open"
        "ConsumeToken"
        "ErasedIndex"
        "UnrestrictedShare"
        "FailClosedGrade"
        "LinearPairSwap"
        "RuntimeExtract"
        "rowDualFormalMap"
        "dualFormalMapPartialOk"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "src/idris2/examples/ConsumeToken.idr"
        "src/lean4/examples/ConsumeToken.lean"
        "src/idris2/examples/ErasedIndex.idr"
        "src/lean4/examples/ErasedIndex.lean"
        "src/idris2/examples/UnrestrictedShare.idr"
        "src/lean4/examples/UnrestrictedShare.lean"
        "src/idris2/examples/FailClosedGrade.idr"
        "src/lean4/examples/FailClosedGrade.lean"
        "src/idris2/examples/LinearPairSwap.idr"
        "src/lean4/examples/LinearPairSwap.lean"
        "src/idris2/examples/RuntimeExtract.idr"
        "src/lean4/examples/RuntimeExtract.lean"
        "src/systems/surface-matrix.md"
        "src/systems/SystemsLean/SurfaceMatrix.lean"
        "SURFACE-MATRIX-THEOREM"
        "HOST-SURFACE-MATRIX-THEOREM"
      ];
      anyGroups = [
        [
          "verdictOf"
          "dualCiteOk"
        ]
      ];
    }
    {
      # SurfaceMatrixTheorems: SURFACE-MATRIX-THEOREM + SURFACE-MATRIX-SMOKE peel (same namespace).
      rel = "src/systems/SystemsLean/SurfaceMatrixTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SurfaceMatrixTheorems"
        "SystemsLean.SurfaceMatrixTheorems"
        "import SystemsLean.SurfaceMatrix"
        "SURFACE-MATRIX-THEOREM"
        "HOST-SURFACE-MATRIX-THEOREM"
        "SURFACE-MATRIX-SMOKE"
        "example"
        "matrixUnitReady_empty_true"
        "matrixProgramReady_empty_false"
        "matrixSurfaceOk_true"
        "matrixUnitReady_mult1_unminted_false"
        "matrixUnitReady_mult1_minted_true"
        "matrixProgramReady_single_value"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem matrixUnitReady_empty_true"
        "theorem matrixProgramReady_empty_false"
        "theorem matrixSurfaceOk_true"
        "theorem matrixUnitReady_mult1_unminted_false"
        "theorem matrixUnitReady_mult1_minted_true"
        "theorem matrixProgramReady_single_value"
      ];
      anyGroups = [];
    }
    {
      # SELF-HOST acceptance prose (SH0..SH5 partial + SH5 freestanding deepen + SH6 hold).
      rel = "src/systems/self-host.md";
      all = [
        "SELF-HOST"
        "SELF-HOST-ACCEPTANCE"
        "SLAKE_SELF_HOST_KERNEL_MULT_V0"
        "SELF-HOST-KERNEL-MULT"
        "SLAKE_SELF_HOST_EMIT_MULT_V0"
        "HOST-EMIT-MULT"
        "SLAKE_SELF_HOST_PARITY_MULT_V0"
        "HOST-PARITY-MULT"
        "SELF-HOST-PARITY-MULT"
        "SLAKE_SELF_HOST_KERNEL_LINEAR_V0"
        "SELF-HOST-KERNEL-LINEAR"
        "HOST-KERNEL-LINEAR"
        "SLAKE_SELF_HOST_PARITY_LINEAR_V0"
        "HOST-PARITY-LINEAR"
        "SELF-HOST-PARITY-LINEAR"
        "SLAKE_SELF_HOST_KERNEL_TYPES_V0"
        "SELF-HOST-KERNEL-TYPES"
        "HOST-KERNEL-TYPES"
        "SLAKE_SELF_HOST_PARITY_TYPES_V0"
        "HOST-PARITY-TYPES"
        "SELF-HOST-PARITY-TYPES"
        "SLAKE_SELF_HOST_KERNEL_PROGRAM_V0"
        "SELF-HOST-KERNEL-PROGRAM"
        "HOST-KERNEL-PROGRAM"
        "SLAKE_SELF_HOST_PARITY_PROGRAM_V0"
        "HOST-PARITY-PROGRAM"
        "SELF-HOST-PARITY-PROGRAM"
        "SLAKE_SELF_HOST_KERNEL_EMIT_V0"
        "SELF-HOST-KERNEL-EMIT"
        "HOST-KERNEL-EMIT"
        "SLAKE_SELF_HOST_PARITY_EMIT_V0"
        "HOST-PARITY-EMIT"
        "SELF-HOST-PARITY-EMIT"
        "SLAKE_SELF_HOST_SELF_APPLY_V0"
        "HOST-SELF-APPLY"
        "SELF-HOST-SELF-APPLY"
        "SLAKE_SELF_HOST_SELF_APPLY_FS_V0"
        "HOST-SELF-APPLY-FS"
        "SELF-HOST-SELF-APPLY-FS"
        "SLAKE_SELF_HOST_LLVM_HOLD_V0"
        "HOST-LLVM-HOLD"
        "SELF-HOST-LLVM-HOLD"
        "HOST-PROVABLY-HOLD"
        "SLAKE_SELF_HOST_INVENTORY_CLOSE_V0"
        "HOST-INVENTORY-CLOSE"
        "SELF-HOST-INVENTORY-CLOSE"
        "SLAKE_SELF_HOST_PRODUCT_PATH_V0"
        "HOST-PRODUCT-PATH"
        "SELF-HOST-PRODUCT-PATH"
        "SLAKE_SELF_HOST_PRODUCT_PATH_CLOSE_V0"
        "HOST-PRODUCT-PATH-CLOSE"
        "SELF-HOST-PRODUCT-PATH-CLOSE"
        "productPathCloseReady"
        "productPathLadderClosedOk"
        "SLAKE_SELF_HOST_DUAL_RESIDUAL_V0"
        "HOST-DUAL-RESIDUAL"
        "SELF-HOST-DUAL-RESIDUAL"
        "dualResidualReady"
        "hostElaboratorResidualRemains"
        "productResidualRemains"
        "SLAKE_SELF_HOST_PROBE_WIRE_V0"
        "HOST-PROBE-WIRE"
        "SELF-HOST-PROBE-WIRE"
        "probeWireReady"
        "behavioralProbeIsSmokeDebt"
        "product freestanding wire"
        "SLAKE_SELF_HOST_SPEC_PROOF_V0"
        "HOST-SPEC-PROOF"
        "SELF-HOST-SPEC-PROOF"
        "specProofReady"
        "specSurfaceStated"
        "proofCompleteClaimed"
        "proofs do not retire tests"
        "SLAKE_SELF_HOST_BODY_V0"
        "HOST-SELF-HOST-BODY"
        "SELF-HOST-BODY"
        "selfHostBodyReady"
        "defined freestanding compile step"
        "SLAKE_SELF_HOST_KERNEL_REBUILD_V0"
        "HOST-SELF-HOST-KERNEL-REBUILD"
        "SELF-HOST-KERNEL-REBUILD"
        "freestanding kernel rebuild evidence"
        "SLAKE_SELF_HOST_KERNEL_SELF_APPLY_V0"
        "HOST-SELF-HOST-KERNEL-SELF-APPLY"
        "SELF-HOST-KERNEL-SELF-APPLY"
        "product kernel self-application"
        "productKernelSelfApplyPartialReady"
        "SLAKE_SELF_HOST_PRODUCT_OUT_V0"
        "HOST-SELF-HOST-PRODUCT-OUT"
        "SELF-HOST-PRODUCT-OUT"
        "product Out kernel evidence"
        "productOutKernelEvidencePartialReady"
        "SLAKE_SELF_HOST_PRODUCT_PATH_BOOTSTRAP_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-BOOTSTRAP"
        "SELF-HOST-PRODUCT-PATH-BOOTSTRAP"
        "product path Lake bootstrap"
        "productPathHostLakeBootstrapRemains"
        "productPathHostLakeBootstrapPartialReady"
        "SLAKE_SELF_HOST_PRODUCT_WRITER_SURFACE_V0"
        "HOST-SELF-HOST-PRODUCT-WRITER-SURFACE"
        "SELF-HOST-PRODUCT-WRITER-SURFACE"
        "product writer surface"
        "productWriterSurfacePartialReady"
        "SLAKE_SELF_HOST_PRODUCT_WRITER_PATH_PLAN_V0"
        "HOST-SELF-HOST-PRODUCT-WRITER-PATH-PLAN"
        "SELF-HOST-PRODUCT-WRITER-PATH-PLAN"
        "product writer path plan"
        "productWriterPathPlanPartialReady"
        "WRITER-PATH-STEP-READ-SSOT"
        "WRITER-PATH-STEP-COMPOSE-PLAN-APPLY-BODY"
        "WRITER-PATH-STEP-WRITE-FREESTANDING-HC"
        "WRITER-PATH-STEP-INSTALL-OUT"
        "SLAKE_SELF_HOST_PRODUCT_WRITER_PATH_EXEC_V0"
        "HOST-SELF-HOST-PRODUCT-WRITER-PATH-EXEC"
        "SELF-HOST-PRODUCT-WRITER-PATH-EXEC"
        "product writer path execution"
        "productWriterPathExecutionPartialReady"
        "loadMultSsot"
        "renderHeader"
        "emitAtRoot"
        "IO.FS.writeFile"
        "build"
        "SLAKE_SELF_HOST_PRODUCT_PATH_OWNERSHIP_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-OWNERSHIP"
        "SELF-HOST-PRODUCT-PATH-OWNERSHIP"
        "product path ownership inputs"
        "productPathOwnershipInputsPartialReady"
        "productPathFreestandingOwnershipClaimed"
        "host_emit_mult.ssot.txt"
        "slake_freestanding.h"
        "slake_freestanding.c"
        "SLAKE_SELF_HOST_PRODUCT_PATH_PERFORM_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-PERFORM"
        "SELF-HOST-PRODUCT-PATH-PERFORM"
        "product path perform"
        "productPathPerformPartialReady"
        "productPathFreestandingPerformClaimed"
        "productPathPerformDependsOnLake"
        "productPathPerformInstallStepLakeFreeCapable"
        "productPathPerformInstallLakeFreeEntrypointClaimed"
        "FREESTANDING-PERFORM-GAP-READ-SSOT"
        "FREESTANDING-PERFORM-GAP-COMPOSE"
        "FREESTANDING-PERFORM-GAP-WRITE-HC"
        "SLAKE_SELF_HOST_PRODUCT_PATH_PERFORM_STEP_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-PERFORM-STEP"
        "SELF-HOST-PRODUCT-PATH-PERFORM-STEP"
        "product path perform step"
        "productPathPerformStepPartialReady"
        "install-freestanding-c-out"
        "SLAKE_SELF_HOST_PRODUCT_PATH_PERFORM_READ_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-PERFORM-READ"
        "SELF-HOST-PRODUCT-PATH-PERFORM-READ"
        "product path perform read"
        "productPathPerformReadPartialReady"
        "read-product-ssot"
        "slake-read-product-ssot"
        "ProductPathReadSsot"
        "SLAKE_SELF_HOST_PRODUCT_PATH_PERFORM_COMPOSE_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-PERFORM-COMPOSE"
        "SELF-HOST-PRODUCT-PATH-PERFORM-COMPOSE"
        "product path perform compose"
        "productPathPerformComposePartialReady"
        "compose-product-plan"
        "slake-compose-product-plan"
        "ProductPathComposePlan"
        "SLAKE_SELF_HOST_PRODUCT_PATH_PERFORM_WRITE_HC_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-PERFORM-WRITE-HC"
        "SELF-HOST-PRODUCT-PATH-PERFORM-WRITE-HC"
        "product path perform write"
        "productPathPerformWriteHcPartialReady"
        "write-freestanding-hc"
        "slake-write-freestanding-hc"
        "ProductPathWriteHc"
        "SLAKE_SELF_HOST_PRODUCT_PATH_FREESTANDING_CAPABLE_GAP_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-GAP"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-GAP"
        "product path freestanding capable gap"
        "productPathFreestandingCapablePartialReady"
        "regenerate-product-path"
        "freestanding-capable-gap"
        "slake-freestanding-capable-gap"
        "Capable"
        "SLAKE_SELF_HOST_PRODUCT_PATH_FREESTANDING_CAPABLE_STEP_CONTRACT_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-STEP-CONTRACT"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-STEP-CONTRACT"
        "product path freestanding capable step contract"
        "productPathFreestandingCapableStepContractPartialReady"
        "freestanding-capable-step-contract"
        "slake-freestanding-capable-step-contract"
        "CapableStepContract"
        "FREESTANDING-CAPABLE-STEP-CONTRACT-READ"
        "SLAKE_SELF_HOST_PRODUCT_PATH_FREESTANDING_CAPABLE_READ_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-READ"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-READ"
        "product path freestanding capable read"
        "productPathFreestandingCapableReadPartialReady"
        "freestanding-capable-read"
        "slake-freestanding-capable-read"
        "CapableRead"
        "freestandingCapableReadDualSsot"
        "SLAKE_SELF_HOST_PRODUCT_PATH_FREESTANDING_CAPABLE_COMPOSE_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-COMPOSE"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-COMPOSE"
        "product path freestanding capable compose"
        "productPathFreestandingCapableComposePartialReady"
        "freestanding-capable-compose"
        "slake-freestanding-capable-compose"
        "CapableCompose"
        "freestandingCapableComposePlanApplyBody"
        "SLAKE_SELF_HOST_PRODUCT_PATH_FREESTANDING_CAPABLE_WRITE_HC_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-WRITE-HC"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-WRITE-HC"
        "product path freestanding capable write"
        "productPathFreestandingCapableWriteHcPartialReady"
        "freestanding-capable-write-hc"
        "slake-freestanding-capable-write-hc"
        "CapableWriteHc"
        "freestandingCapableWriteFreestandingHc"
        "SLAKE_SELF_HOST_PRODUCT_PATH_FREESTANDING_CAPABLE_REGENERATE_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-REGENERATE"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-REGENERATE"
        "product path freestanding capable regenerate"
        "productPathFreestandingCapableRegeneratePartialReady"
        "freestanding-capable-regenerate"
        "slake-freestanding-capable-regenerate"
        "CapableRegenerate"
        "freestandingCapableOrderedRegenerate"
        "SLAKE_SELF_HOST_PRODUCT_PATH_FREESTANDING_CAPABLE_INSTALL_OUT_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-INSTALL-OUT"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-INSTALL-OUT"
        "product path freestanding capable install out"
        "productPathFreestandingCapableInstallOutPartialReady"
        "freestanding-capable-install-out"
        "slake-freestanding-capable-install-out"
        "InstallOut"
        "freestandingCapableInstallFreestandingOut"
        "SLAKE_SELF_HOST_PRODUCT_PATH_FREESTANDING_CAPABLE_FULL_BAR_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-FULL-BAR"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-FULL-BAR"
        "product path freestanding capable full bar"
        "productPathFreestandingCapableFullBarPartialReady"
        "freestanding-capable-full-bar"
        "slake-freestanding-capable-full-bar"
        "CapableFullBar"
        "FULL-BAR-REQ-OWNERSHIP-REGENERATE-WITHOUT-LAKE"
        "SLAKE_SELF_HOST_PRODUCT_PATH_OWNERSHIP_REGENERATE_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-OWNERSHIP-REGENERATE"
        "SELF-HOST-PRODUCT-PATH-OWNERSHIP-REGENERATE"
        "product path ownership regenerate"
        "productPathOwnershipRegeneratePartialReady"
        "ownership-regenerate"
        "ownership-regenerate-install-only"
        "ownership-regenerate-read-only"
        "slake-ownership-regenerate"
        "ProductPathOwnershipRegenerate"
        "OWNERSHIP-REGENERATE-INSTALL-LAKE-FREE"
        "OWNERSHIP-REGENERATE-READ-LAKE-FREE"
        "OWNERSHIP-REGENERATE-COMPOSE-LAKE-FREE"
        "OWNERSHIP-REGENERATE-WRITE-HC-LAKE-FREE"
        "OWNERSHIP-REGENERATE-LAKE-FREE-JOIN"
        "OWNERSHIP-REGENERATE-PRODUCT-PATH-AUTHORITY"
        "ownership-regenerate-compose-only"
        "ownership-regenerate-write-hc-only"
        "ownership-regenerate-lake-free"
        "ownership-regenerate-product-path-authority"
        "SLAKE_SELF_HOST_PRODUCT_PATH_PERFORM_EVIDENCE_V0"
        "HOST-SELF-HOST-PRODUCT-PATH-PERFORM-EVIDENCE"
        "SELF-HOST-PRODUCT-PATH-PERFORM-EVIDENCE"
        "product path freestanding perform evidence"
        "productPathFreestandingPerformEvidencePartialReady"
        "productPathFreestandingPerformEvidenceClaimed"
        "freestanding-perform-evidence"
        "freestanding-perform-evidence-measure"
        "slake-freestanding-perform-evidence"
        "PerformEvidence"
        "FREESTANDING-PERFORM-EVIDENCE"
        "SLAKE_PRODUCT_RESIDUAL_FREE_MEASURE_V0"
        "PRODUCT-RESIDUAL-FREE-MEASURE"
        "SELF-HOST-RESIDUAL-FREE-MEASURE"
        "Product residual free measurement"
        "residualFreeClaimed"
        "SLAKE_EMIT_FREESTANDING_C_V0"
        "product wire"
        "Host model"
        "not residual free"
        "Not PROVABLY"
      ];
    }
];
}
