# SPDX-License-Identifier: Unlicense
# Host presence specs slice (hostSpecsCompilePath). Joined by parent. Sub-1-KLOC.
# No bash, no Python.
{
  hostSpecsCompilePath3 = [
    {
      # Thin Lake main for slake-host-package-write (SKELETON).
      rel = "src/systems/SystemsLean/HostPackageWriteMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostPackageWriteMain"
        "slake-host-package-write"
        "HostPackageWriteMain"
        "SKELETON"
        "import SystemsLean.HostPackageWrite"
      ];
    }
    {
      # HOST-PACKAGE-ROOTS: A3 package load without Lake on measured step (S1).
      rel = "src/systems/SystemsLean/HostPackageRoots.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostPackageRoots"
        "HOST-PACKAGE-ROOTS"
        "SLAKE_HOST_PACKAGE_ROOTS"
        "SLAKE_HOST_PACKAGE_ROOTS_V0"
        "HOST-HOST-PACKAGE-ROOTS"
        "hostPackageRootsReady"
        "hostPackageRootsFinishedClaimed"
        "hostPackageRootsLoadOk"
        "hostPackageRootsWithoutLakeFinished"
        "hostPackageRootsWithoutLakeReady"
        "hostPackageRootsWithoutLakeKeepsHostLake"
        "justRecipeWithoutLake"
        "prebuiltHostPackageRootsRel"
        "host-package-roots-without-lake"
        "HOST-PACKAGE-ROOTS-WITHOUT-LAKE"
        "hostPackageRootsHostElaboratorResidualRemains"
        "hostPackageRootsPackageName"
        "hostPackageRootsLibraryRoot"
        "hostPackageRootsConfigRel"
        "hostPackageRootsLibraryDirRel"
        "hostPackageRootsModuleCountFloor"
        "loadPackageRoots"
        "runPackageRoots"
        "HOST-PACKAGE-ROOTS-SMOKE"
        "HOST-PACKAGE-ROOTS-THEOREM"
        "hostPackageRootsReady_true"
        "slake-host-package-roots"
        "just host-package-roots"
        "Package roots without Lake"
        "def hostPackageRootsWithoutLakeFinished : Bool := true"
        "def hostPackageRootsFinishedClaimed : Bool := true"
        "def hostPackageRootsHostElaboratorResidualRemains : Bool := true"
        "def hostPackageRootsHostFreeClaimed : Bool := false"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Host elaborator residual remains"
      ];
    }
    {
      # Thin Lake main for slake-host-package-roots (SKELETON).
      rel = "src/systems/SystemsLean/HostPackageRootsMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostPackageRootsMain"
        "slake-host-package-roots"
        "HostPackageRootsMain"
        "SKELETON"
        "import SystemsLean.HostPackageRoots"
      ];
    }
    {
      # HOST-IMPORT-GRAPH: A4 real Mult import graph without Lake (S2).
      rel = "src/systems/SystemsLean/HostImportGraph.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostImportGraph"
        "HOST-IMPORT-GRAPH"
        "SLAKE_HOST_IMPORT_GRAPH"
        "SLAKE_HOST_IMPORT_GRAPH_V0"
        "HOST-HOST-IMPORT-GRAPH"
        "hostImportGraphReady"
        "hostImportGraphFinishedClaimed"
        "hostImportGraphLoadOk"
        "hostImportGraphWithoutLakeFinished"
        "hostImportGraphWithoutLakeReady"
        "hostImportGraphWithoutLakeKeepsHostLake"
        "justRecipeWithoutLake"
        "prebuiltHostImportGraphRel"
        "host-import-graph-without-lake"
        "HOST-IMPORT-GRAPH-WITHOUT-LAKE"
        "hostImportGraphHostElaboratorResidualRemains"
        "hostImportGraphSeedModules"
        "hostImportGraphGoodMultSeed"
        "hostImportGraphGoodExpandSeed"
        "hostImportGraphExpandSliceName"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems+IrGraph+IrGraphTheorems+HostCompose+HostComposeTheorems+Erasure+ErasureTheorems+Extract+ExtractTheorems+CompilePath+KernelMult+KernelLinear+KernelTypes+KernelProgram+KernelMultTheorems+KernelLinearTheorems+KernelTypesTheorems+KernelProgramTheorems+JoinMap+JoinMapTheorems+SelfHost+SelfHostTheorems+SurfaceMatrix+SurfaceMatrixTheorems+EmitMultScaffold+EmitLinearScaffold+EmitTypesScaffold+EmitProgramScaffold+EmitGraphScaffold+EmitComposeScaffold+EmitPlanScaffold+EmitApplyScaffold+EmitBodyScaffold+EmitErasureScaffold+EmitExtractScaffold+EmitBannerScaffold+KernelSelfApply+KernelSelfApplyTheorems+EmitMult+EmitPlan+EmitApply+EmitBody+KernelEmit+KernelEmitTheorems+ParityMult+ParityMultTheorems+ParityLinear+ParityLinearTheorems+ParityTypes+ParityTypesTheorems+ParityProgram+ParityProgramTheorems+ParityEmit+ParityEmitTheorems+SelfApply+SelfApplyTheorems+EmitLinear+EmitTypes+EmitProgram+EmitGraph+EmitCompose+EmitErasure+EmitExtract+EmitBanner+ProductOutKernel+ProductOutKernelTheorems+BootstrapHonesty+BootstrapHonestyTheorems+ProductPathWriterSurface+ProductPathWriterSurfaceTheorems+ProductPathWriterPathPlan+ProductPathWriterPathPlanTheorems+ProductPathWriterPathExec+ProductPathWriterPathExecTheorems"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems"
        "Host library seed expand continue"
        "Host compose module expand"
        "Host program module expand"
        "Host module set expand"
        "hostImportGraphBadMissing"
        "hostImportGraphBadCycle"
        "loadMultImportGraph"
        "runImportGraph"
        "resolveImportGraph"
        "extractImports"
        "MISSING-IMPORT"
        "IMPORT-CYCLE"
        "HOST-IMPORT-GRAPH-SMOKE"
        "HOST-IMPORT-GRAPH-THEOREM"
        "hostImportGraphReady_true"
        "slake-host-import-graph"
        "just host-import-graph"
        "Real Mult import graph"
        "def hostImportGraphWithoutLakeFinished : Bool := true"
        "def hostImportGraphFinishedClaimed : Bool := true"
        "def hostImportGraphHostElaboratorResidualRemains : Bool := true"
        "def hostImportGraphHostFreeClaimed : Bool := false"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Host elaborator residual remains"
      ];
    }
    {
      # Thin Lake main for slake-host-import-graph (SKELETON).
      rel = "src/systems/SystemsLean/HostImportGraphMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostImportGraphMain"
        "slake-host-import-graph"
        "HostImportGraphMain"
        "SKELETON"
        "import SystemsLean.HostImportGraph"
      ];
    }
    {
      # HOST-MODULE-CHECK: A5 first real host module check without Lake (S3).
      rel = "src/systems/SystemsLean/HostModuleCheck.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostModuleCheck"
        "HOST-MODULE-CHECK"
        "SLAKE_HOST_MODULE_CHECK"
        "SLAKE_HOST_MODULE_CHECK_V0"
        "HOST-HOST-MODULE-CHECK"
        "hostModuleCheckReady"
        "hostModuleCheckFinishedClaimed"
        "hostModuleCheckLoadOk"
        "hostModuleCheckWithoutLakeFinished"
        "hostModuleCheckWithoutLakeReady"
        "hostModuleCheckWithoutLakeKeepsHostLake"
        "justRecipeWithoutLake"
        "prebuiltHostModuleCheckRel"
        "host-module-check-without-lake"
        "HOST-MODULE-CHECK-WITHOUT-LAKE"
        "hostModuleCheckHostElaboratorResidualRemains"
        "hostModuleCheckSeedModules"
        "hostModuleCheckExpandSliceName"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems+IrGraph+IrGraphTheorems+HostCompose+HostComposeTheorems+Erasure+ErasureTheorems+Extract+ExtractTheorems+CompilePath+KernelMult+KernelLinear+KernelTypes+KernelProgram+KernelMultTheorems+KernelLinearTheorems+KernelTypesTheorems+KernelProgramTheorems+JoinMap+JoinMapTheorems+SelfHost+SelfHostTheorems+SurfaceMatrix+SurfaceMatrixTheorems+EmitMultScaffold+EmitLinearScaffold+EmitTypesScaffold+EmitProgramScaffold+EmitGraphScaffold+EmitComposeScaffold+EmitPlanScaffold+EmitApplyScaffold+EmitBodyScaffold+EmitErasureScaffold+EmitExtractScaffold+EmitBannerScaffold+KernelSelfApply+KernelSelfApplyTheorems+EmitMult+EmitPlan+EmitApply+EmitBody+KernelEmit+KernelEmitTheorems+ParityMult+ParityMultTheorems+ParityLinear+ParityLinearTheorems+ParityTypes+ParityTypesTheorems+ParityProgram+ParityProgramTheorems+ParityEmit+ParityEmitTheorems+SelfApply+SelfApplyTheorems+EmitLinear+EmitTypes+EmitProgram+EmitGraph+EmitCompose+EmitErasure+EmitExtract+EmitBanner+ProductOutKernel+ProductOutKernelTheorems+BootstrapHonesty+BootstrapHonestyTheorems+ProductPathWriterSurface+ProductPathWriterSurfaceTheorems+ProductPathWriterPathPlan+ProductPathWriterPathPlanTheorems+ProductPathWriterPathExec+ProductPathWriterPathExecTheorems"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems"
        "Host library seed expand continue"
        "Host compose module expand"
        "Host program module expand"
        "Host module set expand"
        "hostModuleCheckGoodMult"
        "hostModuleCheckGoodMultTheorems"
        "hostModuleCheckGoodLinear"
        "hostModuleCheckGoodTypes"
        "hostModuleCheckGoodIrProgram"
        "hostModuleCheckGoodIrGraph"
        "hostModuleCheckGoodHostCompose"
        "hostModuleCheckBadMissingInductive"
        "hostModuleCheckBadMissingNamespace"
        "hostModuleCheckBadEmpty"
        "hostModuleCheckBadMissingTheorem"
        "loadMultModuleCheck"
        "runModuleCheck"
        "checkRealModule"
        "extractKeyDecls"
        "PARTIAL-STRUCTURAL"
        "MISSING-DECL"
        "MISSING-NAMESPACE"
        "EMPTY-MODULE"
        "HostModuleCheckTheorems"
        "HostModuleCheckFixtures"
        "slake-host-module-check"
        "just host-module-check"
        "First real host module check"
        "def hostModuleCheckWithoutLakeFinished : Bool := true"
        "def hostModuleCheckFinishedClaimed : Bool := true"
        "def hostModuleCheckHostElaboratorResidualRemains : Bool := true"
        "def hostModuleCheckHostFreeClaimed : Bool := false"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Host elaborator residual remains"
      ];
    }
    {
      # HOST-MODULE-CHECK fixture texts long-file split companion.
      rel = "src/systems/SystemsLean/HostModuleCheckFixtures.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostModuleCheckFixtures"
        "hostModuleCheckGoodMultText"
        "hostModuleCheckGoodIrProgramText"
        "hostModuleCheckGoodIrGraphText"
        "hostModuleCheckGoodHostComposeText"
        "hostModuleCheckBadMissingInductiveText"
        "HostModuleCheckFixtures"
        "Host library seed expand continue"
        "Host compose module expand"
        "Host program module expand"
        "PARTIAL-STRUCTURAL"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # HOST-MODULE-CHECK-THEOREM / SMOKE long-file split companion.
      rel = "src/systems/SystemsLean/HostModuleCheckTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostModuleCheckTheorems"
        "HOST-MODULE-CHECK-THEOREM"
        "HOST-MODULE-CHECK-SMOKE"
        "hostModuleCheckReady_true"
        "hostModuleCheckLoadOk_true"
        "hostModuleCheckGoodLinear_accept"
        "hostModuleCheckGoodTypes_accept"
        "hostModuleCheckGoodIrProgram_accept"
        "hostModuleCheckGoodIrGraph_accept"
        "hostModuleCheckGoodHostCompose_accept"
        "Host library seed expand continue"
        "Host compose module expand"
        "Host program module expand"
        "Host module set expand"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems+IrGraph+IrGraphTheorems+HostCompose+HostComposeTheorems+Erasure+ErasureTheorems+Extract+ExtractTheorems+CompilePath+KernelMult+KernelLinear+KernelTypes+KernelProgram+KernelMultTheorems+KernelLinearTheorems+KernelTypesTheorems+KernelProgramTheorems+JoinMap+JoinMapTheorems+SelfHost+SelfHostTheorems+SurfaceMatrix+SurfaceMatrixTheorems+EmitMultScaffold+EmitLinearScaffold+EmitTypesScaffold+EmitProgramScaffold+EmitGraphScaffold+EmitComposeScaffold+EmitPlanScaffold+EmitApplyScaffold+EmitBodyScaffold+EmitErasureScaffold+EmitExtractScaffold+EmitBannerScaffold+KernelSelfApply+KernelSelfApplyTheorems+EmitMult+EmitPlan+EmitApply+EmitBody+KernelEmit+KernelEmitTheorems+ParityMult+ParityMultTheorems+ParityLinear+ParityLinearTheorems+ParityTypes+ParityTypesTheorems+ParityProgram+ParityProgramTheorems+ParityEmit+ParityEmitTheorems+SelfApply+SelfApplyTheorems+EmitLinear+EmitTypes+EmitProgram+EmitGraph+EmitCompose+EmitErasure+EmitExtract+EmitBanner+ProductOutKernel+ProductOutKernelTheorems+BootstrapHonesty+BootstrapHonestyTheorems+ProductPathWriterSurface+ProductPathWriterSurfaceTheorems+ProductPathWriterPathPlan+ProductPathWriterPathPlanTheorems+ProductPathWriterPathExec+ProductPathWriterPathExecTheorems"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems"
        "import SystemsLean.HostModuleCheck"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # Thin Lake main for slake-host-module-check (SKELETON).
      rel = "src/systems/SystemsLean/HostModuleCheckMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostModuleCheckMain"
        "slake-host-module-check"
        "HostModuleCheckMain"
        "SKELETON"
        "import SystemsLean.HostModuleCheck"
      ];
    }
    {
      # HOST-RESIDUAL-SHRINK: peer elaborator step 10 partial host residual inventory.
      rel = "src/systems/SystemsLean/HostResidualShrink.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostResidualShrink"
        "HOST-RESIDUAL-SHRINK"
        "SLAKE_HOST_RESIDUAL_SHRINK"
        "SLAKE_HOST_RESIDUAL_SHRINK_V0"
        "HOST-HOST-RESIDUAL-SHRINK"
        "hostResidualShrinkReady"
        "hostResidualShrinkFinishedClaimed"
        "hostResidualPartialShrinkClaimed"
        "hostDevelopMeasuredPathsLakeFreeEvidence"
        "hostResidualShrinkHostElaborateRemains"
        "hostResidualShrinkHostFreeClaimed"
        "hostResidualShrinkKeepsHostResidual"
        "hostResidualShrinkDoesNotMeanHostFree"
        "hostResidualShrinkFreeIsNotLakeGone"
        "justRecipeHostResidualShrink"
        "host-residual-shrink"
        "hostResidualShrinkBootstrapPrebuildRemains"
        "hostResidualShrinkFullHostElaborateRemains"
        "hostResidualShrinkDiagnosticLakeRecipesRemain"
        "measuredHostFoundationToolsCleanBootstrap"
        "host-foundation-tools-clean-bootstrap"
        "measuredHostFoundationToolsInventory"
        "fragment-check+graph+package-write+package-roots+import-graph+module-check"
        "hostFoundationToolsBinLinkWithoutLakeDualOk"
        "justRecipeHostFoundationToolsCleanBootstrap"
        "Foundation tools without Lake bootstrap"
        "Host tool build expand"
        "measuredHostToolBuildExpand"
        "measuredHostDevelopToolsCleanBootstrap"
        "host-develop-tools-clean-bootstrap"
        "measuredHostDevelopToolsInventory"
        "host-front+subset-front+front-mult-package+mult-subset-rebuild+first-surface"
        "hostDevelopToolsBinLinkWithoutLakeDualOk"
        "measuredHostLakeFreeHostFront"
        "host-front-without-lake"
        "hostFrontWithoutLakeDualOk"
        "measuredHostLakeFreeSubsetFront"
        "subset-front-without-lake"
        "subsetFrontWithoutLakeDualOk"
        "measuredHostLakeFreeFrontMultPackage"
        "front-mult-package-without-lake"
        "frontMultPackageWithoutLakeDualOk"
        "measuredHostLakeFreeMultSubsetRebuild"
        "mult-subset-rebuild-without-lake"
        "multSubsetRebuildWithoutLakeDualOk"
        "measuredHostLakeFreeFirstSurface"
        "first-surface-without-lake"
        "firstSurfaceWithoutLakeDualOk"
        "measuredHostToolInventoryCleanBootstrapOwned"
        "fragment-check+graph+package-write+package-roots+import-graph+module-check+host-front+subset-front+front-mult-package+mult-subset-rebuild+first-surface"
        "measuredHostToolInventoryDayToDayCandidatesRemain"
        "empty"
        "measuredHostToolInventoryClaimDiagnosticLakeOnly"
        "claim-capable-perform-self-host+llvm-text-writers"
        "measuredHostLakeFreeFragmentCheck"
        "measuredHostLakeFreeGraph"
        "measuredHostLakeFreePackageWrite"
        "measuredHostLakeFreePackageRoots"
        "hostPackageRootsLoadDualOk"
        "measuredHostLakeFreeImportGraph"
        "hostImportGraphMultSeedDualOk"
        "measuredHostLakeFreeModuleCheck"
        "hostModuleCheckMultSeedDualOk"
        "measuredHostRealModuleSeedUnits"
        "hostImportGraphExpandSeedDualOk"
        "hostModuleCheckExpandSeedDualOk"
        "measuredHostTheoremCorpusExpand"
        "hostModuleCheckTheoremCorpusExpandDualOk"
        "measuredHostTheoremCorpusRequiredCounts"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems+IrGraph+IrGraphTheorems+HostCompose+HostComposeTheorems+Erasure+ErasureTheorems+Extract+ExtractTheorems+CompilePath+KernelMult+KernelLinear+KernelTypes+KernelProgram+KernelMultTheorems+KernelLinearTheorems+KernelTypesTheorems+KernelProgramTheorems+JoinMap+JoinMapTheorems+SelfHost+SelfHostTheorems+SurfaceMatrix+SurfaceMatrixTheorems+EmitMultScaffold+EmitLinearScaffold+EmitTypesScaffold+EmitProgramScaffold+EmitGraphScaffold+EmitComposeScaffold+EmitPlanScaffold+EmitApplyScaffold+EmitBodyScaffold+EmitErasureScaffold+EmitExtractScaffold+EmitBannerScaffold+KernelSelfApply+KernelSelfApplyTheorems+EmitMult+EmitPlan+EmitApply+EmitBody+KernelEmit+KernelEmitTheorems+ParityMult+ParityMultTheorems+ParityLinear+ParityLinearTheorems+ParityTypes+ParityTypesTheorems+ParityProgram+ParityProgramTheorems+ParityEmit+ParityEmitTheorems+SelfApply+SelfApplyTheorems+EmitLinear+EmitTypes+EmitProgram+EmitGraph+EmitCompose+EmitErasure+EmitExtract+EmitBanner+ProductOutKernel+ProductOutKernelTheorems+BootstrapHonesty+BootstrapHonestyTheorems+ProductPathWriterSurface+ProductPathWriterSurfaceTheorems+ProductPathWriterPathPlan+ProductPathWriterPathPlanTheorems+ProductPathWriterPathExec+ProductPathWriterPathExecTheorems"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems+IrProgram+IrProgramTheorems"
        "Mult+MultTheorems+Linear+LinearTheorems+Types+TypesTheorems"
        "Host library seed expand continue"
        "Host compose module expand"
        "Host program module expand"
        "Host module set expand"
        "host-fragment-check-without-lake"
        "host-graph-without-lake"
        "host-package-write-without-lake"
        "host-package-roots-without-lake"
        "host-import-graph-without-lake"
        "host-module-check-without-lake"
        "host-foundation-tools-clean-bootstrap"
        "host-develop-tools-clean-bootstrap"
        "host-front-without-lake"
        "subset-front-without-lake"
        "front-mult-package-without-lake"
        "mult-subset-rebuild-without-lake"
        "first-surface-without-lake"
        "HOST-PACKAGE-ROOTS"
        "HOST-IMPORT-GRAPH"
        "HOST-MODULE-CHECK"
        "HOST-RESIDUAL-SHRINK-SMOKE"
        "HOST-RESIDUAL-SHRINK-THEOREM"
        "hostResidualShrinkReady_true"
        "hostResidualShrinkFinishedClaimed_true"
        "hostResidualPartialShrinkClaimed_true"
        "hostDevelopMeasuredPathsLakeFreeEvidence_true"
        "hostResidualShrinkHostElaborateRemains_true"
        "hostResidualShrinkHostFreeClaimed_false"
        "hostResidualShrinkKeepsHostResidual_true"
        "hostResidualShrinkDoesNotMeanHostFree_true"
        "hostResidualShrinkFreeIsNotLakeGone_true"
        "hostResidualShrink_claims_false"
        "measuredHostLakeFree_recipes_eq"
        "hostPackageRootsLoadDualOk_true"
        "hostImportGraphMultSeedDualOk_true"
        "hostModuleCheckMultSeedDualOk_true"
        "hostImportGraphExpandSeedDualOk_true"
        "hostModuleCheckExpandSeedDualOk_true"
        "hostModuleCheckTheoremCorpusExpandDualOk_true"
        "measuredHostTheoremCorpusExpand_eq"
        "measuredHostRealModuleSeedUnits_eq"
        "hostResidualShrinkBootstrapPrebuildRemains_false"
        "hostFoundationToolsBinLinkWithoutLakeDualOk_true"
        "measuredHostFoundationToolsCleanBootstrap_eq"
        "hostDevelopToolsBinLinkWithoutLakeDualOk_true"
        "hostFrontWithoutLakeDualOk_true"
        "subsetFrontWithoutLakeDualOk_true"
        "frontMultPackageWithoutLakeDualOk_true"
        "multSubsetRebuildWithoutLakeDualOk_true"
        "measuredHostLakeFreeSubsetFront_eq"
        "measuredHostLakeFreeFrontMultPackage_eq"
        "measuredHostLakeFreeMultSubsetRebuild_eq"
        "measuredHostToolBuildExpand_eq"
        "theorem hostResidualShrinkReady_true"
        "def hostResidualShrinkFinishedClaimed : Bool := true"
        "def hostResidualPartialShrinkClaimed : Bool := true"
        "def hostResidualShrinkHostElaborateRemains : Bool := true"
        "def hostResidualShrinkHostFreeClaimed : Bool := false"
        "def hostResidualShrinkBootstrapPrebuildRemains : Bool := false"
        "def hostFoundationToolsBinLinkWithoutLakeDualOk : Bool := true"
        "def hostDevelopToolsBinLinkWithoutLakeDualOk : Bool := true"
        "def hostFrontWithoutLakeDualOk : Bool := true"
        "def subsetFrontWithoutLakeDualOk : Bool := true"
        "def frontMultPackageWithoutLakeDualOk : Bool := true"
        "def multSubsetRebuildWithoutLakeDualOk : Bool := true"
        "def hostPackageRootsLoadDualOk : Bool := true"
        "def hostImportGraphMultSeedDualOk : Bool := true"
        "def hostModuleCheckMultSeedDualOk : Bool := true"
        "def hostImportGraphExpandSeedDualOk : Bool := true"
        "def hostModuleCheckExpandSeedDualOk : Bool := true"
        "doc/dev/research/host-residual-shrink-2026-08-02.md"
        "DualResidual"
        "LakeRetireInventory"
        "free true != Lake gone"
        "UNIT_SURFACE"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "Not freestanding residual free"
        "Not freestanding emit"
        "Not PROVABLY"
        "Not llvm unlock"
        "Host elaborator residual remains"
        "Partial shrink only"
      ];
    }
    {
      # HOST-LLVM-EMIT-PATH: first residual design + measured stub (llvm stays locked).
      rel = "src/systems/SystemsLean/LlvmEmitPath.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.LlvmEmitPath"
        "HOST-LLVM-EMIT-PATH"
        "SLAKE_LLVM_EMIT_PATH"
        "SLAKE_LLVM_EMIT_PATH_V0"
        "HOST-HOST-LLVM-EMIT-PATH"
        "llvmEmitPathReady"
        "llvmEmitPathFinishedClaimed"
        "llvmEmitPathDesignLanded"
        "llvmEmitPathStubLanded"
        "llvmEmitPathKeepsLlvmLocked"
        "llvmEmitPathDoesNotUnlockLlvm"
        "llvmEmitPathLlvmUnlocked"
        "llvmEmitPathLocalUnlockFalse"
        "justRecipeLlvmEmitPath"
        "llvm-emit-path"
        "out/llvm-ir"
        "MEASURED-STUB"
        "designNotePath"
        "llvm-ir-emit-path-2026-08-02"
        "LlvmHold"
        "llvmUnlocked"
        "HOST-LLVM-HOLD"
        "HOST-LLVM-EMIT-PATH-SMOKE"
        "HOST-LLVM-EMIT-PATH-THEOREM"
        "llvmEmitPathReady_true"
        "llvmEmitPathFinishedClaimed_true"
        "llvmEmitPathDesignLanded_true"
        "llvmEmitPathStubLanded_true"
        "llvmEmitPathLlvmUnlocked_false"
        "llvmEmitPathKeepsLlvmLocked_true"
        "llvmEmitPathDoesNotUnlockLlvm_true"
        "llvmEmitPath_claims_false"
        "theorem llvmEmitPathReady_true"
        "def llvmEmitPathFinishedClaimed : Bool := true"
        "def llvmEmitPathDesignLanded : Bool := true"
        "def llvmEmitPathStubLanded : Bool := true"
        "def llvmEmitPathLlvmUnlocked : Bool := false"
        "doc/dev/research/llvm-ir-emit-path-2026-08-02.md"
        "UNIT_SURFACE"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "Not freestanding residual free"
        "Not freestanding emit"
        "Not PROVABLY re-open"
        "Not llvm unlock"
        "Host elaborator residual remains"
        "Design + measured stub only"
      ];
    }
    {
      # HOST-LLVM-MULT-TEXT: Mult unit LLVM IR fragment from Lean Mult SSOT
      # (generator-owned out/llvm-ir/slake_mult.ll; llvm stays locked).
      rel = "src/systems/SystemsLean/LlvmMultText.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.LlvmMultText"
        "HOST-LLVM-MULT-TEXT"
        "SLAKE_LLVM_MULT_TEXT"
        "SLAKE_LLVM_MULT_TEXT_V0"
        "HOST-HOST-LLVM-MULT-TEXT"
        "llvmMultTextReady"
        "llvmMultTextFinishedClaimed"
        "llvmMultTextPackageOk"
        "llvmMultTextWroteExpected"
        "llvmMultTextKeepsLlvmLocked"
        "llvmMultTextDoesNotUnlockLlvm"
        "llvmMultTextLlvmUnlocked"
        "llvmMultTextLocalUnlockFalse"
        "justRecipeLlvmMultText"
        "llvm-mult-text"
        "out/llvm-ir"
        "slake_mult.ll"
        "multIrPackage"
        "llvmMultTextWrite"
        "IO.FS.writeFile"
        "Mult"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "LlvmHold"
        "llvmUnlocked"
        "LlvmEmitPath"
        "HOST-LLVM-EMIT-PATH"
        "HOST-LLVM-MULT-TEXT-SMOKE"
        "HOST-LLVM-MULT-TEXT-THEOREM"
        "llvmMultTextReady_true"
        "llvmMultTextFinishedClaimed_true"
        "llvmMultTextLlvmUnlocked_false"
        "llvmMultTextKeepsLlvmLocked_true"
        "llvmMultTextDoesNotUnlockLlvm_true"
        "llvmMultText_claims_false"
        "theorem llvmMultTextReady_true"
        "def llvmMultTextFinishedClaimed : Bool := true"
        "def llvmMultTextLlvmUnlocked : Bool := false"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not freestanding emit"
        "Not PROVABLY re-open"
        "Not llvm unlock"
        "Host elaborator residual remains"
        "Mult IR text only"
      ];
    }
    {
      # HOST-LLVM-LINEAR-TEXT: Linear unit LLVM IR fragment from Lean Linear SSOT
      # (generator-owned out/llvm-ir/slake_linear.ll; llvm stays locked).
      rel = "src/systems/SystemsLean/LlvmLinearText.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.LlvmLinearText"
        "HOST-LLVM-LINEAR-TEXT"
        "SLAKE_LLVM_LINEAR_TEXT"
        "SLAKE_LLVM_LINEAR_TEXT_V0"
        "HOST-HOST-LLVM-LINEAR-TEXT"
        "llvmLinearTextReady"
        "llvmLinearTextFinishedClaimed"
        "llvmLinearTextPackageOk"
        "llvmLinearTextWroteExpected"
        "llvmLinearTextKeepsLlvmLocked"
        "llvmLinearTextDoesNotUnlockLlvm"
        "llvmLinearTextLlvmUnlocked"
        "llvmLinearTextLocalUnlockFalse"
        "justRecipeLlvmLinearText"
        "llvm-linear-text"
        "out/llvm-ir"
        "slake_linear.ll"
        "linearIrPackage"
        "llvmLinearTextWrite"
        "IO.FS.writeFile"
        "Linear"
        "LINEAR-EXACT-ONCE"
        "LINEAR-AXIOMS-REMAIN"
        "shareNat"
        "polyId"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "LlvmHold"
        "llvmUnlocked"
        "LlvmEmitPath"
        "LlvmMultText"
        "HOST-LLVM-EMIT-PATH"
        "HOST-LLVM-MULT-TEXT"
        "HOST-LLVM-LINEAR-TEXT-SMOKE"
        "HOST-LLVM-LINEAR-TEXT-THEOREM"
        "llvmLinearTextReady_true"
        "llvmLinearTextFinishedClaimed_true"
        "llvmLinearTextLlvmUnlocked_false"
        "llvmLinearTextKeepsLlvmLocked_true"
        "llvmLinearTextDoesNotUnlockLlvm_true"
        "llvmLinearText_claims_false"
        "theorem llvmLinearTextReady_true"
        "def llvmLinearTextFinishedClaimed : Bool := true"
        "def llvmLinearTextLlvmUnlocked : Bool := false"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not freestanding emit"
        "Not PROVABLY re-open"
        "Not llvm unlock"
        "Host elaborator residual remains"
        "Linear IR text only"
      ];
    }
    {
      # HOST-LLVM-TYPES-TEXT: Types unit LLVM IR fragment from Lean Types SSOT
      # (generator-owned out/llvm-ir/slake_types.ll; llvm stays locked).
      rel = "src/systems/SystemsLean/LlvmTypesText.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.LlvmTypesText"
        "HOST-LLVM-TYPES-TEXT"
        "SLAKE_LLVM_TYPES_TEXT"
        "SLAKE_LLVM_TYPES_TEXT_V0"
        "HOST-HOST-LLVM-TYPES-TEXT"
        "llvmTypesTextReady"
        "llvmTypesTextFinishedClaimed"
        "llvmTypesTextPackageOk"
        "llvmTypesTextWroteExpected"
        "llvmTypesTextKeepsLlvmLocked"
        "llvmTypesTextDoesNotUnlockLlvm"
        "llvmTypesTextLlvmUnlocked"
        "llvmTypesTextLocalUnlockFalse"
        "justRecipeLlvmTypesText"
        "llvm-types-text"
        "out/llvm-ir"
        "slake_types.ll"
        "typesIrPackage"
        "llvmTypesTextWrite"
        "IO.FS.writeFile"
        "Types"
        "TYPED_IR_V0"
        "FAIL-CLOSED-UNKNOWN-KIND"
        "VALUE"
        "LINEAR"
        "ERASED"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "kindMultOk"
        "isValidKindTag"
        "LlvmHold"
        "llvmUnlocked"
        "LlvmEmitPath"
        "LlvmMultText"
        "LlvmLinearText"
        "HOST-LLVM-EMIT-PATH"
        "HOST-LLVM-MULT-TEXT"
        "HOST-LLVM-LINEAR-TEXT"
        "HOST-LLVM-TYPES-TEXT-SMOKE"
        "HOST-LLVM-TYPES-TEXT-THEOREM"
        "llvmTypesTextReady_true"
        "llvmTypesTextFinishedClaimed_true"
        "llvmTypesTextLlvmUnlocked_false"
        "llvmTypesTextKeepsLlvmLocked_true"
        "llvmTypesTextDoesNotUnlockLlvm_true"
        "llvmTypesText_claims_false"
        "theorem llvmTypesTextReady_true"
        "def llvmTypesTextFinishedClaimed : Bool := true"
        "def llvmTypesTextLlvmUnlocked : Bool := false"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not freestanding emit"
        "Not PROVABLY re-open"
        "Not llvm unlock"
        "Host elaborator residual remains"
        "Types IR text only"
      ];
    }
    {
      # HOST-LLVM-PROGRAM-TEXT: ordered IR program unit LLVM IR fragment from
      # Lean Program SSOT (generator-owned out/llvm-ir/slake_program.ll; llvm stays locked).
      rel = "src/systems/SystemsLean/LlvmProgramText.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.LlvmProgramText"
        "HOST-LLVM-PROGRAM-TEXT"
        "SLAKE_LLVM_PROGRAM_TEXT"
        "SLAKE_LLVM_PROGRAM_TEXT_V0"
        "HOST-HOST-LLVM-PROGRAM-TEXT"
        "llvmProgramTextReady"
        "llvmProgramTextFinishedClaimed"
        "llvmProgramTextPackageOk"
        "llvmProgramTextWroteExpected"
        "llvmProgramTextKeepsLlvmLocked"
        "llvmProgramTextDoesNotUnlockLlvm"
        "llvmProgramTextLlvmUnlocked"
        "llvmProgramTextLocalUnlockFalse"
        "justRecipeLlvmProgramText"
        "llvm-program-text"
        "out/llvm-ir"
        "slake_program.ll"
        "programIrPackage"
        "llvmProgramTextWrite"
        "IO.FS.writeFile"
        "IrProgram"
        "ORDERED-IR-PROGRAM"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "SLAKE_IR_PROGRAM_CAP"
        "programCap"
        "push"
        "isWellTyped"
        "checkFailClosed"
        "LlvmHold"
        "llvmUnlocked"
        "LlvmEmitPath"
        "LlvmMultText"
        "LlvmLinearText"
        "LlvmTypesText"
        "HOST-LLVM-EMIT-PATH"
        "HOST-LLVM-MULT-TEXT"
        "HOST-LLVM-LINEAR-TEXT"
        "HOST-LLVM-TYPES-TEXT"
        "HOST-LLVM-PROGRAM-TEXT-SMOKE"
        "HOST-LLVM-PROGRAM-TEXT-THEOREM"
        "llvmProgramTextReady_true"
        "llvmProgramTextFinishedClaimed_true"
        "llvmProgramTextLlvmUnlocked_false"
        "llvmProgramTextKeepsLlvmLocked_true"
        "llvmProgramTextDoesNotUnlockLlvm_true"
        "llvmProgramText_claims_false"
        "theorem llvmProgramTextReady_true"
        "def llvmProgramTextFinishedClaimed : Bool := true"
        "def llvmProgramTextLlvmUnlocked : Bool := false"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not freestanding emit"
        "Not PROVABLY re-open"
        "Not llvm unlock"
        "Host elaborator residual remains"
        "Program IR text only"
        "Not CFG"
        "Not SSA"
      ];
    }
    {
      # HOST-LLVM-GRAPH-TEXT: IR graph unit LLVM IR fragment from
      # Lean Graph SSOT (generator-owned out/llvm-ir/slake_graph.ll; llvm stays locked).
      rel = "src/systems/SystemsLean/LlvmGraphText.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.LlvmGraphText"
        "HOST-LLVM-GRAPH-TEXT"
        "SLAKE_LLVM_GRAPH_TEXT"
        "SLAKE_LLVM_GRAPH_TEXT_V0"
        "HOST-HOST-LLVM-GRAPH-TEXT"
        "llvmGraphTextReady"
        "llvmGraphTextFinishedClaimed"
        "llvmGraphTextPackageOk"
        "llvmGraphTextWroteExpected"
        "llvmGraphTextKeepsLlvmLocked"
        "llvmGraphTextDoesNotUnlockLlvm"
        "llvmGraphTextLlvmUnlocked"
        "llvmGraphTextLocalUnlockFalse"
        "justRecipeLlvmGraphText"
        "llvm-graph-text"
        "out/llvm-ir"
        "slake_graph.ll"
        "graphIrPackage"
        "llvmGraphTextWrite"
        "IO.FS.writeFile"
        "IrGraph"
        "EMPTY-GRAPH-OK"
        "SLAKE_IR_EDGE_MAX"
        "edgeMax"
        "addEdge"
        "pushNode"
        "isWellTyped"
        "checkFailClosed"
        "edgesSound"
        "LlvmHold"
        "llvmUnlocked"
        "LlvmEmitPath"
        "LlvmMultText"
        "LlvmLinearText"
        "LlvmTypesText"
        "LlvmProgramText"
        "HOST-LLVM-EMIT-PATH"
        "HOST-LLVM-MULT-TEXT"
        "HOST-LLVM-LINEAR-TEXT"
        "HOST-LLVM-TYPES-TEXT"
        "HOST-LLVM-PROGRAM-TEXT"
        "HOST-LLVM-GRAPH-TEXT-SMOKE"
        "HOST-LLVM-GRAPH-TEXT-THEOREM"
        "llvmGraphTextReady_true"
        "llvmGraphTextFinishedClaimed_true"
        "llvmGraphTextLlvmUnlocked_false"
        "llvmGraphTextKeepsLlvmLocked_true"
        "llvmGraphTextDoesNotUnlockLlvm_true"
        "llvmGraphText_claims_false"
        "theorem llvmGraphTextReady_true"
        "def llvmGraphTextFinishedClaimed : Bool := true"
        "def llvmGraphTextLlvmUnlocked : Bool := false"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not freestanding emit"
        "Not PROVABLY re-open"
        "Not llvm unlock"
        "Host elaborator residual remains"
        "Graph IR text only"
        "Not full CFG"
        "Not SSA"
      ];
    }
    {
      # LAKE-RETIRE-INVENTORY: M6 inventory + phase 2 product path Lake retired.
      rel = "src/systems/SystemsLean/LakeRetireInventory.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.LakeRetireInventory"
        "LAKE-RETIRE-INVENTORY"
        "SLAKE_LAKE_RETIRE_INVENTORY"
        "SLAKE_LAKE_RETIRE_INVENTORY_V0"
        "HOST-LAKE-RETIRE-INVENTORY"
        "lakeRetireInventoryReady"
        "lakeRetireInventoryFinishedClaimed"
        "productPathMeasuredStepsLakeFreeEvidence"
        "lakeRetireProductPathLakeRetired"
        "lakeRetireKeepsProductStillUsesLake"
        "justRecipeLakeRetireInventory"
        "lake-retire-inventory"
        "lakeRetireHostElaborateRemains"
        "lakeRetireBootstrapPrebuildRemains"
        "lakeRetireDiagnosticLakeRecipesRemain"
        "measuredLakeFreeJustBuild"
        "measuredLakeFreeProductWireWrite"
        "measuredLakeFreeCapableRegenerate"
        "measuredLakeFreeMultRebuild"
        "measuredLakeFreeMultWrite"
        "measuredLakeFreeMultDeepen"
        "measuredLakeFreeSubsetPackageJoin"
        "stillUsesLake"
        "dependsOnLake"
        "LAKE-RETIRE-INVENTORY-SMOKE"
        "LAKE-RETIRE-INVENTORY-THEOREM"
        "lakeRetireInventoryReady_true"
        "lakeRetireInventoryFinishedClaimed_true"
        "productPathMeasuredStepsLakeFreeEvidence_true"
        "lakeRetireProductPathLakeRetired_true"
        "lakeRetireKeepsProductStillUsesLake_true"
        "lakeRetireHostElaborateRemains_true"
        "lakeRetireInventoryDoesNotRetireLake_true"
        "lakeRetireInventoryDoesNotMeanResidualFree_true"
        "lakeRetireFreeIsNotLakeGone_true"
        "lakeRetireInventory_claims_false"
        "theorem lakeRetireInventoryReady_true"
        "def lakeRetireInventoryFinishedClaimed : Bool := true"
        "def stillUsesLake : Bool := false"
        "def dependsOnLake : Bool := false"
        "def lakeRetireHostElaborateRemains : Bool := true"
        "product-wire-freestanding-write"
        "freestanding-capable-regenerate-without-lake"
        "mult-subset-rebuild-without-lake"
        "mult-subset-freestanding-write"
        "mult-subset-freestanding-deepen"
        "subset-packages-rebuild-join-without-lake"
        "free true != Lake gone"
        "UNIT_SURFACE"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "RUNTIME-FS"
        "Not freestanding residual free"
        "Not freestanding emit"
        "Not PROVABLY"
      ];
    }
    {
      # COMPILE-PATH-LINEAR: Linear unit e2e fixture (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathLinear.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathLinear"
        "COMPILE-PATH-LINEAR"
        "LINEAR-FIXTURE"
        "HOST-EMIT-LINEAR"
        "linearFixtureCompilePathReady"
        "linearFixtureProgramReady"
        "linearFixtureComposeReady"
        "linearFixtureEmitPathOk"
        "linearFixtureMintConsumeOk"
        "lowerLinearFixtureProgram"
        "lowerLinearFixtureCompose"
        "COMPILE-PATH-LINEAR-SMOKE"
        "COMPILE-PATH-LINEAR-THEOREM"
        "linearFixtureCompilePathReady_true"
        "linearFixtureDoesNotMeanResidualFree_true"
        "linearFixture_claims_false"
        "LINEAR-EXACT-ONCE"
        "ConsumeToken"
        "theorem linearFixtureCompilePathReady_true"
        "theorem linearFixtureDoesNotMeanResidualFree_true"
        "theorem linearFixture_claims_false"
        "import SystemsLean.CompilePath"
        "import SystemsLean.EmitLinear"
      ];
    }
    {
      # COMPILE-PATH-TYPES: Types unit e2e fixture (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathTypes.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathTypes"
        "COMPILE-PATH-TYPES"
        "TYPES-FIXTURE"
        "HOST-EMIT-TYPES"
        "typesFixtureCompilePathReady"
        "typesFixtureProgramReady"
        "typesFixtureComposeReady"
        "typesFixtureEmitPathOk"
        "typesFixtureKindMultOk"
        "lowerTypesFixtureProgram"
        "lowerTypesFixtureCompose"
        "COMPILE-PATH-TYPES-SMOKE"
        "COMPILE-PATH-TYPES-THEOREM"
        "typesFixtureCompilePathReady_true"
        "typesFixtureDoesNotMeanResidualFree_true"
        "typesFixture_claims_false"
        "TYPED_IR_V0"
        "theorem typesFixtureCompilePathReady_true"
        "theorem typesFixtureDoesNotMeanResidualFree_true"
        "theorem typesFixture_claims_false"
        "import SystemsLean.CompilePath"
        "import SystemsLean.EmitTypes"
      ];
    }
    {
      # COMPILE-PATH-PROGRAM: Program unit e2e fixture (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathProgram.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathProgram"
        "COMPILE-PATH-PROGRAM"
        "PROGRAM-FIXTURE"
        "HOST-EMIT-PROGRAM"
        "programFixtureCompilePathReady"
        "programFixtureProgramReady"
        "programFixtureComposeReady"
        "programFixtureEmitPathOk"
        "programFixtureFoldOk"
        "lowerProgramFixtureProgram"
        "lowerProgramFixtureCompose"
        "COMPILE-PATH-PROGRAM-SMOKE"
        "COMPILE-PATH-PROGRAM-THEOREM"
        "programFixtureCompilePathReady_true"
        "programFixtureDoesNotMeanResidualFree_true"
        "programFixture_claims_false"
        "theorem programFixtureCompilePathReady_true"
        "theorem programFixtureDoesNotMeanResidualFree_true"
        "theorem programFixture_claims_false"
        "import SystemsLean.CompilePath"
        "import SystemsLean.EmitProgram"
      ];
    }
    {
      # COMPILE-PATH-EXTRACT: extract RUNTIME-FS gate (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathExtract.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathExtract"
        "COMPILE-PATH-EXTRACT"
        "EXTRACT-RUNTIME-FS"
        "fixtureExtractGateOk"
        "multFixtureExtractGateOk"
        "programFixtureExtractGateOk"
        "multFixtureExtractRawReject"
        "programFixtureExtractRawReject"
        "extractRuntimeFsGateReady"
        "extractRuntimeFsDoesNotMeanResidualFree"
        "COMPILE-PATH-EXTRACT-SMOKE"
        "COMPILE-PATH-EXTRACT-THEOREM"
        "extractRuntimeFsGateReady_true"
        "extractRuntimeFsDoesNotMeanResidualFree_true"
        "extractRuntimeFs_claims_false"
        "multFixtureExtractGateOk_true"
        "programFixtureExtractGateOk_true"
        "extractClaimOk_fs_eq_extractOkFs"
        "theorem multFixtureExtractGateOk_true"
        "theorem programFixtureExtractGateOk_true"
        "theorem extractRuntimeFsGateReady_true"
        "theorem extractRuntimeFsDoesNotMeanResidualFree_true"
        "theorem extractRuntimeFs_claims_false"
        "theorem extractClaimOk_fs_eq_extractOkFs"
        "import SystemsLean.CompilePath"
        "import SystemsLean.CompilePathMult"
        "import SystemsLean.CompilePathProgram"
      ];
    }
    {
      # COMPILE-PATH-GRAPH: Graph unit e2e fixture (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathGraph.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathGraph"
        "COMPILE-PATH-GRAPH"
        "GRAPH-FIXTURE"
        "HOST-EMIT-GRAPH"
        "graphFixtureCompilePathReady"
        "graphFixtureProgramReady"
        "graphFixtureGraphReady"
        "graphFixtureComposeReady"
        "graphFixtureEmitPathOk"
        "graphFixtureEdgesOk"
        "graphFixtureChainEdgesOk"
        "lowerGraphFixtureProgram"
        "lowerGraphFixtureGraph"
        "lowerGraphFixtureCompose"
        "COMPILE-PATH-GRAPH-SMOKE"
        "COMPILE-PATH-GRAPH-THEOREM"
        "graphFixtureCompilePathReady_true"
        "graphFixtureDoesNotMeanResidualFree_true"
        "graphFixture_claims_false"
        "graphFixtureMintId_eq"
        "IR-GRAPH-EDGES"
        "EMPTY-GRAPH-OK"
        "theorem graphFixtureCompilePathReady_true"
        "theorem graphFixtureDoesNotMeanResidualFree_true"
        "theorem graphFixture_claims_false"
        "theorem graphFixtureGraphReady_true"
        "theorem graphFixtureEdgesOk_true"
        "theorem graphFixtureMintId_eq"
        "import SystemsLean.CompilePath"
        "import SystemsLean.EmitGraph"
      ];
    }
    {
      # COMPILE-PATH-COMPOSE: Compose unit e2e fixture (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathCompose.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathCompose"
        "COMPILE-PATH-COMPOSE"
        "COMPOSE-FIXTURE"
        "HOST-EMIT-COMPOSE"
        "composeFixtureCompilePathReady"
        "composeFixtureProgramReady"
        "composeFixtureComposeReady"
        "composeFixtureEmitPathOk"
        "composeFixtureEdgesOk"
        "composeFixtureChainEdgesOk"
        "composeFixtureMintConsumeOk"
        "lowerComposeFixtureProgram"
        "lowerComposeFixtureCompose"
        "COMPILE-PATH-COMPOSE-SMOKE"
        "COMPILE-PATH-COMPOSE-THEOREM"
        "composeFixtureCompilePathReady_true"
        "composeFixtureDoesNotMeanResidualFree_true"
        "composeFixture_claims_false"
        "composeFixtureMintId_eq"
        "ConsumeToken"
        "LINEAR-EXACT-ONCE"
        "theorem composeFixtureCompilePathReady_true"
        "theorem composeFixtureDoesNotMeanResidualFree_true"
        "theorem composeFixture_claims_false"
        "theorem composeFixtureComposeReady_true"
        "theorem composeFixtureEdgesOk_true"
        "theorem composeFixtureMintConsumeOk_true"
        "theorem composeFixtureMintId_eq"
        "import SystemsLean.CompilePath"
        "import SystemsLean.EmitCompose"
      ];
    }
    {
      # COMPILE-PATH-ERASURE: Erasure unit e2e fixture (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathErasure.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathErasure"
        "COMPILE-PATH-ERASURE"
        "ERASURE-FIXTURE"
        "HOST-EMIT-ERASURE"
        "erasureFixtureCompilePathReady"
        "erasureFixtureProgramReady"
        "erasureFixtureComposeReady"
        "erasureFixtureEmitPathOk"
        "erasureFixtureMarkedOk"
        "lowerErasureFixtureProgram"
        "lowerErasureFixtureCompose"
        "COMPILE-PATH-ERASURE-SMOKE"
        "COMPILE-PATH-ERASURE-THEOREM"
        "erasureFixtureCompilePathReady_true"
        "erasureFixtureDoesNotMeanResidualFree_true"
        "erasureFixture_claims_false"
        "ERASE-RULE-MULT-0"
        "ERASE-NO-RUNTIME"
        "theorem erasureFixtureCompilePathReady_true"
        "theorem erasureFixtureDoesNotMeanResidualFree_true"
        "theorem erasureFixture_claims_false"
        "theorem erasureFixtureComposeReady_true"
        "theorem erasureFixtureMarkedOk_true"
        "import SystemsLean.CompilePath"
        "import SystemsLean.EmitErasure"
      ];
    }
    {
      # COMPILE-PATH-PLAN: Plan unit e2e fixture (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathPlan.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathPlan"
        "COMPILE-PATH-PLAN"
        "PLAN-FIXTURE"
        "HOST-EMIT-PLAN"
        "planFixtureCompilePathReady"
        "planFixtureProgramReady"
        "planFixtureComposeReady"
        "planFixtureEmitPathOk"
        "planFixturePlanOk"
        "lowerPlanFixtureProgram"
        "lowerPlanFixtureCompose"
        "COMPILE-PATH-PLAN-SMOKE"
        "COMPILE-PATH-PLAN-THEOREM"
        "planFixtureCompilePathReady_true"
        "planFixtureDoesNotMeanResidualFree_true"
        "planFixture_claims_false"
        "planFixtureMintId_eq"
        "planFromCompose"
        "planOk"
        "theorem planFixtureCompilePathReady_true"
        "theorem planFixtureDoesNotMeanResidualFree_true"
        "theorem planFixture_claims_false"
        "theorem planFixtureComposeReady_true"
        "theorem planFixturePlanOk_true"
        "theorem planFixtureMintId_eq"
        "import SystemsLean.CompilePath"
        "import SystemsLean.EmitPlan"
      ];
    }
    {
      # COMPILE-PATH-APPLY: Apply unit e2e fixture (peeled from CompilePath.lean).
      rel = "src/systems/SystemsLean/CompilePathApply.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.CompilePathApply"
        "COMPILE-PATH-APPLY"
        "APPLY-FIXTURE"
        "HOST-EMIT-APPLY"
        "applyFixtureCompilePathReady"
        "applyFixtureProgramReady"
        "applyFixtureComposeReady"
        "applyFixtureEmitPathOk"
        "applyFixtureApplyOk"
        "lowerApplyFixtureProgram"
        "lowerApplyFixtureCompose"
        "COMPILE-PATH-APPLY-SMOKE"
        "COMPILE-PATH-APPLY-THEOREM"
        "applyFixtureCompilePathReady_true"
        "applyFixtureDoesNotMeanResidualFree_true"
        "applyFixture_claims_false"
        "applyFixtureMintId_eq"
        "applyFromCompose"
        "applyOk"
        "theorem applyFixtureCompilePathReady_true"
        "theorem applyFixtureDoesNotMeanResidualFree_true"
        "theorem applyFixture_claims_false"
        "theorem applyFixtureComposeReady_true"
        "theorem applyFixtureApplyOk_true"
        "theorem applyFixtureMintId_eq"
        "import SystemsLean.CompilePath"
        "import SystemsLean.EmitApply"
      ];
    }
  ];
}
