# SPDX-License-Identifier: Unlicense
# Host presence specs slice (hostSpecsCompilePath). Joined by parent. Sub-1-KLOC.
# No bash, no Python.
{
  hostSpecsCompilePath2 = [
    {
      # Thin Lake main for slake-extract-subset-rebuild (SKELETON).
      rel = "src/systems/SystemsLean/ExtractSubsetRebuildMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ExtractSubsetRebuildMain"
        "slake-extract-subset-rebuild"
        "ExtractSubsetRebuildMain"
        "SKELETON"
        "import SystemsLean.ExtractSubsetRebuild"
      ];
    }
    {
      # ERASURE-SUBSET-EMIT: ideal ladder M1 Erasure subset freestanding emit.
      rel = "src/systems/SystemsLean/ErasureSubsetEmit.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ErasureSubsetEmit"
        "ERASURE-SUBSET-EMIT"
        "SLAKE_ERASURE_SUBSET_EMIT"
        "SLAKE_ERASURE_SUBSET_EMIT_V0"
        "HOST-ERASURE-SUBSET-EMIT"
        "erasureSubsetEmitReady"
        "erasureSubsetEmitInputId"
        "erasureSubsetEmitWroteExpected"
        "erasureSubsetEmitInputReady"
        "erasureSubsetEmitErasureDialectOk"
        "erasureSubsetEmitPackageOk"
        "stillUsesLake"
        "dependsOnLake"
        "ERASURE-SUBSET-EMIT-SMOKE"
        "ERASURE-SUBSET-EMIT-THEOREM"
        "erasureSubsetEmitReady_true"
        "erasureSubsetEmitWroteExpected_true"
        "erasureSubsetEmitDoesNotRetireLake_true"
        "erasureSubsetEmitDoesNotMeanResidualFree_true"
        "erasureSubsetEmit_claims_false"
        "theorem erasureSubsetEmitReady_true"
        "slake-erasure-subset-emit"
        "just erasure-subset-emit"
        "slake_erasure_subset.h"
        "slake_erasure_subset.c"
        "SLAKE_ERASURE_SUBSET_ERASURE"
        "HOST-EMIT-ERASURE"
        "import SystemsLean.CompilePathErasure"
        "import SystemsLean.EmitErasure"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "ERASE-RULE-MULT-0"
        "ERASE-NO-RUNTIME"
        "erasureFixtureCompilePathReady"
        "COMPILE-PATH-ERASURE"
      ];
    }
    {
      # Thin Lake main for slake-erasure-subset-emit (SKELETON).
      rel = "src/systems/SystemsLean/ErasureSubsetEmitMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ErasureSubsetEmitMain"
        "slake-erasure-subset-emit"
        "ErasureSubsetEmitMain"
        "SKELETON"
        "import SystemsLean.ErasureSubsetEmit"
      ];
    }
    {
      # ERASURE-SUBSET-REBUILD: M1 Erasure subset rebuild / self-application.
      rel = "src/systems/SystemsLean/ErasureSubsetRebuild.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ErasureSubsetRebuild"
        "ERASURE-SUBSET-REBUILD"
        "SLAKE_ERASURE_SUBSET_REBUILD"
        "SLAKE_ERASURE_SUBSET_REBUILD_V0"
        "HOST-ERASURE-SUBSET-REBUILD"
        "erasureSubsetRebuildReady"
        "erasureSubsetRebuildInputReady"
        "erasureSubsetRebuildSelfApplyOk"
        "erasureSubsetRebuildWroteExpected"
        "erasureSubsetRebuildPackagePinOk"
        "erasureSubsetRebuildWithoutLakeFinishedClaimed"
        "stillUsesLake"
        "dependsOnLake"
        "ERASURE-SUBSET-REBUILD-SMOKE"
        "ERASURE-SUBSET-REBUILD-THEOREM"
        "erasureSubsetRebuildReady_true"
        "erasureSubsetRebuildSelfApplyOk_true"
        "erasureSubsetRebuildWroteExpected_true"
        "erasureSubsetRebuildDoesNotRetireLake_true"
        "erasureSubsetRebuildDoesNotMeanResidualFree_true"
        "erasureSubsetRebuildDoesNotMeanWithoutLakeFinished_true"
        "erasureSubsetRebuild_claims_false"
        "theorem erasureSubsetRebuildReady_true"
        "slake-erasure-subset-rebuild"
        "just erasure-subset-rebuild"
        "slake_erasure_subset.h"
        "slake_erasure_subset.c"
        "SLAKE_ERASURE_SUBSET_EMIT_V0"
        "erasureSubsetEmitReady"
        "erasureSubsetEmitWroteExpected"
        "import SystemsLean.ErasureSubsetEmit"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "HOST-EMIT-ERASURE"
        "ERASE-RULE-MULT-0"
        "ERASE-NO-RUNTIME"
      ];
    }
    {
      # Thin Lake main for slake-erasure-subset-rebuild (SKELETON).
      rel = "src/systems/SystemsLean/ErasureSubsetRebuildMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ErasureSubsetRebuildMain"
        "slake-erasure-subset-rebuild"
        "ErasureSubsetRebuildMain"
        "SKELETON"
        "import SystemsLean.ErasureSubsetRebuild"
      ];
    }
    {
      # GRAPH-SUBSET-EMIT: ideal ladder M1 Graph subset freestanding emit.
      rel = "src/systems/SystemsLean/GraphSubsetEmit.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.GraphSubsetEmit"
        "GRAPH-SUBSET-EMIT"
        "SLAKE_GRAPH_SUBSET_EMIT"
        "SLAKE_GRAPH_SUBSET_EMIT_V0"
        "HOST-GRAPH-SUBSET-EMIT"
        "graphSubsetEmitReady"
        "graphSubsetEmitInputId"
        "graphSubsetEmitWroteExpected"
        "graphSubsetEmitInputReady"
        "graphSubsetEmitGraphDialectOk"
        "graphSubsetEmitPackageOk"
        "stillUsesLake"
        "dependsOnLake"
        "GRAPH-SUBSET-EMIT-SMOKE"
        "GRAPH-SUBSET-EMIT-THEOREM"
        "graphSubsetEmitReady_true"
        "graphSubsetEmitWroteExpected_true"
        "graphSubsetEmitDoesNotRetireLake_true"
        "graphSubsetEmitDoesNotMeanResidualFree_true"
        "graphSubsetEmit_claims_false"
        "theorem graphSubsetEmitReady_true"
        "slake-graph-subset-emit"
        "just graph-subset-emit"
        "slake_graph_subset.h"
        "slake_graph_subset.c"
        "SLAKE_GRAPH_SUBSET_GRAPH"
        "HOST-EMIT-GRAPH"
        "import SystemsLean.CompilePathGraph"
        "import SystemsLean.EmitGraph"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "IR_GRAPH_EDGES_V0"
        "SLAKE_IR_EDGE_MAX"
        "graphFixtureCompilePathReady"
        "COMPILE-PATH-GRAPH"
      ];
    }
    {
      # Thin Lake main for slake-graph-subset-emit (SKELETON).
      rel = "src/systems/SystemsLean/GraphSubsetEmitMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.GraphSubsetEmitMain"
        "slake-graph-subset-emit"
        "GraphSubsetEmitMain"
        "SKELETON"
        "import SystemsLean.GraphSubsetEmit"
      ];
    }
    {
      # GRAPH-SUBSET-REBUILD: M1 Graph subset rebuild / self-application.
      rel = "src/systems/SystemsLean/GraphSubsetRebuild.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.GraphSubsetRebuild"
        "GRAPH-SUBSET-REBUILD"
        "SLAKE_GRAPH_SUBSET_REBUILD"
        "SLAKE_GRAPH_SUBSET_REBUILD_V0"
        "HOST-GRAPH-SUBSET-REBUILD"
        "graphSubsetRebuildReady"
        "graphSubsetRebuildInputReady"
        "graphSubsetRebuildSelfApplyOk"
        "graphSubsetRebuildWroteExpected"
        "graphSubsetRebuildPackagePinOk"
        "graphSubsetRebuildWithoutLakeFinishedClaimed"
        "stillUsesLake"
        "dependsOnLake"
        "GRAPH-SUBSET-REBUILD-SMOKE"
        "GRAPH-SUBSET-REBUILD-THEOREM"
        "graphSubsetRebuildReady_true"
        "graphSubsetRebuildSelfApplyOk_true"
        "graphSubsetRebuildWroteExpected_true"
        "graphSubsetRebuildDoesNotRetireLake_true"
        "graphSubsetRebuildDoesNotMeanResidualFree_true"
        "graphSubsetRebuildDoesNotMeanWithoutLakeFinished_true"
        "graphSubsetRebuild_claims_false"
        "theorem graphSubsetRebuildReady_true"
        "slake-graph-subset-rebuild"
        "just graph-subset-rebuild"
        "slake_graph_subset.h"
        "slake_graph_subset.c"
        "SLAKE_GRAPH_SUBSET_EMIT_V0"
        "graphSubsetEmitReady"
        "graphSubsetEmitWroteExpected"
        "import SystemsLean.GraphSubsetEmit"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "HOST-EMIT-GRAPH"
        "IR_GRAPH_EDGES_V0"
        "SLAKE_IR_EDGE_MAX"
      ];
    }
    {
      # Thin Lake main for slake-graph-subset-rebuild (SKELETON).
      rel = "src/systems/SystemsLean/GraphSubsetRebuildMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.GraphSubsetRebuildMain"
        "slake-graph-subset-rebuild"
        "GraphSubsetRebuildMain"
        "SKELETON"
        "import SystemsLean.GraphSubsetRebuild"
      ];
    }
    {
      # COMPOSE-SUBSET-EMIT: ideal ladder M1 Compose subset freestanding emit.
      rel = "src/systems/SystemsLean/ComposeSubsetEmit.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ComposeSubsetEmit"
        "COMPOSE-SUBSET-EMIT"
        "SLAKE_COMPOSE_SUBSET_EMIT"
        "SLAKE_COMPOSE_SUBSET_EMIT_V0"
        "HOST-COMPOSE-SUBSET-EMIT"
        "composeSubsetEmitReady"
        "composeSubsetEmitInputId"
        "composeSubsetEmitWroteExpected"
        "composeSubsetEmitInputReady"
        "composeSubsetEmitComposeDialectOk"
        "composeSubsetEmitPackageOk"
        "stillUsesLake"
        "dependsOnLake"
        "COMPOSE-SUBSET-EMIT-SMOKE"
        "COMPOSE-SUBSET-EMIT-THEOREM"
        "composeSubsetEmitReady_true"
        "composeSubsetEmitWroteExpected_true"
        "composeSubsetEmitDoesNotRetireLake_true"
        "composeSubsetEmitDoesNotMeanResidualFree_true"
        "composeSubsetEmit_claims_false"
        "theorem composeSubsetEmitReady_true"
        "slake-compose-subset-emit"
        "just compose-subset-emit"
        "slake_compose_subset.h"
        "slake_compose_subset.c"
        "SLAKE_COMPOSE_SUBSET_COMPOSE"
        "HOST-EMIT-COMPOSE"
        "import SystemsLean.CompilePathCompose"
        "import SystemsLean.EmitCompose"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "HOST_COMPOSE_V0"
        "IR_GRAPH_EDGES_V0"
        "composeFixtureCompilePathReady"
        "COMPILE-PATH-COMPOSE"
      ];
    }
    {
      # Thin Lake main for slake-compose-subset-emit (SKELETON).
      rel = "src/systems/SystemsLean/ComposeSubsetEmitMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ComposeSubsetEmitMain"
        "slake-compose-subset-emit"
        "ComposeSubsetEmitMain"
        "SKELETON"
        "import SystemsLean.ComposeSubsetEmit"
      ];
    }
    {
      # COMPOSE-SUBSET-REBUILD: M1 Compose subset rebuild / self-application.
      rel = "src/systems/SystemsLean/ComposeSubsetRebuild.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ComposeSubsetRebuild"
        "COMPOSE-SUBSET-REBUILD"
        "SLAKE_COMPOSE_SUBSET_REBUILD"
        "SLAKE_COMPOSE_SUBSET_REBUILD_V0"
        "HOST-COMPOSE-SUBSET-REBUILD"
        "composeSubsetRebuildReady"
        "composeSubsetRebuildInputReady"
        "composeSubsetRebuildSelfApplyOk"
        "composeSubsetRebuildWroteExpected"
        "composeSubsetRebuildPackagePinOk"
        "composeSubsetRebuildWithoutLakeFinishedClaimed"
        "stillUsesLake"
        "dependsOnLake"
        "COMPOSE-SUBSET-REBUILD-SMOKE"
        "COMPOSE-SUBSET-REBUILD-THEOREM"
        "composeSubsetRebuildReady_true"
        "composeSubsetRebuildSelfApplyOk_true"
        "composeSubsetRebuildWroteExpected_true"
        "composeSubsetRebuildDoesNotRetireLake_true"
        "composeSubsetRebuildDoesNotMeanResidualFree_true"
        "composeSubsetRebuildDoesNotMeanWithoutLakeFinished_true"
        "composeSubsetRebuild_claims_false"
        "theorem composeSubsetRebuildReady_true"
        "slake-compose-subset-rebuild"
        "just compose-subset-rebuild"
        "slake_compose_subset.h"
        "slake_compose_subset.c"
        "SLAKE_COMPOSE_SUBSET_EMIT_V0"
        "composeSubsetEmitReady"
        "composeSubsetEmitWroteExpected"
        "import SystemsLean.ComposeSubsetEmit"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "HOST-EMIT-COMPOSE"
        "HOST_COMPOSE_V0"
        "IR_GRAPH_EDGES_V0"
      ];
    }
    {
      # Thin Lake main for slake-compose-subset-rebuild (SKELETON).
      rel = "src/systems/SystemsLean/ComposeSubsetRebuildMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.ComposeSubsetRebuildMain"
        "slake-compose-subset-rebuild"
        "ComposeSubsetRebuildMain"
        "SKELETON"
        "import SystemsLean.ComposeSubsetRebuild"
      ];
    }
    {
      # SUBSET-FRONT: ideal ladder M3 Mult subset language front-end.
      rel = "src/systems/SystemsLean/SubsetFront.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.SubsetFront"
        "SUBSET-FRONT"
        "SLAKE_SUBSET_FRONT"
        "SLAKE_SUBSET_FRONT_V0"
        "HOST-SUBSET-FRONT"
        "subsetFrontReady"
        "subsetFrontGoodG1"
        "subsetFrontGoodG2"
        "subsetFrontBadB1"
        "subsetFrontBadB2"
        "subsetFrontBadB3"
        "subsetFrontStillUsesLake"
        "subsetFrontDependsOnLake"
        "stillUsesLake"
        "dependsOnLake"
        "SUBSET-FRONT-SMOKE"
        "SUBSET-FRONT-THEOREM"
        "subsetFrontReady_true"
        "subsetFrontGoodG1_true"
        "subsetFrontGoodG2_true"
        "subsetFrontBadB1_true"
        "subsetFrontBadB2_true"
        "subsetFrontBadB3_true"
        "subsetFrontDoesNotRetireLake_true"
        "subsetFrontDoesNotMeanResidualFree_true"
        "subsetFront_claims_false"
        "theorem subsetFrontReady_true"
        "slake-subset-front"
        "just subset-front"
        "goldens/mult-front"
        "FAIL-CLOSED-UNKNOWN-GRADE"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "KIND-MULT-MISMATCH"
        "parseSource"
        "programCompileReady"
        "import SystemsLean.CompilePath"
        "import SystemsLean.IrProgram"
        "import SystemsLean.Types"
        "import SystemsLean.Mult"
        "UNIT_SURFACE"
        "Not freestanding emit"
        "MULT-0"
      ];
    }
    {
      # Thin Lake main for slake-subset-front (SKELETON).
      rel = "src/systems/SystemsLean/SubsetFrontMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.SubsetFrontMain"
        "slake-subset-front"
        "SubsetFrontMain"
        "SKELETON"
        "import SystemsLean.SubsetFront"
      ];
    }
    {
      # SUBSET-PACKAGE-JOIN: ideal ladder M5 Name A multi-unit package rebuild join
      # + Name C without-Lake multi-unit join deepen.
      rel = "src/systems/SystemsLean/SubsetPackageJoin.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.SubsetPackageJoin"
        "SUBSET-PACKAGE-JOIN"
        "SLAKE_SUBSET_PACKAGE_JOIN"
        "SLAKE_SUBSET_PACKAGE_JOIN_V0"
        "HOST-SUBSET-PACKAGE-JOIN"
        "subsetPackageJoinReady"
        "subsetPackageJoinFinishedClaimed"
        "subsetPackageJoinUnitsReady"
        "subsetPackageJoinKeepsHostLake"
        "justRecipeSubsetPackageJoin"
        "subset-packages-rebuild-join"
        "justRecipeSubsetPackageJoinWithoutLake"
        "subset-packages-rebuild-join-without-lake"
        "prebuiltUnitRebuildBinDirRel"
        "subsetPackageJoinWithoutLakeReady"
        "subsetPackageJoinWithoutLakeKeepsHostLake"
        "subsetPackageJoinNonMultWithoutLakeHonest"
        "subsetPackageJoinWithoutLakeMultiUnitFinishedClaimed"
        "stillUsesLake"
        "dependsOnLake"
        "SUBSET-PACKAGE-JOIN-SMOKE"
        "SUBSET-PACKAGE-JOIN-THEOREM"
        "subsetPackageJoinReady_true"
        "subsetPackageJoinFinishedClaimed_true"
        "subsetPackageJoinUnitsReady_true"
        "subsetPackageJoinKeepsHostLake_true"
        "subsetPackageJoinWithoutLakeMultiUnitFinishedClaimed_true"
        "subsetPackageJoinWithoutLakeReady_true"
        "subsetPackageJoinWithoutLakeKeepsHostLake_true"
        "subsetPackageJoinDoesNotRetireLake_true"
        "subsetPackageJoinDoesNotMeanResidualFree_true"
        "subsetPackageJoin_claims_false"
        "theorem subsetPackageJoinReady_true"
        "def subsetPackageJoinFinishedClaimed : Bool := true"
        "def subsetPackageJoinWithoutLakeMultiUnitFinishedClaimed : Bool := true"
        "def stillUsesLake : Bool := true"
        "def dependsOnLake : Bool := true"
        "import SystemsLean.MultSubsetRebuild"
        "import SystemsLean.LinearSubsetRebuild"
        "import SystemsLean.TypesSubsetRebuild"
        "import SystemsLean.ProgramSubsetRebuild"
        "import SystemsLean.ExtractSubsetRebuild"
        "import SystemsLean.ErasureSubsetRebuild"
        "import SystemsLean.GraphSubsetRebuild"
        "import SystemsLean.ComposeSubsetRebuild"
        "multSubsetRebuildReady"
        "linearSubsetRebuildReady"
        "composeSubsetRebuildReady"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # FRONT-MULT-PACKAGE: ideal ladder M5 Name B front-end Mult package path.
      rel = "src/systems/SystemsLean/FrontMultPackage.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.FrontMultPackage"
        "FRONT-MULT-PACKAGE"
        "SLAKE_FRONT_MULT_PACKAGE"
        "SLAKE_FRONT_MULT_PACKAGE_V0"
        "HOST-FRONT-MULT-PACKAGE"
        "frontMultPackageReady"
        "frontMultPackageFinishedClaimed"
        "frontMultPackageG1Ready"
        "frontMultPackageMultReady"
        "frontMultPackageKeepsHostLake"
        "justRecipeFrontMultPackage"
        "front-mult-package"
        "stillUsesLake"
        "dependsOnLake"
        "FRONT-MULT-PACKAGE-SMOKE"
        "FRONT-MULT-PACKAGE-THEOREM"
        "frontMultPackageReady_true"
        "frontMultPackageFinishedClaimed_true"
        "frontMultPackageG1Ready_true"
        "frontMultPackageMultReady_true"
        "frontMultPackageKeepsHostLake_true"
        "frontMultPackageDoesNotRetireLake_true"
        "frontMultPackageDoesNotMeanResidualFree_true"
        "frontMultPackage_claims_false"
        "theorem frontMultPackageReady_true"
        "def frontMultPackageFinishedClaimed : Bool := true"
        "def stillUsesLake : Bool := true"
        "def dependsOnLake : Bool := true"
        "import SystemsLean.SubsetFront"
        "import SystemsLean.MultSubsetEmit"
        "import SystemsLean.MultSubsetRebuild"
        "subsetFrontGoodG1"
        "subsetFrontReady"
        "multSubsetEmitReady"
        "multSubsetRebuildReady"
        "acceptG1Golden"
        "runFrontMultPackage"
        "multSubsetEmitWrite"
        "slake-front-mult-package"
        "just front-mult-package"
        "goldens/mult-front"
        "SLAKE_MULT_SUBSET_EMIT_V0"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # Thin Lake main for slake-front-mult-package (SKELETON).
      rel = "src/systems/SystemsLean/FrontMultPackageMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.FrontMultPackageMain"
        "slake-front-mult-package"
        "FrontMultPackageMain"
        "SKELETON"
        "import SystemsLean.FrontMultPackage"
      ];
    }
    {
      # HOST-TERM-IR: peer elaborator Mult-first closed host term/command IR.
      rel = "src/systems/SystemsLean/HostTerm.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostTerm"
        "HOST-TERM-IR"
        "HOST-TERM"
        "SLAKE_HOST_TERM"
        "SLAKE_HOST_TERM_V0"
        "hostTermReady"
        "hostTermGoodMult"
        "hostTermBadEmpty"
        "hostTermBadEmptyName"
        "hostTermBadIndZeroCtor"
        "hostTermBadMatchEmpty"
        "hostTermHostElaboratorResidualRemains"
        "hostTermDoesNotClaimPeerGreen"
        "HOST-TERM-SMOKE"
        "HOST-TERM-THEOREM"
        "hostTermReady_true"
        "hostTermGoodMult_true"
        "hostTermBadEmpty_true"
        "hostTermBadEmptyName_true"
        "hostTermBadIndZeroCtor_true"
        "hostTermBadMatchEmpty_true"
        "hostTermDoesNotClaimPeer_true"
        "hostTermKeepsHostResidual_true"
        "hostTermDoesNotMeanResidualFree_true"
        "hostTerm_claims_false"
        "theorem hostTermReady_true"
        "multFixtureModule"
        "isWellFormed"
        "import SystemsLean.Mult"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "MULT-0"
      ];
    }
    {
      # HOST-FRONT: peer elaborator Mult-first host fragment front-end.
      # Theorems/smoke peeled to HostFrontTheorems; golden texts to HostFrontGoldens.
      rel = "src/systems/SystemsLean/HostFront.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostFront"
        "HOST-FRONT"
        "SLAKE_HOST_FRONT"
        "SLAKE_HOST_FRONT_V0"
        "hostFrontReady"
        "hostFrontGoodG1"
        "hostFrontGoodG2"
        "hostFrontGoodG3"
        "hostFrontGoodG4"
        "hostFrontGoodG5"
        "hostFrontGoodG6"
        "hostFrontGoodG7"
        "hostFrontBadB1"
        "hostFrontBadB2"
        "hostFrontBadB3"
        "hostFrontBadB4"
        "hostFrontHostElaboratorResidualRemains"
        "hostFrontDoesNotClaimPeerGreen"
        "HOST-FRONT-SMOKE"
        "HOST-FRONT-THEOREM"
        "HostFrontTheorems"
        "hostFrontReady_true"
        "goodG3Text"
        "goodG4Text"
        "goodG5Text"
        "goodG6Text"
        "goodG7Text"
        "LINEAR-EXACT-ONCE"
        "TYPED_IR_V0"
        "KIND-MULT-OK"
        "TYPES-FIXTURE"
        "IR_PROGRAM_V0"
        "ORDERED-IR-PROGRAM"
        "PROGRAM-FIXTURE"
        "IR_GRAPH_EDGES_V0"
        "EMPTY-GRAPH-OK"
        "GRAPH-FIXTURE"
        "HOST_COMPOSE_V0"
        "HOST-COMPOSE"
        "COMPOSE-FIXTURE"
        "slake-host-front"
        "just host-front"
        "goldens/host-front"
        "parseSource"
        "EMPTY-MODULE-FAIL-CLOSED"
        "LINE-SHAPE"
        "UNKNOWN-CMD"
        "ZERO-CTOR-INDUCTIVE"
        "isWellFormed"
        "import SystemsLean.HostTerm"
        "import SystemsLean.Mult"
        "import SystemsLean.HostFrontGoldens"
        "HostFrontGoldens"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "MULT-0"
      ];
    }
    {
      # HostFrontGoldens: dual-pinned golden texts + file names peel.
      rel = "src/systems/SystemsLean/HostFrontGoldens.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "HostFrontGoldens"
        "SystemsLean.HostFrontGoldens"
        "goodG1Text"
        "goodG2Text"
        "goodG3Text"
        "goodG4Text"
        "goodG5Text"
        "goodG6Text"
        "goodG7Text"
        "badB1Text"
        "badB2Text"
        "badB3Text"
        "badB4Text"
        "LINEAR-EXACT-ONCE"
        "TYPED_IR_V0"
        "IR_PROGRAM_V0"
        "IR_GRAPH_EDGES_V0"
        "HOST_COMPOSE_V0"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # HostFrontTheorems: HOST-FRONT-THEOREM + SMOKE peel
      # (same namespace HostFront).
      rel = "src/systems/SystemsLean/HostFrontTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "HostFrontTheorems"
        "SystemsLean.HostFrontTheorems"
        "import SystemsLean.HostFront"
        "HOST-FRONT-THEOREM"
        "HOST-FRONT-SMOKE"
        "HOST-FRONT"
        "example"
        "hostFrontReady_true"
        "hostFrontGoodG1_true"
        "hostFrontGoodG2_true"
        "hostFrontGoodG3_true"
        "hostFrontGoodG4_true"
        "hostFrontGoodG5_true"
        "hostFrontGoodG6_true"
        "hostFrontGoodG7_true"
        "hostFrontBadB1_true"
        "hostFrontBadB2_true"
        "hostFrontBadB3_true"
        "hostFrontBadB4_true"
        "hostFrontGoldensStructuralOk_true"
        "hostFrontDoesNotClaimPeer_true"
        "hostFrontKeepsHostResidual_true"
        "hostFrontDoesNotMeanResidualFree_true"
        "hostFront_claims_false"
        "hostFront_ids_eq"
        "theorem hostFrontReady_true"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # Thin Lake main for slake-host-front (SKELETON).
      rel = "src/systems/SystemsLean/HostFrontMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostFrontMain"
        "slake-host-front"
        "HostFrontMain"
        "SKELETON"
        "import SystemsLean.HostFront"
      ];
    }
    {
      # HOST-FRAGMENT-CHECK: peer elaborator Mult-first host fragment check
      # (+ step 5 without-Lake prebuilt measured path).
      rel = "src/systems/SystemsLean/HostCheck.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostCheck"
        "HOST-FRAGMENT-CHECK"
        "SLAKE_HOST_FRAGMENT_CHECK"
        "SLAKE_HOST_FRAGMENT_CHECK_V0"
        "hostFragmentCheckReady"
        "hostFragmentCheckFinishedClaimed"
        "hostFragmentCheckCorpusOk"
        "hostFragmentCheckGoodG1"
        "hostFragmentCheckGoodG2"
        "hostFragmentCheckGoodG3"
        "hostFragmentCheckGoodG4"
        "hostFragmentCheckGoodG5"
        "hostFragmentCheckGoodG6"
        "hostFragmentCheckGoodG7"
        "hostFragmentCheckBadB1"
        "hostFragmentCheckBadB2"
        "hostFragmentCheckBadB3"
        "hostFragmentCheckBadB4"
        "hostFragmentCheckHostElaboratorResidualRemains"
        "hostFragmentCheckDoesNotClaimPeerGreen"
        "hostFragmentCheckWithoutLakeFinished"
        "hostFragmentCheckWithoutLakeReady"
        "hostFragmentCheckWithoutLakeKeepsHostLake"
        "justRecipeWithoutLake"
        "prebuiltHostFragmentCheckRel"
        "host-fragment-check-without-lake"
        "HOST-FRAGMENT-CHECK-WITHOUT-LAKE"
        "def hostFragmentCheckWithoutLakeFinished : Bool := true"
        "HOST-FRAGMENT-CHECK-SMOKE"
        "HOST-FRAGMENT-CHECK-THEOREM"
        "hostFragmentCheckReady_true"
        "hostFragmentCheckFinishedClaimed_true"
        "hostFragmentCheckCorpusOk_true"
        "hostFragmentCheckGoodG1_true"
        "hostFragmentCheckGoodG2_true"
        "hostFragmentCheckGoodG3_true"
        "hostFragmentCheckGoodG4_true"
        "hostFragmentCheckGoodG5_true"
        "hostFragmentCheckGoodG6_true"
        "hostFragmentCheckGoodG7_true"
        "hostFragmentCheckBadB1_true"
        "hostFragmentCheckBadB2_true"
        "hostFragmentCheckBadB3_true"
        "hostFragmentCheckBadB4_true"
        "hostFragmentCheckDoesNotClaimPeer_true"
        "hostFragmentCheckKeepsHostResidual_true"
        "hostFragmentCheckDoesNotMeanResidualFree_true"
        "hostFragmentCheckDoesNotClaimWithoutLake_true"
        "hostFragmentCheckWithoutLakeFinished_true"
        "hostFragmentCheckWithoutLakeReady_true"
        "hostFragmentCheckWithoutLakeKeepsHostLake_true"
        "hostFragmentCheck_claims_false"
        "theorem hostFragmentCheckReady_true"
        "slake-host-fragment-check"
        "just host-fragment-check"
        "goldens/host-front"
        "EMPTY-MODULE-FAIL-CLOSED"
        "LINE-SHAPE"
        "UNKNOWN-CMD"
        "ZERO-CTOR-INDUCTIVE"
        "import SystemsLean.HostFront"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # Thin Lake main for slake-host-fragment-check (SKELETON).
      rel = "src/systems/SystemsLean/HostCheckMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostCheckMain"
        "slake-host-fragment-check"
        "HostCheckMain"
        "SKELETON"
        "import SystemsLean.HostCheck"
      ];
    }
    {
      # HOST-GRAPH: peer elaborator Mult-first multi-file module graph
      # (+ without-Lake prebuilt measured path).
      # Theorems/smoke in HostGraphTheorems (same namespace; long-file split).
      rel = "src/systems/SystemsLean/HostGraph.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostGraph"
        "HOST-GRAPH"
        "SLAKE_HOST_GRAPH"
        "SLAKE_HOST_GRAPH_V0"
        "hostGraphReady"
        "hostGraphFinishedClaimed"
        "hostGraphGoodClosure"
        "hostGraphGoodLinearExpand"
        "hostGraphGoodTypesExpand"
        "hostGraphGoodProgramExpand"
        "hostGraphGoodGraphExpand"
        "hostGraphGoodComposeExpand"
        "hostGraphBadMissing"
        "hostGraphBadCycle"
        "hostGraphHostElaboratorResidualRemains"
        "hostGraphDoesNotClaimPeerGreen"
        "hostGraphWithoutLakeFinished"
        "hostGraphWithoutLakeReady"
        "hostGraphWithoutLakeKeepsHostLake"
        "justRecipeWithoutLake"
        "prebuiltHostGraphRel"
        "host-graph-without-lake"
        "HOST-GRAPH-WITHOUT-LAKE"
        "def hostGraphWithoutLakeFinished : Bool := true"
        "HOST-GRAPH-SMOKE"
        "HOST-GRAPH-THEOREM"
        "HostGraphTheorems"
        "hostGraphReady_true"
        "linearText"
        "typesText"
        "programText"
        "graphText"
        "composeText"
        "documentedExpandImportClosure"
        "documentedTypesExpandImportClosure"
        "documentedProgramExpandImportClosure"
        "documentedGraphExpandImportClosure"
        "documentedComposeExpandImportClosure"
        "LINEAR-EXACT-ONCE"
        "TYPED_IR_V0"
        "KIND-MULT-OK"
        "TYPES-FIXTURE"
        "IR_PROGRAM_V0"
        "ORDERED-IR-PROGRAM"
        "PROGRAM-FIXTURE"
        "IR_GRAPH_EDGES_V0"
        "EMPTY-GRAPH-OK"
        "GRAPH-FIXTURE"
        "HOST_COMPOSE_V0"
        "HOST-COMPOSE"
        "COMPOSE-FIXTURE"
        "slake-host-graph"
        "just host-graph"
        "goldens/host-graph"
        "MISSING-IMPORT"
        "IMPORT-CYCLE"
        "resolveGraph"
        "moduleImports"
        "documentedImportClosure"
        "import SystemsLean.HostFront"
        "import SystemsLean.HostTerm"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # HostGraphTheorems: HOST-GRAPH-THEOREM + SMOKE long-file split
      # (same namespace HostGraph).
      rel = "src/systems/SystemsLean/HostGraphTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "HostGraphTheorems"
        "SystemsLean.HostGraphTheorems"
        "import SystemsLean.HostGraph"
        "HOST-GRAPH-THEOREM"
        "HOST-GRAPH-SMOKE"
        "HOST-GRAPH"
        "example"
        "hostGraphReady_true"
        "hostGraphFinishedClaimed_true"
        "hostGraphGoodClosure_true"
        "hostGraphGoodMultLeaf_true"
        "hostGraphGoodLinearExpand_true"
        "hostGraphGoodTypesExpand_true"
        "hostGraphGoodProgramExpand_true"
        "hostGraphGoodGraphExpand_true"
        "hostGraphGoodComposeExpand_true"
        "hostGraphBadMissing_true"
        "hostGraphBadCycle_true"
        "hostGraphGoldensStructuralOk_true"
        "hostGraphDoesNotClaimPeer_true"
        "hostGraphKeepsHostResidual_true"
        "hostGraphDoesNotMeanResidualFree_true"
        "hostGraphWithoutLakeFinished_true"
        "hostGraphWithoutLakeReady_true"
        "hostGraphWithoutLakeKeepsHostLake_true"
        "hostGraph_claims_false"
        "hostGraph_ids_eq"
        "theorem hostGraphReady_true"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # Thin Lake main for slake-host-graph (SKELETON).
      rel = "src/systems/SystemsLean/HostGraphMain.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostGraphMain"
        "slake-host-graph"
        "HostGraphMain"
        "SKELETON"
        "import SystemsLean.HostGraph"
      ];
    }
    {
      # HOST-PACKAGE-WRITE: peer elaborator Mult + Linear + Types + Program +
      # Graph package write (HostFront G1 + HostGraph Mult set + MultSubsetEmit
      # write; Linear/Types/Program/Graph expand + unit subset emit writes;
      # Track 3b-5 Linear + Track 3b-6 Types + Track 3b-7 Program + Track 3b-8
      # Graph named units beyond Mult).
      rel = "src/systems/SystemsLean/HostPackageWrite.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SystemsLean.HostPackageWrite"
        "HOST-PACKAGE-WRITE"
        "SLAKE_HOST_PACKAGE_WRITE"
        "SLAKE_HOST_PACKAGE_WRITE_V0"
        "hostPackageWriteReady"
        "hostPackageWriteFinishedClaimed"
        "hostPackageWriteG1Ready"
        "hostPackageWriteGraphReady"
        "hostPackageWriteMultReady"
        "hostPackageWriteLinearReady"
        "hostPackageWriteLinearGraphReady"
        "hostPackageWriteTypesReady"
        "hostPackageWriteTypesGraphReady"
        "hostPackageWriteProgramReady"
        "hostPackageWriteProgramGraphReady"
        "hostPackageWriteGraphExpandReady"
        "hostPackageWriteGraphPackageReady"
        "hostPackageWriteHostElaboratorResidualRemains"
        "hostPackageWriteDoesNotClaimPeerGreen"
        "hostPackageWriteWithoutLakeFinished"
        "hostPackageWriteWithoutLakeReady"
        "hostPackageWriteWithoutLakeKeepsHostLake"
        "justRecipeWithoutLake"
        "prebuiltHostPackageWriteRel"
        "host-package-write-without-lake"
        "HOST-PACKAGE-WRITE-WITHOUT-LAKE"
        "def hostPackageWriteWithoutLakeFinished : Bool := true"
        "def hostPackageWriteFinishedClaimed : Bool := true"
        "HOST-PACKAGE-WRITE-SMOKE"
        "HOST-PACKAGE-WRITE-THEOREM"
        "HostPackageWriteTheorems"
        "hostPackageWriteReady_true"
        "slake-host-package-write"
        "just host-package-write"
        "multSubsetEmitWrite"
        "linearSubsetEmitWrite"
        "typesSubsetEmitWrite"
        "programSubsetEmitWrite"
        "graphSubsetEmitWrite"
        "SLAKE_MULT_SUBSET_EMIT_V0"
        "SLAKE_LINEAR_SUBSET_EMIT_V0"
        "SLAKE_TYPES_SUBSET_EMIT_V0"
        "SLAKE_PROGRAM_SUBSET_EMIT_V0"
        "SLAKE_GRAPH_SUBSET_EMIT_V0"
        "hostFrontGoodG1"
        "hostGraphGoodClosure"
        "hostGraphGoodLinearExpand"
        "hostGraphGoodTypesExpand"
        "hostGraphGoodProgramExpand"
        "hostGraphGoodGraphExpand"
        "import SystemsLean.HostFront"
        "import SystemsLean.HostGraph"
        "import SystemsLean.MultSubsetEmit"
        "import SystemsLean.LinearSubsetEmit"
        "import SystemsLean.TypesSubsetEmit"
        "import SystemsLean.ProgramSubsetEmit"
        "import SystemsLean.GraphSubsetEmit"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # HostPackageWriteTheorems: HOST-PACKAGE-WRITE-THEOREM + SMOKE peel
      # (same namespace HostPackageWrite).
      rel = "src/systems/SystemsLean/HostPackageWriteTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "HostPackageWriteTheorems"
        "SystemsLean.HostPackageWriteTheorems"
        "import SystemsLean.HostPackageWrite"
        "HOST-PACKAGE-WRITE-THEOREM"
        "HOST-PACKAGE-WRITE-SMOKE"
        "HOST-PACKAGE-WRITE"
        "example"
        "hostPackageWriteReady_true"
        "hostPackageWriteFinishedClaimed_true"
        "hostPackageWriteG1Ready_true"
        "hostPackageWriteGraphReady_true"
        "hostPackageWriteMultReady_true"
        "hostPackageWriteLinearReady_true"
        "hostPackageWriteLinearGraphReady_true"
        "hostPackageWriteTypesReady_true"
        "hostPackageWriteTypesGraphReady_true"
        "hostPackageWriteProgramReady_true"
        "hostPackageWriteProgramGraphReady_true"
        "hostPackageWriteGraphExpandReady_true"
        "hostPackageWriteGraphPackageReady_true"
        "hostPackageWriteComposeExpandReady_true"
        "hostPackageWriteComposePackageReady_true"
        "hostPackageWriteWithoutLakeFinished_true"
        "hostPackageWriteWithoutLakeReady_true"
        "hostPackageWriteWithoutLakeKeepsHostLake_true"
        "hostPackageWrite_claims_false"
        "hostPackageWrite_ids_eq"
        "theorem hostPackageWriteReady_true"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
  ];
}
