# SPDX-License-Identifier: Unlicense
# Host presence token specs slice. Joined via specs.nix. Sub-1-KLOC.
# No bash, no Python.
{
  hostSpecsTipSelfApply1 = [
    {
      # Compiler self-application readiness (SH5 partial).
      # Long-file split: theorems + smoke live in SelfApplyTheorems (same namespace).
      rel = "src/systems/SystemsLean/SelfApply.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_SELF_APPLY_V0"
        "HOST-SELF-APPLY"
        "SELF-HOST-SELF-APPLY"
        "SELF-HOST"
        "selfApplyReady"
        "kernelRebuildsKernel"
        "multKernelSideReady"
        "linearKernelSideReady"
        "typesKernelSideReady"
        "programKernelSideReady"
        "emitKernelSideReady"
        "selfApplyOk"
        "SystemsLean.SelfApply"
        "SelfApplyTheorems"
        "SELF-APPLY-SMOKE"
        "HOST-SELF-APPLY-SMOKE"
        "HOST-PARITY-MULT"
        "SELF-HOST-KERNEL-LINEAR"
        "SELF-HOST-KERNEL-TYPES"
        "SELF-HOST-KERNEL-PROGRAM"
        "SELF-HOST-KERNEL-EMIT"
        "multParityReady"
        "linearKernelReady"
        "typesKernelReady"
        "programKernelReady"
        "emitKernelReady"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/SelfApply.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
        "SELF-APPLY-THEOREM"
        "HOST-SELF-APPLY-THEOREM"
        "selfApplyReady_true"
        "kernelRebuildsKernel_true"
        "selfApplySurfaceOk_true"
        "selfApplyOk_eq_ready"
      ];
      anyGroups = [
        [
          "selfApplySurfaceOk"
          "kernelRebuildsKernel"
        ]
      ];
    }
    {
      # SelfApplyTheorems: SELF-APPLY-THEOREM + SELF-APPLY-SMOKE
      # (same namespace SelfApply; long-file split).
      rel = "src/systems/SystemsLean/SelfApplyTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SelfApplyTheorems"
        "SystemsLean.SelfApplyTheorems"
        "import SystemsLean.SelfApply"
        "SELF-APPLY-THEOREM"
        "HOST-SELF-APPLY-THEOREM"
        "SELF-APPLY-SMOKE"
        "HOST-SELF-APPLY-SMOKE"
        "example"
        "selfApplyReady_true"
        "kernelRebuildsKernel_true"
        "selfApplySurfaceOk_true"
        "selfApplyOk_true"
        "selfApplyOk_eq_ready"
        "stageId_eq"
        "hostSelfApplyId_eq"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem selfApplyReady_true"
        "theorem kernelRebuildsKernel_true"
        "theorem selfApplySurfaceOk_true"
        "theorem selfApplyOk_eq_ready"
        "example : selfApplyReady = true"
        "example : selfApplyOk = true"
        "example : kernelRebuildsKernel = true"
      ];
      anyGroups = [ ];
    }
    {
      # Freestanding self-application deepen (SH5 freestanding deepen partial).
      # Living tip: freestandingProductSelfHostComplete true after claim B complete.
      # Composes freestanding Mult..Emit parity ladder (ParityEmit) into readiness.
      # Long-file split: theorems + smoke in SelfApplyFsTheorems; close-path
      # PartialReady B34..complete in SelfApplyFsClose (same namespace).
      rel = "src/systems/SystemsLean/SelfApplyFs.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_SELF_APPLY_FS_V0"
        "HOST-SELF-APPLY-FS"
        "SELF-HOST-SELF-APPLY-FS"
        "SELF-HOST"
        "freestandingExtractPathReady"
        "freestandingBodyPathReady"
        "freestandingSelfApplyPathReady"
        "freestandingParityLadderReady"
        "freestandingEmitParityReady"
        "freestandingSelfApplyReady"
        "freestandingProductSelfHostComplete"
        "selfApplyFsDoesNotComplete"
        "selfApplyFsOk"
        "SystemsLean.SelfApplyFs"
        "SELF-APPLY-FS-SMOKE"
        "HOST-SELF-APPLY-FS-SMOKE"
        "HOST-SELF-APPLY"
        "selfApplyReady"
        "HOST-PARITY-EMIT"
        "SELF-HOST-PARITY-EMIT"
        "SLAKE_SELF_HOST_PARITY_EMIT_V0"
        "emitParityReady"
        "multLinearTypesProgramEmitParityReady"
        "RUNTIME-FS"
        "EMIT-BOUNDARY"
        "HOST-EMIT-SSOT"
        "EMIT_BODY_V0"
        "HOST-EMIT-MULT"
        "SELF-HOST-KERNEL-EMIT"
        "lowerEmitCompose"
        "extractOkFs"
        "bodyOk"
        "emitMultReady"
        "import SystemsLean.ParityEmit"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/SelfApplyFs.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not full LLVM backend"
        "def freestandingProductSelfHostComplete : Bool := true"
        "&& freestandingParityLadderReady"
        "SELF-APPLY-FS-THEOREM"
        "HOST-SELF-APPLY-FS-THEOREM"
        "SELF-HOST-KERNEL-SELF-APPLY"
        "productKernelSelfApplyPartialReady"
        "product kernel self-application"
        "KernelSelfApply"
        "SELF-HOST-PRODUCT-OUT"
        "productOutKernelEvidencePartialReady"
        "product Out kernel evidence"
        "ProductOutKernel"
        "SELF-HOST-PRODUCT-PATH-BOOTSTRAP"
        "productPathHostLakeBootstrapRemains"
        "productPathHostLakeBootstrapPartialReady"
        "product path Lake bootstrap"
        "BootstrapHonesty"
        "def productPathHostLakeBootstrapRemains : Bool := true"
        "SELF-HOST-PRODUCT-WRITER-SURFACE"
        "productWriterSurfacePartialReady"
        "product writer surface"
        "ProductPathWriterSurface"
        "SELF-HOST-PRODUCT-WRITER-PATH-PLAN"
        "productWriterPathPlanPartialReady"
        "product writer path plan"
        "ProductPathWriterPathPlan"
        "SELF-HOST-PRODUCT-WRITER-PATH-EXEC"
        "productWriterPathExecutionPartialReady"
        "product writer path execution"
        "ProductPathWriterPathExec"
        "SELF-HOST-PRODUCT-PATH-OWNERSHIP"
        "productPathOwnershipInputsPartialReady"
        "productPathFreestandingOwnershipClaimed"
        "def productPathFreestandingOwnershipClaimed : Bool := true"
        "product path ownership inputs"
        "ProductPathOwnershipInputs"
        "SELF-HOST-PRODUCT-PATH-PERFORM"
        "productPathPerformPartialReady"
        "productPathFreestandingPerformClaimed"
        "def productPathFreestandingPerformClaimed : Bool := true"
        "productPathPerformDependsOnLake"
        "def productPathPerformDependsOnLake : Bool := false"
        "product path perform"
        "ProductPathPerform"
        "SELF-HOST-PRODUCT-PATH-PERFORM-STEP"
        "productPathPerformStepPartialReady"
        "def productPathPerformInstallLakeFreeEntrypointClaimed : Bool := true"
        "ProductPathPerformStep"
        "product path perform step"
        "SELF-HOST-PRODUCT-PATH-PERFORM-READ"
        "productPathPerformReadPartialReady"
        "def productPathPerformReadEntrypointClaimed : Bool := true"
        "def productPathPerformReadDependsOnLake : Bool := true"
        "ProductPathReadSsot"
        "product path perform read"
        "SELF-HOST-PRODUCT-PATH-PERFORM-COMPOSE"
        "productPathPerformComposePartialReady"
        "def productPathPerformComposeEntrypointClaimed : Bool := true"
        "def productPathPerformComposeDependsOnLake : Bool := true"
        "ProductPathComposePlan"
        "product path perform compose"
        "SELF-HOST-PRODUCT-PATH-PERFORM-WRITE-HC"
        "productPathPerformWriteHcPartialReady"
        "def productPathPerformWriteHcEntrypointClaimed : Bool := true"
        "def productPathPerformWriteHcDependsOnLake : Bool := true"
        "ProductPathWriteHc"
        "product path perform write"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-GAP"
        "productPathFreestandingCapablePartialReady"
        "def productPathFreestandingCapableInstallOnly : Bool := true"
        "def productPathFreestandingCapableRead : Bool := true"
        "def productPathFreestandingCapableCompose : Bool := true"
        "def productPathFreestandingCapableWriteHc : Bool := true"
        "def productPathFreestandingCapableFullPerform : Bool := false"
        "Capable"
        "product path freestanding capable gap"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-STEP-CONTRACT"
        "productPathFreestandingCapableStepContractPartialReady"
        "def productPathFreestandingCapableStepContractAuthorityNotEmit : Bool := true"
        "def productPathFreestandingCapableStepContractReadSatisfied : Bool := true"
        "def productPathFreestandingCapableStepContractComposeSatisfied : Bool := true"
        "def productPathFreestandingCapableStepContractWriteHcSatisfied : Bool := true"
        "def productPathFreestandingCapableStepContractFullSatisfied : Bool := false"
        "def stepContractFull : Bool := true"
        "CapableStepContract"
        "product path freestanding capable step contract"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-READ"
        "productPathFreestandingCapableReadPartialReady"
        "def productPathFreestandingCapableReadEntrypointClaimed : Bool := true"
        "def productPathFreestandingCapableReadAuthorityNotEmit : Bool := true"
        "def productPathFreestandingCapableReadDependsOnLake : Bool := true"
        "CapableRead"
        "freestandingCapableReadDualSsot"
        "product path freestanding capable read"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-COMPOSE"
        "productPathFreestandingCapableComposePartialReady"
        "def productPathFreestandingCapableComposeEntrypointClaimed : Bool := true"
        "def productPathFreestandingCapableComposeAuthorityNotEmit : Bool := true"
        "def productPathFreestandingCapableComposeDependsOnLake : Bool := true"
        "CapableCompose"
        "freestandingCapableComposePlanApplyBody"
        "product path freestanding capable compose"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-WRITE-HC"
        "productPathFreestandingCapableWriteHcPartialReady"
        "def productPathFreestandingCapableWriteHcEntrypointClaimed : Bool := true"
        "def productPathFreestandingCapableWriteHcAuthorityNotEmit : Bool := true"
        "def productPathFreestandingCapableWriteHcDependsOnLake : Bool := true"
        "CapableWriteHc"
        "freestandingCapableWriteFreestandingHc"
        "product path freestanding capable write"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-REGENERATE"
        "productPathFreestandingCapableRegeneratePartialReady"
        "def productPathFreestandingCapableRegenerateEntrypointClaimed : Bool := true"
        "def productPathFreestandingCapableRegenerateAuthorityNotEmit : Bool := true"
        "def productPathFreestandingCapableRegenerateDependsOnLake : Bool := true"
        "def productPathFreestandingCapableRegenerateInstallOutOpen : Bool := false"
        "CapableRegenerate"
        "freestandingCapableOrderedRegenerate"
        "product path freestanding capable regenerate"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-INSTALL-OUT"
        "productPathFreestandingCapableInstallOutPartialReady"
        "def productPathFreestandingCapableInstallOutEntrypointClaimed : Bool := true"
        "def productPathFreestandingCapableInstallOutAuthorityNotEmit : Bool := true"
        "def productPathFreestandingCapableInstallOutDependsOnLake : Bool := true"
        "InstallOut"
        "freestandingCapableInstallFreestandingOut"
        "product path freestanding capable install out"
        "SELF-HOST-PRODUCT-PATH-FREESTANDING-CAPABLE-FULL-BAR"
        "productPathFreestandingCapableFullBarPartialReady"
        "def productPathFreestandingCapableFullBarStepContractsClosed : Bool := true"
        "def productPathFreestandingCapableFullBarInstallOutClosed : Bool := true"
        "def productPathFreestandingCapableFullBarOrderedPipelineJoined : Bool := true"
        "def productPathFreestandingCapableFullBarOwnershipRegenerateWithoutLake : Bool := true"
        "def productPathFreestandingCapableFullBarCapableLakeFree : Bool := true"
        "def productPathFreestandingCapableFullBarDependsOnLake : Bool := true"
        "CapableFullBar"
        "product path freestanding capable full bar"
        "SELF-HOST-PRODUCT-PATH-OWNERSHIP-REGENERATE"
        "productPathOwnershipRegeneratePartialReady"
        "def productPathOwnershipRegenerateInstallLakeFree : Bool := true"
        "def productPathOwnershipRegenerateReadLakeFree : Bool := true"
        "def productPathOwnershipRegenerateComposeLakeFree : Bool := true"
        "def productPathOwnershipRegenerateWriteHcLakeFree : Bool := true"
        "def productPathOwnershipRegenerateLakeFreeJoinClaimed : Bool := true"
        "def productPathOwnershipRegenerateProductPathAuthorityClaimed : Bool := true"
        "def productPathOwnershipRegenerateWithoutLake : Bool := true"
        "def productPathOwnershipRegenerateDependsOnLake : Bool := true"
        "def productPathOwnershipRegenerateInstallPathClaimed : Bool := true"
        "def productPathOwnershipRegenerateReadPathClaimed : Bool := true"
        "def productPathOwnershipRegenerateComposePathClaimed : Bool := true"
        "def productPathOwnershipRegenerateWriteHcPathClaimed : Bool := true"
        "ProductPathOwnershipRegenerate"
        "product path ownership regenerate"
        "SELF-HOST-PRODUCT-PATH-PERFORM-EVIDENCE"
        "productPathFreestandingPerformEvidencePartialReady"
        "def productPathFreestandingPerformEvidenceClaimed : Bool := true"
        "def productPathFreestandingPerformClaimed : Bool := true"
        "def productPathPerformDependsOnLake : Bool := false"
        "PerformEvidence"
        "product path freestanding perform evidence"
        "SELF-HOST-PRODUCT-PATH-PERFORM-OFFICIAL-PATH"
        "productPathFreestandingPerformOfficialPathPartialReady"
        "def productPathFreestandingPerformOfficialPathGapMeasured : Bool := true"
        "def productPathFreestandingPerformClaimed : Bool := true"
        "def productPathPerformDependsOnLake : Bool := false"
        "def productPathOfficialPathStillUsesFreestandingEmit : Bool := false"
        "def productPathOfficialPathStillUsesLake : Bool := false"
        "def productPathOfficialPathRetireFreestandingEmitRequired : Bool := false"
        "OfficialPath"
        "product path freestanding perform official path"
        "SELF-HOST-PRODUCT-PATH-PERFORM-OFFICIAL-PATH-ALTERNATE"
        "productPathFreestandingPerformOfficialPathAlternatePartialReady"
        "def productPathFreestandingPerformOfficialPathAlternateMeasured : Bool := true"
        "def productPathOfficialPathAlternateWriterPresent : Bool := true"
        "def productPathOfficialPathAlternateNotOfficial : Bool := false"
        "def productPathOfficialPathDualEqualityBlocksRetirement : Bool := false"
        "def productPathFreestandingPerformClaimed : Bool := true"
        "def productPathPerformDependsOnLake : Bool := false"
        "def productPathOfficialPathStillUsesFreestandingEmit : Bool := false"
        "def productPathOfficialPathStillUsesLake : Bool := false"
        "def productPathOfficialPathRetireFreestandingEmitRequired : Bool := false"
        "OfficialPathAlternate"
        "product path freestanding perform official path alternate"
        "FULL-BAR-REQ-OWNERSHIP-CLAIMED-WITH-EVIDENCE"
        "OwnershipClaimed"
        "SelfApplyFsClose"
        "SelfApplyFsTheorems"
        "selfApplyFsCloseModuleCite"
      ];
      anyGroups = [
        [
          "selfApplyFsSurfaceOk"
          "freestandingSelfApplyPathReady"
          "freestandingParityLadderReady"
        ]
      ];
    }
    {
      # SelfApplyFsClose: close-path PartialReady B34..complete (same namespace).
      rel = "src/systems/SystemsLean/SelfApplyFsClose.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SelfApplyFsClose"
        "SystemsLean.SelfApplyFsClose"
        "import SystemsLean.SelfApplyFs"
        "SELF-HOST-PRODUCT-PATH-PERFORM-DUAL-EQUALITY-WRITE-PARITY"
        "productPathFreestandingPerformDualEqualityWriteParityPartialReady"
        "SELF-HOST-PRODUCT-PATH-PERFORM-DUAL-EQUALITY-WRITE-CLOSE-PATH"
        "productPathFreestandingPerformDualEqualityWriteClosePathPartialReady"
        "SELF-HOST-PRODUCT-PATH-PERFORM-DUAL-EQUALITY-WRITE-API"
        "productPathFreestandingPerformDualEqualityWriteApiPartialReady"
        "SELF-HOST-PRODUCT-PATH-PERFORM-DUAL-EQUALITY-WRITE-CAPABLE-GAP"
        "productPathFreestandingPerformDualEqualityWriteCapableGapPartialReady"
        "SELF-HOST-PRODUCT-PATH-PERFORM-RETIRE-OFFICIAL"
        "productPathOfficialPathRetireOfficialPartialReady"
        "SELF-HOST-PRODUCT-PATH-PERFORM-CLAIMED"
        "productPathFreestandingPerformClaimedPartialReady"
        "SELF-HOST-PRODUCT-PATH-OWNERSHIP-CLAIMED"
        "productPathFreestandingOwnershipClaimedPartialReady"
        "stepContractFullPartialReady"
        "freestandingProductSelfHostCompletePartialReady"
        "SELF-HOST-FREESTANDING-PRODUCT-COMPLETE"
        "FREESTANDING-DUAL-EQUALITY-WRITE-CLOSE-STEP-OWNERSHIP-CLAIMED"
        "Not freestanding residual free"
        "Not PROVABLY"
      ];
    }
    {
      # SelfApplyFsTheorems: SELF-APPLY-FS-THEOREM + SELF-APPLY-FS-SMOKE
      # (same namespace SelfApplyFs; long-file role module split).
      rel = "src/systems/SystemsLean/SelfApplyFsTheorems.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SelfApplyFsTheorems"
        "SystemsLean.SelfApplyFsTheorems"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.SelfApplyFsClose"
        "SELF-APPLY-FS-THEOREM"
        "HOST-SELF-APPLY-FS-THEOREM"
        "SELF-APPLY-FS-SMOKE"
        "HOST-SELF-APPLY-FS-SMOKE"
        "example"
        "stageId_eq"
        "hostSelfApplyFsId_eq"
        "freestandingSelfApplyReady_true"
        "freestandingProductSelfHostComplete_true"
        "selfApplyFsDoesNotComplete_false"
        "freestandingSelfApplyPathReady_true"
        "productKernelSelfApplyPartialReady_true"
        "productOutKernelEvidencePartialReady_true"
        "productPathHostLakeBootstrapPartialReady_true"
        "productPathHostLakeBootstrapRemains_true"
        "productWriterSurfacePartialReady_true"
        "productWriterPathPlanPartialReady_true"
        "productWriterPathExecutionPartialReady_true"
        "productPathOwnershipInputsPartialReady_true"
        "productPathPerformPartialReady_true"
        "productPathPerformStepPartialReady_true"
        "productPathPerformReadPartialReady_true"
        "productPathPerformComposePartialReady_true"
        "productPathPerformWriteHcPartialReady_true"
        "productPathFreestandingCapablePartialReady_true"
        "productPathFreestandingCapableStepContractPartialReady_true"
        "productPathFreestandingCapableReadPartialReady_true"
        "productPathFreestandingCapableComposePartialReady_true"
        "productPathFreestandingCapableWriteHcPartialReady_true"
        "productPathFreestandingCapableRegeneratePartialReady_true"
        "productPathFreestandingCapableInstallOutPartialReady_true"
        "productPathFreestandingCapableFullBarPartialReady_true"
        "productPathOwnershipRegeneratePartialReady_true"
        "productPathFreestandingPerformEvidencePartialReady_true"
        "productPathFreestandingPerformOfficialPathPartialReady_true"
        "productPathFreestandingPerformOfficialPathAlternatePartialReady_true"
        "productPathFreestandingPerformDualEqualityWriteParityPartialReady_true"
        "productPathFreestandingPerformDualEqualityWriteClosePathPartialReady_true"
        "productPathFreestandingPerformDualEqualityWriteApiPartialReady_true"
        "productPathFreestandingPerformDualEqualityWriteCapableGapPartialReady_true"
        "productPathOfficialPathRetireOfficialPartialReady_true"
        "productPathFreestandingPerformClaimedPartialReady_true"
        "productPathFreestandingOwnershipClaimedPartialReady_true"
        "stepContractFullPartialReady_true"
        "stepContractFull_true"
        "stepContractFullMeasured_true"
        "freestandingProductSelfHostCompletePartialReady_true"
        "freestandingProductSelfHostCompleteMeasured_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "example"
        "example : freestandingProductSelfHostComplete = true"
        "example : freestandingSelfApplyReady = true"
        "example : selfApplyFsDoesNotComplete = false"
        "example : freestandingParityLadderReady = true"
        "example : freestandingEmitParityReady = true"
        "theorem freestandingSelfApplyReady_true"
        "theorem freestandingProductSelfHostComplete_true"
        "theorem selfApplyFsDoesNotComplete_false"
        "theorem productKernelSelfApplyPartialReady_true"
        "example : productKernelSelfApplyPartialReady = true"
        "theorem productOutKernelEvidencePartialReady_true"
        "example : productOutKernelEvidencePartialReady = true"
        "theorem productPathHostLakeBootstrapPartialReady_true"
        "theorem productPathHostLakeBootstrapRemains_true"
        "example : productPathHostLakeBootstrapPartialReady = true"
        "example : productPathHostLakeBootstrapRemains = true"
        "theorem productWriterSurfacePartialReady_true"
        "example : productWriterSurfacePartialReady = true"
        "theorem productWriterPathPlanPartialReady_true"
        "example : productWriterPathPlanPartialReady = true"
        "theorem productWriterPathExecutionPartialReady_true"
        "example : productWriterPathExecutionPartialReady = true"
        "theorem productPathOwnershipInputsPartialReady_true"
        "theorem productPathFreestandingOwnershipClaimed_true"
        "example : productPathOwnershipInputsPartialReady = true"
        "example : productPathFreestandingOwnershipClaimed = true"
        "theorem productPathPerformPartialReady_true"
        "theorem productPathFreestandingPerformClaimed_true"
        "theorem productPathPerformDependsOnLake_false"
        "example : productPathPerformPartialReady = true"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathPerformStepPartialReady_true"
        "theorem productPathPerformInstallLakeFreeEntrypointClaimed_true"
        "example : productPathPerformStepPartialReady = true"
        "example : productPathPerformInstallLakeFreeEntrypointClaimed = true"
        "theorem productPathPerformReadPartialReady_true"
        "theorem productPathPerformReadDependsOnLake_true"
        "theorem productPathPerformReadEntrypointClaimed_true"
        "example : productPathPerformReadPartialReady = true"
        "example : productPathPerformReadEntrypointClaimed = true"
        "example : productPathPerformReadDependsOnLake = true"
        "theorem productPathPerformComposePartialReady_true"
        "theorem productPathPerformComposeDependsOnLake_true"
        "theorem productPathPerformComposeEntrypointClaimed_true"
        "example : productPathPerformComposePartialReady = true"
        "example : productPathPerformComposeEntrypointClaimed = true"
        "example : productPathPerformComposeDependsOnLake = true"
        "theorem productPathPerformWriteHcPartialReady_true"
        "theorem productPathPerformWriteHcDependsOnLake_true"
        "theorem productPathPerformWriteHcEntrypointClaimed_true"
        "example : productPathPerformWriteHcPartialReady = true"
        "example : productPathPerformWriteHcEntrypointClaimed = true"
        "example : productPathPerformWriteHcDependsOnLake = true"
        "theorem productPathFreestandingCapablePartialReady_true"
        "theorem productPathFreestandingCapableInstallOnly_true"
        "theorem productPathFreestandingCapableFullPerform_false"
        "theorem productPathFreestandingCapableRead_true"
        "theorem productPathFreestandingCapableCompose_true"
        "theorem productPathFreestandingCapableWriteHc_true"
        "example : productPathFreestandingCapablePartialReady = true"
        "example : productPathFreestandingCapableInstallOnly = true"
        "example : productPathFreestandingCapableFullPerform = false"
        "example : productPathFreestandingCapableRead = true"
        "example : productPathFreestandingCapableCompose = true"
        "example : productPathFreestandingCapableWriteHc = true"
        "theorem productPathFreestandingCapableStepContractPartialReady_true"
        "theorem productPathFreestandingCapableStepContractAuthorityNotEmit_true"
        "theorem productPathFreestandingCapableStepContractReadSatisfied_true"
        "theorem productPathFreestandingCapableStepContractComposeSatisfied_true"
        "theorem productPathFreestandingCapableStepContractWriteHcSatisfied_true"
        "theorem productPathFreestandingCapableStepContractFullSatisfied_false"
        "theorem stepContractFull_true"
        "example : productPathFreestandingCapableStepContractPartialReady = true"
        "example : productPathFreestandingCapableStepContractAuthorityNotEmit = true"
        "example : productPathFreestandingCapableStepContractReadSatisfied = true"
        "example : productPathFreestandingCapableStepContractComposeSatisfied = true"
        "example : productPathFreestandingCapableStepContractWriteHcSatisfied = true"
        "example : productPathFreestandingCapableStepContractFullSatisfied = false"
        "theorem productPathFreestandingCapableReadPartialReady_true"
        "theorem productPathFreestandingCapableReadEntrypointClaimed_true"
        "theorem productPathFreestandingCapableReadAuthorityNotEmit_true"
        "theorem productPathFreestandingCapableReadDependsOnLake_true"
        "example : productPathFreestandingCapableReadPartialReady = true"
        "example : productPathFreestandingCapableReadEntrypointClaimed = true"
        "example : productPathFreestandingCapableReadAuthorityNotEmit = true"
        "example : productPathFreestandingCapableReadDependsOnLake = true"
        "theorem productPathFreestandingCapableComposePartialReady_true"
        "theorem productPathFreestandingCapableComposeEntrypointClaimed_true"
        "theorem productPathFreestandingCapableComposeAuthorityNotEmit_true"
        "theorem productPathFreestandingCapableComposeDependsOnLake_true"
        "example : productPathFreestandingCapableComposePartialReady = true"
        "example : productPathFreestandingCapableComposeEntrypointClaimed = true"
        "example : productPathFreestandingCapableComposeAuthorityNotEmit = true"
        "example : productPathFreestandingCapableComposeDependsOnLake = true"
        "theorem productPathFreestandingCapableWriteHcPartialReady_true"
        "theorem productPathFreestandingCapableWriteHcEntrypointClaimed_true"
        "theorem productPathFreestandingCapableWriteHcAuthorityNotEmit_true"
        "theorem productPathFreestandingCapableWriteHcDependsOnLake_true"
        "example : productPathFreestandingCapableWriteHcPartialReady = true"
        "example : productPathFreestandingCapableWriteHcEntrypointClaimed = true"
        "example : productPathFreestandingCapableWriteHcAuthorityNotEmit = true"
        "example : productPathFreestandingCapableWriteHcDependsOnLake = true"
        "theorem productPathFreestandingCapableRegeneratePartialReady_true"
        "theorem productPathFreestandingCapableRegenerateEntrypointClaimed_true"
        "theorem productPathFreestandingCapableRegenerateAuthorityNotEmit_true"
        "theorem productPathFreestandingCapableRegenerateDependsOnLake_true"
        "theorem productPathFreestandingCapableRegenerateInstallOutOpen_false"
        "example : productPathFreestandingCapableRegeneratePartialReady = true"
        "example : productPathFreestandingCapableRegenerateEntrypointClaimed = true"
        "example : productPathFreestandingCapableRegenerateAuthorityNotEmit = true"
        "example : productPathFreestandingCapableRegenerateDependsOnLake = true"
        "example : productPathFreestandingCapableRegenerateInstallOutOpen = false"
        "theorem productPathFreestandingCapableInstallOutPartialReady_true"
        "theorem productPathFreestandingCapableInstallOutEntrypointClaimed_true"
        "theorem productPathFreestandingCapableInstallOutAuthorityNotEmit_true"
        "theorem productPathFreestandingCapableInstallOutDependsOnLake_true"
        "example : productPathFreestandingCapableInstallOutPartialReady = true"
        "example : productPathFreestandingCapableInstallOutEntrypointClaimed = true"
        "example : productPathFreestandingCapableInstallOutAuthorityNotEmit = true"
        "example : productPathFreestandingCapableInstallOutDependsOnLake = true"
        "theorem productPathFreestandingCapableFullBarPartialReady_true"
        "theorem productPathFreestandingCapableFullBarStepContractsClosed_true"
        "theorem productPathFreestandingCapableFullBarInstallOutClosed_true"
        "theorem productPathFreestandingCapableFullBarOrderedPipelineJoined_true"
        "theorem productPathFreestandingCapableFullBarOwnershipRegenerateWithoutLake_true"
        "theorem productPathFreestandingCapableFullBarCapableLakeFree_true"
        "example : productPathFreestandingCapableFullBarPartialReady = true"
        "example : productPathFreestandingCapableFullBarStepContractsClosed = true"
        "example : productPathFreestandingCapableFullBarOwnershipRegenerateWithoutLake"
        "theorem productPathOwnershipRegeneratePartialReady_true"
        "theorem productPathOwnershipRegenerateInstallLakeFree_true"
        "theorem productPathOwnershipRegenerateReadLakeFree_true"
        "theorem productPathOwnershipRegenerateReadPathClaimed_true"
        "theorem productPathOwnershipRegenerateComposeLakeFree_true"
        "theorem productPathOwnershipRegenerateComposePathClaimed_true"
        "theorem productPathOwnershipRegenerateWriteHcLakeFree_true"
        "theorem productPathOwnershipRegenerateWriteHcPathClaimed_true"
        "theorem productPathOwnershipRegenerateLakeFreeJoinClaimed_true"
        "theorem productPathOwnershipRegenerateProductPathAuthorityClaimed_true"
        "theorem productPathOwnershipRegenerateWithoutLake_true"
        "theorem productPathOwnershipRegenerateDependsOnLake_true"
        "theorem productPathOwnershipRegenerateInstallPathClaimed_true"
        "example : productPathOwnershipRegeneratePartialReady = true"
        "example : productPathOwnershipRegenerateInstallLakeFree = true"
        "example : productPathOwnershipRegenerateWithoutLake = true"
        "theorem productPathFreestandingPerformEvidenceClaimed_true"
        "theorem productPathFreestandingPerformEvidencePartialReady_true"
        "example : productPathFreestandingPerformEvidencePartialReady = true"
        "example : productPathFreestandingPerformEvidenceClaimed = true"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathFreestandingPerformOfficialPathGapMeasured_true"
        "theorem productPathFreestandingPerformOfficialPathPartialReady_true"
        "example : productPathFreestandingPerformOfficialPathPartialReady = true"
        "example : productPathFreestandingPerformOfficialPathGapMeasured = true"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathFreestandingPerformOfficialPathAlternateMeasured_true"
        "theorem productPathFreestandingPerformOfficialPathAlternatePartialReady_true"
        "example : productPathFreestandingPerformOfficialPathAlternatePartialReady = true"
        "example : productPathFreestandingPerformOfficialPathAlternateMeasured = true"
        "example : productPathOfficialPathDualEqualityBlocksRetirement = false"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathFreestandingPerformDualEqualityWriteParityMeasured_true"
        "theorem productPathFreestandingPerformDualEqualityWriteParityPartialReady_true"
        "example : productPathFreestandingPerformDualEqualityWriteParityPartialReady = true"
        "example : productPathFreestandingPerformDualEqualityWriteParityMeasured = true"
        "example : productPathDualEqualityWriteParityGapOpen = false"
        "example : productPathCapableWriteStructuralNotDualEquality = false"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathFreestandingPerformDualEqualityWriteClosePathMeasured_true"
        "theorem productPathFreestandingPerformDualEqualityWriteClosePathPartialReady_true"
        "example : productPathFreestandingPerformDualEqualityWriteClosePathPartialReady = true"
        "example : productPathFreestandingPerformDualEqualityWriteClosePathMeasured = true"
        "example : productPathDualEqualityWriteClosePathNamed = true"
        "example : productPathDualEqualityWriteClosePathNotGapClosed = false"
        "example : productPathDualEqualityWriteParityGapOpen = false"
        "example : productPathCapableWriteStructuralNotDualEquality = false"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathFreestandingPerformDualEqualityWriteApiMeasured_true"
        "theorem productPathFreestandingPerformDualEqualityWriteApiPartialReady_true"
        "example : productPathFreestandingPerformDualEqualityWriteApiPartialReady = true"
        "example : productPathFreestandingPerformDualEqualityWriteApiMeasured = true"
        "example : productPathDualEqualityWriteApiPresent = true"
        "example : productPathDualEqualityWriteApiAuthorityNotEmit = true"
        "example : productPathDualEqualityWriteApiNotOfficial = true"
        "example : productPathDualEqualityWriteApiStepAdvanced = true"
        "example : productPathDualEqualityWriteParityGapOpen = false"
        "example : productPathCapableWriteStructuralNotDualEquality = false"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathFreestandingPerformDualEqualityWriteCapableGapMeasured_true"
        "theorem productPathFreestandingPerformDualEqualityWriteCapableGapPartialReady_true"
        "example : productPathFreestandingPerformDualEqualityWriteCapableGapPartialReady = true"
        "example : productPathFreestandingPerformDualEqualityWriteCapableGapMeasured = true"
        "example : productPathDualEqualityWriteCapableGapClosed = true"
        "example : productPathCapableWriteDualEqualityLive = true"
        "example : productPathDualEqualityWriteCapableGapStepAdvanced = true"
        "example : productPathDualEqualityWriteParityGapOpen = false"
        "example : productPathCapableWriteStructuralNotDualEquality = false"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathOfficialPathRetireOfficialMeasured_true"
        "theorem productPathOfficialPathRetireOfficialPartialReady_true"
        "example : productPathOfficialPathRetireOfficialPartialReady = true"
        "example : productPathOfficialPathRetireOfficialMeasured = true"
        "example : productPathOfficialPathUsesDualEqualityWrite = true"
        "example : productPathOfficialPathStillUsesFreestandingEmit = false"
        "example : productPathOfficialPathDualEqualityBlocksRetirement = false"
        "example : productPathFreestandingPerformClaimed = true"
        "theorem productPathFreestandingPerformClaimedMeasured_true"
        "theorem productPathFreestandingPerformClaimedPartialReady_true"
        "theorem productPathFreestandingPerformClaimed_true"
        "example : productPathFreestandingPerformClaimedPartialReady = true"
        "example : productPathFreestandingPerformClaimedMeasured = true"
        "example : productPathFreestandingPerformClaimed = true"
        "example : productPathOfficialPathUsesDualEqualityWrite = true"
        "example : productPathOfficialPathStillUsesFreestandingEmit = false"
        "example : productPathOfficialPathDualEqualityBlocksRetirement = false"
        "example : productPathFreestandingOwnershipClaimed = true"
        "example : freestandingProductSelfHostComplete = true"
        "theorem productPathFreestandingOwnershipClaimedMeasured_true"
        "theorem productPathFreestandingOwnershipClaimedPartialReady_true"
        "theorem productPathFreestandingOwnershipClaimed_true"
        "example : productPathFreestandingOwnershipClaimedPartialReady = true"
        "example : productPathFreestandingOwnershipClaimedMeasured = true"
        "example : productPathFreestandingOwnershipClaimed = true"
        "example : productPathFreestandingPerformClaimed = true"
        "example : stepContractFull = true"
        "example : freestandingProductSelfHostComplete = true"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not full LLVM backend"
      ];
      anyGroups = [ ];
    }
    {
      # B2 KERNEL-SELF-APPLY module (land-time B-bar HOST-EMIT cites).
      # Batch-33 PartialReady bulk + dual-pin thin batch 1 historical stage/bar
      # string authority. SelfApplyFs tip keeps chain fold only.
      # No living-tip claim true defs on this land-time module.
      # Name KernelSelfApply (not SelfApply) -- SelfApply.lean is host structural.
      # Long-file split: KERNEL-SELF-APPLY-THEOREM + SMOKE in KernelSelfApplyTheorems
      # (same namespace).
      rel = "src/systems/SystemsLean/KernelSelfApply.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_KERNEL_SELF_APPLY_V0"
        "HOST-SELF-HOST-KERNEL-SELF-APPLY"
        "SELF-HOST-KERNEL-SELF-APPLY"
        "productKernelBarSurfaceOk"
        "productKernelSelfApplyPartialReady"
        "def productKernelSelfApplyPartialReady : Bool :="
        "KERNEL-SELF-APPLY-THEOREM"
        "HOST-KERNEL-SELF-APPLY-THEOREM"
        "KERNEL-SELF-APPLY-SMOKE"
        "HOST-KERNEL-SELF-APPLY-SMOKE"
        "KernelSelfApplyTheorems"
        # Greppable theorem cite (live def in Theorems module; same split pattern
        # as ProductOutKernel / ProductPathPerform).
        "theorem productKernelSelfApplyPartialReady_true"
        "SystemsLean.KernelSelfApply"
        "KernelSelfApply"
        "productKernelSelfApplyModuleCite"
        "productKernelBarMult"
        "productKernelBarLinear"
        "productKernelBarErasure"
        "productKernelBarTypes"
        "productKernelBarProgram"
        "HOST-EMIT-MULT"
        "HOST-EMIT-LINEAR"
        "HOST-EMIT-ERASURE"
        "HOST-EMIT-TYPES"
        "HOST-EMIT-PROGRAM"
        "RUNTIME-FS"
        "UNIT_SURFACE"
        "Not freestanding emit residual free"
        "Not residual free"
        "Not PROVABLY"
      ];
    }
  ];
}
